title: Close
collated: true
variants:
  - name: default
  - name: small
    context:
      modifiers: close-button-small
  - name: large
    context:
      modifiers: close-button-large
  - name: xlarge
    context:
      modifiers: close-button-xlarge
