[build]
  command = """
    (cd ../lib && npm ci --ignore-scripts && npm run build:no-sync) &&
    (cd ../schema && npm ci && npm run build) &&
    (cd ../renderers/react && npm ci --ignore-scripts && npm run build) &&
    npm ci --ignore-scripts &&
    npm run build
  """
  publish = "dist"
