// AUTO-GENERATED by v2/schema/scripts/codegen.ts — do not edit by hand
// Run: npm run codegen   (from v2/schema/)
// Source: v2/lib/src/components/*/core/_*.ts

import { defineComponent, h, type PropType, type VNode } from 'vue';
import type { AgNode } from '@agnosticui/schema';
import { VueAccordion } from 'agnosticui-core/accordion/vue';
import { VueAlert } from 'agnosticui-core/alert/vue';
import { VueAspectRatio } from 'agnosticui-core/aspect-ratio/vue';
import { VueAvatar } from 'agnosticui-core/avatar/vue';
import { VueBadge } from 'agnosticui-core/badge/vue';
import { VueBadgeFx } from 'agnosticui-core/badge-fx/vue';
import { VueBreadcrumb } from 'agnosticui-core/breadcrumb/vue';
import VueButton from 'agnosticui-core/button/vue';
import { VueButtonFx } from 'agnosticui-core/button-fx/vue';
import { VueCard } from 'agnosticui-core/card/vue';
import { VueCheckbox } from 'agnosticui-core/checkbox/vue';
import { VueDialog } from 'agnosticui-core/dialog/vue';
import { VueDivider } from 'agnosticui-core/divider/vue';
import { VueDrawer } from 'agnosticui-core/drawer/vue';
import { VueFieldset } from 'agnosticui-core/fieldset/vue';
import { VueHeader } from 'agnosticui-core/header/vue';
import { VueIcon } from 'agnosticui-core/icon/vue';
import { VueIconButton } from 'agnosticui-core/icon-button/vue';
import { VueIconButtonFx } from 'agnosticui-core/icon-button-fx/vue';
import { VueInput } from 'agnosticui-core/input/vue';
import { VueIntlFormatter } from 'agnosticui-core/intl-formatter/vue';
import { VueKbd } from 'agnosticui-core/kbd/vue';
import { VueLink } from 'agnosticui-core/link/vue';
import { VueLoader } from 'agnosticui-core/loader/vue';
import { VueMark } from 'agnosticui-core/mark/vue';
import { VueMessageBubble } from 'agnosticui-core/message-bubble/vue';
import { VuePopover } from 'agnosticui-core/popover/vue';
import { VueProgress } from 'agnosticui-core/progress/vue';
import { VueRadio } from 'agnosticui-core/radio/vue';
import { VueRating } from 'agnosticui-core/rating/vue';
import { VueSelect } from 'agnosticui-core/select/vue';
import { VueSelectionButton } from 'agnosticui-core/selection-button/vue';
import { VueSelectionButtonGroup } from 'agnosticui-core/selection-button-group/vue';
import { VueSelectionCard } from 'agnosticui-core/selection-card/vue';
import { VueSelectionCardGroup } from 'agnosticui-core/selection-card-group/vue';
import { VueSpinner } from 'agnosticui-core/spinner/vue';
import { VueTabs } from 'agnosticui-core/tabs/vue';
import { VueTag } from 'agnosticui-core/tag/vue';
import { VueToggle } from 'agnosticui-core/toggle/vue';
import { VueTooltip } from 'agnosticui-core/tooltip/vue';

type Actions = Record<string, (payload?: unknown) => void>;

/**
 * Create an action dispatcher bound to a given actions map.
 *
 * This is the XSS boundary: only aliases present in the map are called;
 * unknown aliases are silently ignored. No eval(), no dynamic code execution.
 */
export function createDispatcher(actions: Actions) {
  return (alias?: string, payload?: unknown): void => {
    if (alias) actions[alias]?.(payload);
  };
}

function doDispatch(alias: string | undefined, actions: Actions, payload?: unknown): void {
  if (alias) actions[alias]?.(payload);
}

function renderNode(
  node: AgNode,
  nodeMap: Map<string, AgNode>,
  actions: Actions,
): VNode | null {
  const renderChildren = (childIds?: string[]): (VNode | null)[] =>
    (childIds ?? []).map(id => {
      const child = nodeMap.get(id);
      return child ? renderNode(child, nodeMap, actions) : null;
    });

  switch (node.component) {
    case 'AgAccordion':
      return h(
        VueAccordion,
        {
        },
        { default: () => renderChildren(node.children) },
      );

    case 'AgAlert':
      return h(
        VueAlert,
        {
        variant: node.variant,
        bordered: node.bordered,
        rounded: node.rounded,
        borderedLeft: node.borderedLeft,
        dismissible: node.dismissible,
        onAlertDismiss: () => doDispatch(node.on_dismiss, actions),
        },
        { default: () => renderChildren(node.children) },
      );

    case 'AgAspectRatio':
      return h(
        VueAspectRatio,
        {
        width: node.width,
        height: node.height,
        maxWidth: node.maxWidth,
        },
      );

    case 'AgAvatar':
      return h(
        VueAvatar,
        {
        text: node.text,
        imgSrc: node.imgSrc,
        imgAlt: node.imgAlt,
        size: node.size,
        shape: node.shape,
        variant: node.variant,
        ariaLabel: node.ariaLabel,
        },
      );

    case 'AgBadge':
      return h(
        VueBadge,
        {
        variant: node.variant,
        size: node.size,
        dot: node.dot,
        value: node.value,
        max: node.max,
        interactive: node.interactive,
        statusLabel: node.statusLabel,
        live: node.live,
        hiddenFromAT: node.hiddenFromAT,
        },
        { default: () => renderChildren(node.children) },
      );

    case 'AgBadgeFx':
      return h(
        VueBadgeFx,
        {
        variant: node.variant,
        size: node.size,
        dot: node.dot,
        value: node.value,
        max: node.max,
        interactive: node.interactive,
        statusLabel: node.statusLabel,
        live: node.live,
        hiddenFromAT: node.hiddenFromAT,
        fx: node.fx,
        fxSpeed: node.fxSpeed,
        fxEase: node.fxEase,
        fxDisabled: node.fxDisabled,
        },
        { default: () => renderChildren(node.children) },
      );

    case 'AgBreadcrumb':
      return h(
        VueBreadcrumb,
        {
        type: node.type,
        primary: node.primary,
        ariaLabel: node.ariaLabel,
        onBreadcrumbClick: () => doDispatch(node.on_click, actions),
        },
      );

    case 'AgButton':
      return h(
        VueButton,
        {
        variant: node.variant,
        size: node.size,
        shape: node.shape,
        bordered: node.bordered,
        ghost: node.ghost,
        link: node.link,
        grouped: node.grouped,
        fullWidth: node.fullWidth,
        type: node.type,
        disabled: node.disabled,
        loading: node.loading,
        ariaLabel: node.ariaLabel,
        onClick: () => doDispatch(node.on_click, actions),
        onToggle: () => doDispatch(node.on_toggle, actions),
        },
        {
          default: () =>
            node.children?.length
              ? renderChildren(node.children)
              : ((node as { label?: string }).label ?? ''),
        },
      );

    case 'AgButtonFx':
      return h(
        VueButtonFx,
        {
        variant: node.variant,
        size: node.size,
        shape: node.shape,
        bordered: node.bordered,
        ghost: node.ghost,
        link: node.link,
        grouped: node.grouped,
        fullWidth: node.fullWidth,
        type: node.type,
        disabled: node.disabled,
        loading: node.loading,
        ariaLabel: node.ariaLabel,
        fx: node.fx,
        fxSpeed: node.fxSpeed,
        fxEase: node.fxEase,
        fxDisabled: node.fxDisabled,
        onClick: () => doDispatch(node.on_click, actions),
        onToggle: () => doDispatch(node.on_toggle, actions),
        },
        {
          default: () =>
            node.children?.length
              ? renderChildren(node.children)
              : ((node as { label?: string }).label ?? ''),
        },
      );

    case 'AgCard':
      return h(
        VueCard,
        {
        stacked: node.stacked,
        shadow: node.shadow,
        animated: node.animated,
        rounded: node.rounded,
        variant: node.variant,
        hasMedia: node.hasMedia,
        mediaPosition: node.mediaPosition,
        },
        { default: () => renderChildren(node.children) },
      );

    case 'AgCheckbox':
      return h(
        VueCheckbox,
        {
        name: node.name,
        value: node.value,
        checked: node.checked,
        disabled: node.disabled,
        size: node.size,
        labelText: node.labelText,
        labelPosition: node.labelPosition,
        required: node.required,
        invalid: node.invalid,
        errorMessage: node.errorMessage,
        helpText: node.helpText,
        onClick: () => doDispatch(node.on_click, actions),
        onChange: () => doDispatch(node.on_change, actions),
        },
      );

    case 'AgDialog':
      return h(
        VueDialog,
        {
        open: node.open,
        heading: node.heading,
        description: node.description,
        noCloseOnEscape: node.noCloseOnEscape,
        noCloseOnBackdrop: node.noCloseOnBackdrop,
        showCloseButton: node.showCloseButton,
        drawerPosition: node.drawerPosition,
        onDialogOpen: () => doDispatch(node.on_open, actions),
        onDialogClose: () => doDispatch(node.on_close, actions),
        onDialogCancel: () => doDispatch(node.on_cancel, actions),
        },
        { default: () => renderChildren(node.children) },
      );

    case 'AgDivider':
      return h(
        VueDivider,
        {
        vertical: node.vertical,
        justify: node.justify,
        size: node.size,
        variant: node.variant,
        },
      );

    case 'AgDrawer':
      return h(
        VueDrawer,
        {
        open: node.open,
        heading: node.heading,
        description: node.description,
        noCloseOnEscape: node.noCloseOnEscape,
        noCloseOnBackdrop: node.noCloseOnBackdrop,
        showCloseButton: node.showCloseButton,
        position: node.position,
        onDrawerOpen: () => doDispatch(node.on_open, actions),
        onDrawerClose: () => doDispatch(node.on_close, actions),
        onDrawerCancel: () => doDispatch(node.on_cancel, actions),
        },
        { default: () => renderChildren(node.children) },
      );

    case 'AgFieldset':
      return h(
        VueFieldset,
        {
        legend: node.legend,
        bordered: node.bordered,
        layout: node.layout,
        legendHidden: node.legendHidden,
        },
        { default: () => renderChildren(node.children) },
      );

    case 'AgHeader':
      return h(
        VueHeader,
        {
        sticky: node.sticky,
        contentJustify: node.contentJustify,
        },
        { default: () => renderChildren(node.children) },
      );

    case 'AgIcon':
      return h(
        VueIcon,
        {
        size: node.size,
        type: node.type,
        noFill: node.noFill,
        },
      );

    case 'AgIconButton':
      return h(
        VueIconButton,
        {
        label: node.label,
        icon: node.icon,
        unicode: node.unicode,
        size: node.size,
        variant: node.variant,
        type: node.type,
        disabled: node.disabled,
        loading: node.loading,
        onIconButtonClick: () => doDispatch(node.on_click, actions),
        onIconButtonActivate: () => doDispatch(node.on_activate, actions),
        },
      );

    case 'AgIconButtonFx':
      return h(
        VueIconButtonFx,
        {
        label: node.label,
        icon: node.icon,
        unicode: node.unicode,
        size: node.size,
        variant: node.variant,
        type: node.type,
        disabled: node.disabled,
        loading: node.loading,
        fx: node.fx,
        fxSpeed: node.fxSpeed,
        fxEase: node.fxEase,
        fxDisabled: node.fxDisabled,
        onIconButtonClick: () => doDispatch(node.on_click, actions),
        onIconButtonActivate: () => doDispatch(node.on_activate, actions),
        },
      );

    case 'AgInput':
      return h(
        VueInput,
        {
        label: node.label,
        labelHidden: node.labelHidden,
        labelPosition: node.labelPosition,
        noLabel: node.noLabel,
        ariaLabel: node.ariaLabel,
        name: node.name,
        type: node.type,
        value: node.value,
        placeholder: node.placeholder,
        rows: node.rows,
        cols: node.cols,
        size: node.size,
        capsule: node.capsule,
        rounded: node.rounded,
        underlined: node.underlined,
        underlinedWithBackground: node.underlinedWithBackground,
        inline: node.inline,
        required: node.required,
        disabled: node.disabled,
        readonly: node.readonly,
        invalid: node.invalid,
        errorMessage: node.errorMessage,
        helpText: node.helpText,
        onClick: () => doDispatch(node.on_click, actions),
        onChange: () => doDispatch(node.on_change, actions),
        },
      );

    case 'AgIntlFormatter':
      return h(
        VueIntlFormatter,
        {
        type: node.type,
        value: node.value,
        lang: node.lang,
        date: node.date,
        weekday: node.weekday,
        era: node.era,
        year: node.year,
        month: node.month,
        day: node.day,
        hour: node.hour,
        minute: node.minute,
        second: node.second,
        timeZoneName: node.timeZoneName,
        timeZone: node.timeZone,
        hourFormat: node.hourFormat,
        dateStyle: node.dateStyle,
        timeStyle: node.timeStyle,
        noGrouping: node.noGrouping,
        currency: node.currency,
        currencyDisplay: node.currencyDisplay,
        minimumIntegerDigits: node.minimumIntegerDigits,
        minimumFractionDigits: node.minimumFractionDigits,
        maximumFractionDigits: node.maximumFractionDigits,
        minimumSignificantDigits: node.minimumSignificantDigits,
        maximumSignificantDigits: node.maximumSignificantDigits,
        },
      );

    case 'AgKbd':
      return h(
        VueKbd,
        {
        variant: node.variant,
        bordered: node.bordered,
        background: node.background,
        size: node.size,
        },
        { default: () => renderChildren(node.children) },
      );

    case 'AgLink':
      return h(
        VueLink,
        {
        href: node.href,
        variant: node.variant,
        isButton: node.isButton,
        buttonSize: node.buttonSize,
        buttonShape: node.buttonShape,
        buttonBordered: node.buttonBordered,
        external: node.external,
        disabled: node.disabled,
        ariaLabel: node.ariaLabel,
        onClick: () => doDispatch(node.on_click, actions),
        },
        { default: () => renderChildren(node.children) },
      );

    case 'AgLoader':
      return h(
        VueLoader,
        {
        size: node.size,
        ariaLabel: node.ariaLabel,
        },
      );

    case 'AgMark':
      return h(
        VueMark,
        {
        variant: node.variant,
        search: node.search,
        caseSensitive: node.caseSensitive,
        matchAll: node.matchAll,
        },
        { default: () => renderChildren(node.children) },
      );

    case 'AgMessageBubble':
      return h(
        VueMessageBubble,
        {
        from: node.from,
        message: node.message,
        time: node.time,
        author: node.author,
        avatarUrl: node.avatarUrl,
        footer: node.footer,
        variant: node.variant,
        },
        { default: () => renderChildren(node.children) },
      );

    case 'AgPopover':
      return h(
        VuePopover,
        {
        placement: node.placement,
        distance: node.distance,
        skidding: node.skidding,
        arrow: node.arrow,
        disabled: node.disabled,
        triggerType: node.triggerType,
        matchTriggerWidth: node.matchTriggerWidth,
        showCloseButton: node.showCloseButton,
        showHeader: node.showHeader,
        closeLabel: node.closeLabel,
        trapFocus: node.trapFocus,
        onShow: () => doDispatch(node.on_show, actions),
        onHide: () => doDispatch(node.on_hide, actions),
        },
        { default: () => renderChildren(node.children) },
      );

    case 'AgProgress':
      return h(
        VueProgress,
        {
        value: node.value,
        max: node.max,
        label: node.label,
        size: node.size,
        },
        { default: () => renderChildren(node.children) },
      );

    case 'AgRadio':
      return h(
        VueRadio,
        {
        name: node.name,
        value: node.value,
        checked: node.checked,
        disabled: node.disabled,
        size: node.size,
        theme: node.theme,
        labelText: node.labelText,
        labelPosition: node.labelPosition,
        label: node.label,
        labelHidden: node.labelHidden,
        noLabel: node.noLabel,
        required: node.required,
        invalid: node.invalid,
        errorMessage: node.errorMessage,
        helpText: node.helpText,
        onClick: () => doDispatch(node.on_click, actions),
        onChange: () => doDispatch(node.on_change, actions),
        },
      );

    case 'AgRating':
      return h(
        VueRating,
        {
        value: node.value,
        max: node.max,
        precision: node.precision,
        readonly: node.readonly,
        allowClear: node.allowClear,
        variant: node.variant,
        size: node.size,
        name: node.name,
        label: node.label,
        labelPosition: node.labelPosition,
        labelHidden: node.labelHidden,
        noLabel: node.noLabel,
        required: node.required,
        invalid: node.invalid,
        errorMessage: node.errorMessage,
        helpText: node.helpText,
        },
      );

    case 'AgSelect':
      return h(
        VueSelect,
        {
        size: node.size,
        multiple: node.multiple,
        disabled: node.disabled,
        name: node.name,
        multipleSize: node.multipleSize,
        label: node.label,
        labelPosition: node.labelPosition,
        labelHidden: node.labelHidden,
        noLabel: node.noLabel,
        required: node.required,
        invalid: node.invalid,
        errorMessage: node.errorMessage,
        helpText: node.helpText,
        onClick: () => doDispatch(node.on_click, actions),
        onChange: () => doDispatch(node.on_change, actions),
        },
      );

    case 'AgSelectionButton':
      return h(
        VueSelectionButton,
        {
        value: node.value,
        label: node.label,
        checked: node.checked,
        disabled: node.disabled,
        },
        { default: () => renderChildren(node.children) },
      );

    case 'AgSelectionButtonGroup':
      return h(
        VueSelectionButtonGroup,
        {
        type: node.type,
        name: node.name,
        legend: node.legend,
        legendHidden: node.legendHidden,
        theme: node.theme,
        size: node.size,
        shape: node.shape,
        value: node.value,
        values: node.values,
        disabled: node.disabled,
        required: node.required,
        onSelectionChange: (e: Event) => doDispatch(node.on_change, actions, (e as CustomEvent<{value: string}>).detail.value),
        },
        { default: () => renderChildren(node.children) },
      );

    case 'AgSelectionCard':
      return h(
        VueSelectionCard,
        {
        value: node.value,
        label: node.label,
        checked: node.checked,
        disabled: node.disabled,
        },
        { default: () => renderChildren(node.children) },
      );

    case 'AgSelectionCardGroup':
      return h(
        VueSelectionCardGroup,
        {
        type: node.type,
        name: node.name,
        legend: node.legend,
        legendHidden: node.legendHidden,
        theme: node.theme,
        value: node.value,
        values: node.values,
        disabled: node.disabled,
        required: node.required,
        onSelectionChange: (e: Event) => doDispatch(node.on_change, actions, (e as CustomEvent<{value: string}>).detail.value),
        },
        { default: () => renderChildren(node.children) },
      );

    case 'AgSpinner':
      return h(
        VueSpinner,
        {
        size: node.size,
        ariaLabel: node.ariaLabel,
        },
      );

    case 'AgTabs':
      return h(
        VueTabs,
        {
        activation: node.activation,
        activeTab: node.activeTab,
        orientation: node.orientation,
        ariaLabel: node.ariaLabel,
        },
        { default: () => renderChildren(node.children) },
      );

    case 'AgTag':
      return h(
        VueTag,
        {
        variant: node.variant,
        shape: node.shape,
        uppercase: node.uppercase,
        removable: node.removable,
        onTagRemove: () => doDispatch(node.on_remove, actions),
        },
        { default: () => renderChildren(node.children) },
      );

    case 'AgToggle':
      return h(
        VueToggle,
        {
        label: node.label,
        labelPosition: node.labelPosition,
        labelHidden: node.labelHidden,
        noLabel: node.noLabel,
        checked: node.checked,
        size: node.size,
        variant: node.variant,
        disabled: node.disabled,
        readonly: node.readonly,
        required: node.required,
        invalid: node.invalid,
        errorMessage: node.errorMessage,
        helpText: node.helpText,
        name: node.name,
        value: node.value,
        onClick: () => doDispatch(node.on_click, actions),
        onToggleChange: () => doDispatch(node.on_change, actions),
        },
      );

    case 'AgTooltip':
      return h(
        VueTooltip,
        {
        content: node.content,
        placement: node.placement,
        distance: node.distance,
        skidding: node.skidding,
        trigger: node.trigger,
        disabled: node.disabled,
        onShow: () => doDispatch(node.on_show, actions),
        onHide: () => doDispatch(node.on_hide, actions),
        },
      );

    case 'AgText':
      return h(node.el ?? 'span', { key: node.id }, node.text ?? '');

    default:
      return null;
  }
}

/**
 * AgDynamicRenderer (Vue)
 *
 * Consumes a flat array of AgNode objects and renders them using the
 * AgnosticUI Vue wrapper components. Nodes not referenced as children
 * by any other node are treated as roots.
 *
 * Actions are routed through a whitelist map — unknown aliases are
 * silently ignored, providing an XSS boundary.
 */
export const AgDynamicRenderer = defineComponent({
  name: 'AgDynamicRenderer',

  props: {
    nodes: {
      type: Array as PropType<AgNode[]>,
      required: true,
    },
    actions: {
      type: Object as PropType<Actions>,
      default: () => ({}),
    },
  },

  setup(props) {
    return () => {
      const nodeMap = new Map(props.nodes.map(n => [n.id, n]));
      const childIds = new Set(props.nodes.flatMap(n => n.children ?? []));
      const rootNodes = props.nodes.filter(n => !childIds.has(n.id));
      return rootNodes.map(node => renderNode(node, nodeMap, props.actions));
    };
  },
});
