import { describe, it, expect } from 'vitest';
import {
  generateReactStory,
  generateVueStory,
  generateLitStory,
  generateStorybookMain,
  generateStorybookPreview,
  generateStorybookManager,
} from '../src/utils/stories.js';

// All components available via `ag add`
const ALL_COMPONENTS = [
  'Accordion', 'Alert', 'AspectRatio', 'Avatar', 'Badge', 'BadgeFx',
  'Breadcrumb', 'Button', 'ButtonFx', 'Card', 'Checkbox', 'Collapsible',
  'Combobox', 'CopyButton', 'Dialog', 'Divider', 'Drawer', 'EmptyState',
  'Fieldset', 'Flex', 'Header', 'Icon', 'IconButton', 'IconButtonFx',
  'Image', 'Input', 'IntlFormatter', 'Kbd', 'Link', 'Loader', 'Mark',
  'Menu', 'MessageBubble', 'Pagination', 'Popover', 'Progress', 'ProgressRing',
  'Radio', 'Rating', 'ScrollProgress', 'ScrollToButton', 'Select', 'Sidebar',
  'SidebarNav', 'SkeletonLoader', 'Slider', 'Spinner', 'Tabs', 'Tag',
  'Timeline', 'Toast', 'Toggle', 'Tooltip', 'VisuallyHidden',
];

// External packages that must NOT appear in generated story files
const BANNED_EXTERNAL_IMPORTS = ['lucide-react', 'lucide-vue-next', 'heroicons', 'feather-icons'];

// ---------------------------------------------------------------------------
// generateStorybookMain
// ---------------------------------------------------------------------------

describe('generateStorybookMain', () => {
  it('starts with the AUTO-GENERATED header comment', () => {
    const out = generateStorybookMain('react');
    expect(out).toContain('AUTO-GENERATED by agnosticui-cli');
    expect(out).toContain('storybook --force');
  });

  it('generates react-vite framework for react', () => {
    const out = generateStorybookMain('react');
    expect(out).toContain('@storybook/react-vite');
    expect(out).toContain('viteFinal');
    expect(out).toContain('noDiscovery = false');
  });

  it('generates vue3-vite framework for vue', () => {
    const out = generateStorybookMain('vue');
    expect(out).toContain('@storybook/vue3-vite');
  });

  it('generates web-components-vite framework for lit', () => {
    const out = generateStorybookMain('lit');
    expect(out).toContain('@storybook/web-components-vite');
  });
});

describe('generateStorybookManager', () => {
  const out = generateStorybookManager();

  it('starts with the AUTO-GENERATED header comment', () => {
    expect(out).toContain('AUTO-GENERATED by agnosticui-cli');
  });

  it('imports from storybook/manager-api (bundled, no extra dep)', () => {
    expect(out).toContain("from 'storybook/manager-api'");
    expect(out).not.toContain("from '@storybook/manager-api'");
  });

  it('imports from storybook/theming (bundled, no extra dep)', () => {
    expect(out).toContain("from 'storybook/theming/create'");
    expect(out).not.toContain("from '@storybook/theming'");
  });

  it('sets a brandTitle that communicates auto-generated nature', () => {
    expect(out).toContain('brandTitle');
    expect(out).toContain('Auto-generated');
  });

  it('calls addons.setConfig with the theme', () => {
    expect(out).toContain('addons.setConfig');
  });
});

// ---------------------------------------------------------------------------
// generateStorybookPreview
// ---------------------------------------------------------------------------

describe('generateStorybookPreview', () => {
  it('imports ag-tokens.css for react', () => {
    const out = generateStorybookPreview('react', '../src/components/ag');
    expect(out).toContain('ag-tokens.css');
  });

  it('imports ag-tokens.css for vue', () => {
    const out = generateStorybookPreview('vue', '../src/components/ag');
    expect(out).toContain('ag-tokens.css');
  });

  it('imports ag-tokens.css for lit', () => {
    const out = generateStorybookPreview('lit', '../src/components/ag');
    expect(out).toContain('ag-tokens.css');
  });
});

// ---------------------------------------------------------------------------
// generateReactStory - universal invariants
// ---------------------------------------------------------------------------

describe('generateReactStory - universal invariants', () => {
  for (const name of ALL_COMPONENTS) {
    it(`${name}: starts with AUTO-GENERATED header`, () => {
      const out = generateReactStory(name);
      expect(out).toContain('AUTO-GENERATED by agnosticui-cli');
    });

    it(`${name}: has Meta and StoryObj imports from @storybook/react`, () => {
      const out = generateReactStory(name);
      expect(out).toContain("from '@storybook/react'");
    });

    it(`${name}: has a default export (meta)`, () => {
      const out = generateReactStory(name);
      expect(out).toContain('export default');
    });

    it(`${name}: has at least one named story export`, () => {
      const out = generateReactStory(name);
      expect(out).toMatch(/export const \w+/);
    });

    it(`${name}: does not import banned external packages`, () => {
      const out = generateReactStory(name);
      for (const banned of BANNED_EXTERNAL_IMPORTS) {
        expect(out, `${name} story imports "${banned}"`).not.toContain(banned);
      }
    });

    it(`${name}: does not have unfilled template placeholders`, () => {
      const out = generateReactStory(name);
      expect(out).not.toContain('TODO');
      // '{{' can appear in JSX style props — check for template-style {{ }} with spaces
      expect(out).not.toMatch(/\{\{\s+\w+\s+\}\}/);
    });
  }
});

// ---------------------------------------------------------------------------
// generateReactStory - component-specific checks
// ---------------------------------------------------------------------------

describe('generateReactStory - Sidebar', () => {
  const out = generateReactStory('Sidebar');

  it('uses inline SVG icons, not lucide-react', () => {
    expect(out).not.toContain('lucide-react');
    expect(out).toContain('const HomeIcon');
    expect(out).toContain('const FolderIcon');
    expect(out).toContain('const ChevronRightIcon');
  });

  it('has submenu toggle handler', () => {
    expect(out).toContain('handleSubmenuToggle');
    expect(out).toContain('aria-expanded');
  });

  it('uses nav-button-expanded class for desktop submenu buttons', () => {
    expect(out).toContain('nav-button-expanded');
  });

  it('uses nav-button-collapsed class for popover triggers', () => {
    expect(out).toContain('nav-button-collapsed');
  });

  it('uses ag-sidebar-nav-submenu[open] CSS rule', () => {
    expect(out).toContain('ag-sidebar-nav-submenu[open]');
  });

  it('hides collapsed elements via CSS', () => {
    expect(out).toContain('ag-sidebar[collapsed]');
    expect(out).toContain('display: none');
  });
});

describe('generateReactStory - Dialog', () => {
  const out = generateReactStory('Dialog');

  it('imports useState for open state', () => {
    expect(out).toContain('useState');
  });

  it('imports ReactButton for the trigger', () => {
    expect(out).toContain('ReactButton');
  });
});

describe('generateReactStory - Combobox', () => {
  const out = generateReactStory('Combobox');

  it('provides sample FRUITS data array', () => {
    expect(out).toContain('FRUITS');
    expect(out).toContain('ComboboxOption');
  });
});

describe('generateReactStory - Toast', () => {
  const out = generateReactStory('Toast');

  it('imports useState for open state', () => {
    expect(out).toContain('useState');
  });
});

// ---------------------------------------------------------------------------
// generateVueStory - universal invariants
// ---------------------------------------------------------------------------

describe('generateVueStory - universal invariants', () => {
  for (const name of ALL_COMPONENTS) {
    it(`${name}: has Meta and StoryObj imports from @storybook/vue3`, () => {
      const out = generateVueStory(name);
      expect(out).toContain("from '@storybook/vue3'");
    });

    it(`${name}: has a default export (meta)`, () => {
      const out = generateVueStory(name);
      expect(out).toContain('export default');
    });

    it(`${name}: has at least one named story export`, () => {
      const out = generateVueStory(name);
      expect(out).toMatch(/export const \w+/);
    });

    it(`${name}: does not import banned external packages`, () => {
      const out = generateVueStory(name);
      for (const banned of BANNED_EXTERNAL_IMPORTS) {
        expect(out, `${name} story imports "${banned}"`).not.toContain(banned);
      }
    });
  }
});

// ---------------------------------------------------------------------------
// generateVueStory - component-specific checks
// ---------------------------------------------------------------------------

describe('generateVueStory - Sidebar', () => {
  const out = generateVueStory('Sidebar');

  it('has submenu toggle handler', () => {
    expect(out).toContain('handleSubmenuToggle');
  });

  it('uses nav-button-expanded class', () => {
    expect(out).toContain('nav-button-expanded');
  });

  it('uses ag-sidebar-nav-submenu[open] CSS rule', () => {
    expect(out).toContain('ag-sidebar-nav-submenu[open]');
  });
});

describe('generateVueStory - Accordion', () => {
  it('uses VueAccordionContent wrapper component', () => {
    const out = generateVueStory('Accordion');
    expect(out).toContain('VueAccordionContent');
  });

  it('uses VueAccordionItem', () => {
    const out = generateVueStory('Accordion');
    expect(out).toContain('VueAccordionItem');
  });
});

describe('generateVueStory - Menu', () => {
  it('uses VueMenuItem for menu items', () => {
    const out = generateVueStory('Menu');
    expect(out).toContain('VueMenuItem');
  });
});

// ---------------------------------------------------------------------------
// generateLitStory - universal invariants
// ---------------------------------------------------------------------------

describe('generateLitStory - universal invariants', () => {
  for (const name of ALL_COMPONENTS) {
    it(`${name}: has Meta and StoryObj from @storybook/web-components`, () => {
      const out = generateLitStory(name);
      expect(out).toContain("from '@storybook/web-components'");
    });

    it(`${name}: has a default export (meta)`, () => {
      const out = generateLitStory(name);
      expect(out).toContain('export default');
    });

    it(`${name}: has at least one named story export`, () => {
      const out = generateLitStory(name);
      expect(out).toMatch(/export const \w+/);
    });

    it(`${name}: does not import banned external packages`, () => {
      const out = generateLitStory(name);
      for (const banned of BANNED_EXTERNAL_IMPORTS) {
        expect(out, `${name} story imports "${banned}"`).not.toContain(banned);
      }
    });
  }
});

// ---------------------------------------------------------------------------
// generateLitStory - component-specific checks
// ---------------------------------------------------------------------------

describe('generateLitStory - Sidebar', () => {
  const out = generateLitStory('Sidebar');

  it('has submenu toggle handler', () => {
    expect(out).toContain('handleSubmenuToggle');
  });

  it('uses nav-button-expanded class', () => {
    expect(out).toContain('nav-button-expanded');
  });

  it('uses ag-sidebar-nav-submenu[open] CSS rule', () => {
    expect(out).toContain('ag-sidebar-nav-submenu[open]');
  });

  it('uses toggleCollapse() not collapsed property assignment', () => {
    expect(out).toContain('toggleCollapse()');
    expect(out).not.toContain('collapsed = !');
  });
});

describe('generateLitStory - Accordion', () => {
  it('uses slot="content" for accordion panels', () => {
    const out = generateLitStory('Accordion');
    expect(out).toContain('slot="content"');
  });
});

describe('generateLitStory - Menu', () => {
  it('uses slot="menu"', () => {
    const out = generateLitStory('Menu');
    expect(out).toContain('slot="menu"');
  });
});

describe('generateLitStory - Toast', () => {
  it('sets position property via dot-notation assignment', () => {
    const out = generateLitStory('Toast');
    expect(out).toContain('.position');
  });
});

describe('generateLitStory - ScrollProgress', () => {
  it('uses fullscreen layout so the page is scrollable', () => {
    const out = generateLitStory('ScrollProgress');
    expect(out).toContain('fullscreen');
  });

  it('renders LOREM paragraph content for scrolling', () => {
    const out = generateLitStory('ScrollProgress');
    expect(out).toContain('LOREM');
  });
});
