// AUTO-GENERATED by v2/schema/scripts/codegen.ts — do not edit by hand
// Run: npm run codegen   (from v2/schema/)
// Source: v2/lib/src/components/*/core/_*.ts

import { LitElement, html, nothing, type TemplateResult } from 'lit';
import { property } from 'lit/decorators.js';
import type { AgNode } from '@agnosticui/schema';

// Register AgnosticUI core custom elements
import 'agnosticui-core/accordion';
import 'agnosticui-core/alert';
import 'agnosticui-core/aspect-ratio';
import 'agnosticui-core/avatar';
import 'agnosticui-core/badge';
import 'agnosticui-core/badge-fx';
import 'agnosticui-core/breadcrumb';
import 'agnosticui-core/button';
import 'agnosticui-core/button-fx';
import 'agnosticui-core/card';
import 'agnosticui-core/checkbox';
import 'agnosticui-core/dialog';
import 'agnosticui-core/divider';
import 'agnosticui-core/drawer';
import 'agnosticui-core/fieldset';
import 'agnosticui-core/header';
import 'agnosticui-core/icon';
import 'agnosticui-core/icon-button';
import 'agnosticui-core/icon-button-fx';
import 'agnosticui-core/input';
import 'agnosticui-core/intl-formatter';
import 'agnosticui-core/kbd';
import 'agnosticui-core/link';
import 'agnosticui-core/loader';
import 'agnosticui-core/mark';
import 'agnosticui-core/message-bubble';
import 'agnosticui-core/popover';
import 'agnosticui-core/progress';
import 'agnosticui-core/radio';
import 'agnosticui-core/rating';
import 'agnosticui-core/select';
import 'agnosticui-core/selection-button';
import 'agnosticui-core/selection-button-group';
import 'agnosticui-core/selection-card';
import 'agnosticui-core/selection-card-group';
import 'agnosticui-core/spinner';
import 'agnosticui-core/tabs';
import 'agnosticui-core/tag';
import 'agnosticui-core/toggle';
import 'agnosticui-core/tooltip';

type Actions = Record<string, (payload?: unknown) => void>;

/**
 * Create an action dispatcher bound to a given actions map.
 *
 * This is the XSS boundary: only aliases present in the map are called;
 * unknown aliases are silently ignored. No eval(), no dynamic code execution.
 */
export function createDispatcher(actions: Actions) {
  return (alias?: string): void => {
    if (alias) actions[alias]?.();
  };
}

function doDispatch(alias: string | undefined, actions: Actions): void {
  if (alias) actions[alias]?.();
}

function renderNode(
  node: AgNode,
  nodeMap: Map<string, AgNode>,
  actions: Actions,
): TemplateResult | typeof nothing {
  const renderChildren = (childIds?: string[]) =>
    (childIds ?? []).map(id => {
      const child = nodeMap.get(id);
      return child ? renderNode(child, nodeMap, actions) : nothing;
    });

  switch (node.component) {
    case 'AgAccordion':
      return html`<ag-accordion>${renderChildren(node.children)}</ag-accordion>`;

    case 'AgAlert':
      return html`<ag-alert
        .variant=${node.variant ?? ''}
        .bordered=${node.bordered ?? false}
        .rounded=${node.rounded ?? false}
        .borderedLeft=${node.borderedLeft ?? false}
        .dismissible=${node.dismissible ?? false}
        @alert-dismiss=${() => doDispatch(node.on_dismiss, actions)}
      >${renderChildren(node.children)}</ag-alert>`;

    case 'AgAspectRatio':
      return html`<ag-aspect-ratio
        .width=${node.width ?? 0}
        .height=${node.height ?? 0}
        .maxWidth=${node.maxWidth ?? 0}
      ></ag-aspect-ratio>`;

    case 'AgAvatar':
      return html`<ag-avatar
        .text=${node.text ?? ''}
        .imgSrc=${node.imgSrc ?? ''}
        .imgAlt=${node.imgAlt ?? ''}
        .size=${node.size ?? ''}
        .shape=${node.shape ?? ''}
        .variant=${node.variant ?? ''}
        .ariaLabel=${node.ariaLabel ?? ''}
      ></ag-avatar>`;

    case 'AgBadge':
      return html`<ag-badge
        .variant=${node.variant ?? ''}
        .size=${node.size ?? ''}
        .dot=${node.dot ?? false}
        .value=${node.value ?? 0}
        .max=${node.max ?? 0}
        .interactive=${node.interactive ?? false}
        .statusLabel=${node.statusLabel ?? ''}
        .live=${node.live ?? ''}
        .hiddenFromAT=${node.hiddenFromAT ?? false}
      ></ag-badge>`;

    case 'AgBadgeFx':
      return html`<ag-badge-fx
        .variant=${node.variant ?? ''}
        .size=${node.size ?? ''}
        .dot=${node.dot ?? false}
        .value=${node.value ?? 0}
        .max=${node.max ?? 0}
        .interactive=${node.interactive ?? false}
        .statusLabel=${node.statusLabel ?? ''}
        .live=${node.live ?? ''}
        .hiddenFromAT=${node.hiddenFromAT ?? false}
        .fx=${node.fx ?? ''}
        .fxSpeed=${node.fxSpeed ?? ''}
        .fxEase=${node.fxEase ?? ''}
        .fxDisabled=${node.fxDisabled ?? false}
      ></ag-badge-fx>`;

    case 'AgBreadcrumb':
      return html`<ag-breadcrumb
        .type=${node.type ?? ''}
        .primary=${node.primary ?? false}
        .ariaLabel=${node.ariaLabel ?? ''}
        @breadcrumb-click=${() => doDispatch(node.on_click, actions)}
      ></ag-breadcrumb>`;

    case 'AgButton':
      return html`<ag-button
        .variant=${node.variant ?? ''}
        .size=${node.size ?? ''}
        .shape=${node.shape ?? ''}
        .bordered=${node.bordered ?? false}
        .ghost=${node.ghost ?? false}
        .link=${node.link ?? false}
        .grouped=${node.grouped ?? false}
        .fullWidth=${node.fullWidth ?? false}
        .type=${node.type ?? ''}
        .disabled=${node.disabled ?? false}
        .loading=${node.loading ?? false}
        .ariaLabel=${node.ariaLabel ?? ''}
        @click=${() => doDispatch(node.on_click, actions)}
        @toggle=${() => doDispatch(node.on_toggle, actions)}
      >${node.children?.length ? renderChildren(node.children) : (node.label ?? '')}</ag-button>`;

    case 'AgButtonFx':
      return html`<ag-button-fx
        .variant=${node.variant ?? ''}
        .size=${node.size ?? ''}
        .shape=${node.shape ?? ''}
        .bordered=${node.bordered ?? false}
        .ghost=${node.ghost ?? false}
        .link=${node.link ?? false}
        .grouped=${node.grouped ?? false}
        .fullWidth=${node.fullWidth ?? false}
        .type=${node.type ?? ''}
        .disabled=${node.disabled ?? false}
        .loading=${node.loading ?? false}
        .ariaLabel=${node.ariaLabel ?? ''}
        .fx=${node.fx ?? ''}
        .fxSpeed=${node.fxSpeed ?? ''}
        .fxEase=${node.fxEase ?? ''}
        .fxDisabled=${node.fxDisabled ?? false}
        @click=${() => doDispatch(node.on_click, actions)}
        @toggle=${() => doDispatch(node.on_toggle, actions)}
      >${node.children?.length ? renderChildren(node.children) : (node.label ?? '')}</ag-button-fx>`;

    case 'AgCard':
      return html`<ag-card
        .stacked=${node.stacked ?? false}
        .shadow=${node.shadow ?? false}
        .animated=${node.animated ?? false}
        .rounded=${node.rounded ?? ''}
        .variant=${node.variant ?? ''}
        .hasMedia=${node.hasMedia ?? false}
        .mediaPosition=${node.mediaPosition ?? ''}
      >${renderChildren(node.children)}</ag-card>`;

    case 'AgCheckbox':
      return html`<ag-checkbox
        .name=${node.name ?? ''}
        .value=${node.value ?? ''}
        .checked=${node.checked ?? false}
        .disabled=${node.disabled ?? false}
        .size=${node.size ?? ''}
        .labelText=${node.labelText ?? ''}
        .labelPosition=${node.labelPosition ?? ''}
        .required=${node.required ?? false}
        .invalid=${node.invalid ?? false}
        .errorMessage=${node.errorMessage ?? ''}
        .helpText=${node.helpText ?? ''}
        @click=${() => doDispatch(node.on_click, actions)}
        @change=${() => doDispatch(node.on_change, actions)}
      ></ag-checkbox>`;

    case 'AgDialog':
      return html`<ag-dialog
        .open=${node.open ?? false}
        .heading=${node.heading ?? ''}
        .description=${node.description ?? ''}
        .noCloseOnEscape=${node.noCloseOnEscape ?? false}
        .noCloseOnBackdrop=${node.noCloseOnBackdrop ?? false}
        .showCloseButton=${node.showCloseButton ?? false}
        .drawerPosition=${node.drawerPosition ?? ''}
        @dialog-open=${() => doDispatch(node.on_open, actions)}
        @dialog-close=${() => doDispatch(node.on_close, actions)}
        @dialog-cancel=${() => doDispatch(node.on_cancel, actions)}
      >${renderChildren(node.children)}</ag-dialog>`;

    case 'AgDivider':
      return html`<ag-divider
        .vertical=${node.vertical ?? false}
        .justify=${node.justify ?? ''}
        .size=${node.size ?? ''}
        .variant=${node.variant ?? ''}
      ></ag-divider>`;

    case 'AgDrawer':
      return html`<ag-drawer
        .open=${node.open ?? false}
        .heading=${node.heading ?? ''}
        .description=${node.description ?? ''}
        .noCloseOnEscape=${node.noCloseOnEscape ?? false}
        .noCloseOnBackdrop=${node.noCloseOnBackdrop ?? false}
        .showCloseButton=${node.showCloseButton ?? false}
        .position=${node.position ?? ''}
        @drawer-open=${() => doDispatch(node.on_open, actions)}
        @drawer-close=${() => doDispatch(node.on_close, actions)}
        @drawer-cancel=${() => doDispatch(node.on_cancel, actions)}
      >${renderChildren(node.children)}</ag-drawer>`;

    case 'AgFieldset':
      return html`<ag-fieldset
        .legend=${node.legend ?? ''}
        .bordered=${node.bordered ?? false}
        .layout=${node.layout ?? ''}
        .legendHidden=${node.legendHidden ?? false}
      >${renderChildren(node.children)}</ag-fieldset>`;

    case 'AgHeader':
      return html`<ag-header
        .sticky=${node.sticky ?? false}
        .contentJustify=${node.contentJustify ?? ''}
      >${renderChildren(node.children)}</ag-header>`;

    case 'AgIcon':
      return html`<ag-icon
        .size=${node.size ?? ''}
        .type=${node.type ?? ''}
        .noFill=${node.noFill ?? false}
      ></ag-icon>`;

    case 'AgIconButton':
      return html`<ag-icon-button
        .label=${node.label ?? ''}
        .icon=${node.icon ?? ''}
        .unicode=${node.unicode ?? ''}
        .size=${node.size ?? ''}
        .variant=${node.variant ?? ''}
        .type=${node.type ?? ''}
        .disabled=${node.disabled ?? false}
        .loading=${node.loading ?? false}
        @icon-button-click=${() => doDispatch(node.on_click, actions)}
        @icon-button-activate=${() => doDispatch(node.on_activate, actions)}
      ></ag-icon-button>`;

    case 'AgIconButtonFx':
      return html`<ag-icon-button-fx
        .label=${node.label ?? ''}
        .icon=${node.icon ?? ''}
        .unicode=${node.unicode ?? ''}
        .size=${node.size ?? ''}
        .variant=${node.variant ?? ''}
        .type=${node.type ?? ''}
        .disabled=${node.disabled ?? false}
        .loading=${node.loading ?? false}
        .fx=${node.fx ?? ''}
        .fxSpeed=${node.fxSpeed ?? ''}
        .fxEase=${node.fxEase ?? ''}
        .fxDisabled=${node.fxDisabled ?? false}
        @icon-button-click=${() => doDispatch(node.on_click, actions)}
        @icon-button-activate=${() => doDispatch(node.on_activate, actions)}
      ></ag-icon-button-fx>`;

    case 'AgInput':
      return html`<ag-input
        .label=${node.label ?? ''}
        .labelHidden=${node.labelHidden ?? false}
        .labelPosition=${node.labelPosition ?? ''}
        .noLabel=${node.noLabel ?? false}
        .ariaLabel=${node.ariaLabel ?? ''}
        .name=${node.name ?? ''}
        .type=${node.type ?? ''}
        .value=${node.value ?? ''}
        .placeholder=${node.placeholder ?? ''}
        .rows=${node.rows ?? 0}
        .cols=${node.cols ?? 0}
        .size=${node.size ?? ''}
        .capsule=${node.capsule ?? false}
        .rounded=${node.rounded ?? false}
        .underlined=${node.underlined ?? false}
        .underlinedWithBackground=${node.underlinedWithBackground ?? false}
        .inline=${node.inline ?? false}
        .required=${node.required ?? false}
        .disabled=${node.disabled ?? false}
        .readonly=${node.readonly ?? false}
        .invalid=${node.invalid ?? false}
        .errorMessage=${node.errorMessage ?? ''}
        .helpText=${node.helpText ?? ''}
        @click=${() => doDispatch(node.on_click, actions)}
        @change=${() => doDispatch(node.on_change, actions)}
      ></ag-input>`;

    case 'AgIntlFormatter':
      return html`<ag-intl-formatter
        .type=${node.type ?? ''}
        .value=${node.value ?? ''}
        .lang=${node.lang ?? ''}
        .date=${node.date ?? ''}
        .weekday=${node.weekday ?? ''}
        .era=${node.era ?? ''}
        .year=${node.year ?? ''}
        .month=${node.month ?? ''}
        .day=${node.day ?? ''}
        .hour=${node.hour ?? ''}
        .minute=${node.minute ?? ''}
        .second=${node.second ?? ''}
        .timeZoneName=${node.timeZoneName ?? ''}
        .timeZone=${node.timeZone ?? ''}
        .hourFormat=${node.hourFormat ?? ''}
        .dateStyle=${node.dateStyle ?? ''}
        .timeStyle=${node.timeStyle ?? ''}
        .noGrouping=${node.noGrouping ?? false}
        .currency=${node.currency ?? ''}
        .currencyDisplay=${node.currencyDisplay ?? ''}
        .minimumIntegerDigits=${node.minimumIntegerDigits ?? 0}
        .minimumFractionDigits=${node.minimumFractionDigits ?? 0}
        .maximumFractionDigits=${node.maximumFractionDigits ?? 0}
        .minimumSignificantDigits=${node.minimumSignificantDigits ?? 0}
        .maximumSignificantDigits=${node.maximumSignificantDigits ?? 0}
      ></ag-intl-formatter>`;

    case 'AgKbd':
      return html`<ag-kbd
        .variant=${node.variant ?? ''}
        .bordered=${node.bordered ?? false}
        .background=${node.background ?? false}
        .size=${node.size ?? ''}
      >${renderChildren(node.children)}</ag-kbd>`;

    case 'AgLink':
      return html`<ag-link
        .href=${node.href ?? ''}
        .variant=${node.variant ?? ''}
        .isButton=${node.isButton ?? false}
        .buttonSize=${node.buttonSize ?? ''}
        .buttonShape=${node.buttonShape ?? ''}
        .buttonBordered=${node.buttonBordered ?? false}
        .external=${node.external ?? false}
        .disabled=${node.disabled ?? false}
        .ariaLabel=${node.ariaLabel ?? ''}
        @click=${() => doDispatch(node.on_click, actions)}
      >${renderChildren(node.children)}</ag-link>`;

    case 'AgLoader':
      return html`<ag-loader
        .size=${node.size ?? ''}
        .ariaLabel=${node.ariaLabel ?? ''}
      ></ag-loader>`;

    case 'AgMark':
      return html`<ag-mark
        .variant=${node.variant ?? ''}
        .search=${node.search ?? ''}
        .caseSensitive=${node.caseSensitive ?? false}
        .matchAll=${node.matchAll ?? false}
      >${renderChildren(node.children)}</ag-mark>`;

    case 'AgMessageBubble':
      return html`<ag-message-bubble
        .from=${node.from ?? ''}
        .message=${node.message ?? ''}
        .time=${node.time ?? ''}
        .author=${node.author ?? ''}
        .avatarUrl=${node.avatarUrl ?? ''}
        .footer=${node.footer ?? ''}
        .variant=${node.variant ?? ''}
      >${renderChildren(node.children)}</ag-message-bubble>`;

    case 'AgPopover':
      return html`<ag-popover
        .placement=${node.placement ?? ''}
        .distance=${node.distance ?? 0}
        .skidding=${node.skidding ?? 0}
        .arrow=${node.arrow ?? false}
        .disabled=${node.disabled ?? false}
        .triggerType=${node.triggerType ?? ''}
        .matchTriggerWidth=${node.matchTriggerWidth ?? false}
        .showCloseButton=${node.showCloseButton ?? false}
        .showHeader=${node.showHeader ?? false}
        .closeLabel=${node.closeLabel ?? ''}
        .trapFocus=${node.trapFocus ?? false}
        @show=${() => doDispatch(node.on_show, actions)}
        @hide=${() => doDispatch(node.on_hide, actions)}
      >${renderChildren(node.children)}</ag-popover>`;

    case 'AgProgress':
      return html`<ag-progress
        .value=${node.value ?? 0}
        .max=${node.max ?? 0}
        .label=${node.label ?? ''}
        .size=${node.size ?? ''}
      >${renderChildren(node.children)}</ag-progress>`;

    case 'AgRadio':
      return html`<ag-radio
        .name=${node.name ?? ''}
        .value=${node.value ?? ''}
        .checked=${node.checked ?? false}
        .disabled=${node.disabled ?? false}
        .size=${node.size ?? ''}
        .theme=${node.theme ?? ''}
        .labelText=${node.labelText ?? ''}
        .labelPosition=${node.labelPosition ?? ''}
        .label=${node.label ?? ''}
        .labelHidden=${node.labelHidden ?? false}
        .noLabel=${node.noLabel ?? false}
        .required=${node.required ?? false}
        .invalid=${node.invalid ?? false}
        .errorMessage=${node.errorMessage ?? ''}
        .helpText=${node.helpText ?? ''}
        @click=${() => doDispatch(node.on_click, actions)}
        @change=${() => doDispatch(node.on_change, actions)}
      ></ag-radio>`;

    case 'AgRating':
      return html`<ag-rating
        .value=${node.value ?? 0}
        .max=${node.max ?? 0}
        .precision=${node.precision ?? ''}
        .readonly=${node.readonly ?? false}
        .allowClear=${node.allowClear ?? false}
        .variant=${node.variant ?? ''}
        .size=${node.size ?? ''}
        .name=${node.name ?? ''}
        .label=${node.label ?? ''}
        .labelPosition=${node.labelPosition ?? ''}
        .labelHidden=${node.labelHidden ?? false}
        .noLabel=${node.noLabel ?? false}
        .required=${node.required ?? false}
        .invalid=${node.invalid ?? false}
        .errorMessage=${node.errorMessage ?? ''}
        .helpText=${node.helpText ?? ''}
      ></ag-rating>`;

    case 'AgSelect':
      return html`<ag-select
        .size=${node.size ?? ''}
        .multiple=${node.multiple ?? false}
        .disabled=${node.disabled ?? false}
        .name=${node.name ?? ''}
        .multipleSize=${node.multipleSize ?? 0}
        .label=${node.label ?? ''}
        .labelPosition=${node.labelPosition ?? ''}
        .labelHidden=${node.labelHidden ?? false}
        .noLabel=${node.noLabel ?? false}
        .required=${node.required ?? false}
        .invalid=${node.invalid ?? false}
        .errorMessage=${node.errorMessage ?? ''}
        .helpText=${node.helpText ?? ''}
        @click=${() => doDispatch(node.on_click, actions)}
        @change=${() => doDispatch(node.on_change, actions)}
      ></ag-select>`;

    case 'AgSelectionButton':
      return html`<ag-selection-button
        .value=${node.value ?? ''}
        .label=${node.label ?? ''}
        .checked=${node.checked ?? false}
        .disabled=${node.disabled ?? false}
      ></ag-selection-button>`;

    case 'AgSelectionButtonGroup':
      return html`<ag-selection-button-group
        .type=${node.type ?? ''}
        .name=${node.name ?? ''}
        .legend=${node.legend ?? ''}
        .legendHidden=${node.legendHidden ?? false}
        .theme=${node.theme ?? ''}
        .size=${node.size ?? ''}
        .shape=${node.shape ?? ''}
        .value=${node.value ?? ''}
        .values=${node.values ?? ''}
        .disabled=${node.disabled ?? false}
        .required=${node.required ?? false}
      ></ag-selection-button-group>`;

    case 'AgSelectionCard':
      return html`<ag-selection-card
        .value=${node.value ?? ''}
        .label=${node.label ?? ''}
        .checked=${node.checked ?? false}
        .disabled=${node.disabled ?? false}
      ></ag-selection-card>`;

    case 'AgSelectionCardGroup':
      return html`<ag-selection-card-group
        .type=${node.type ?? ''}
        .name=${node.name ?? ''}
        .legend=${node.legend ?? ''}
        .legendHidden=${node.legendHidden ?? false}
        .theme=${node.theme ?? ''}
        .value=${node.value ?? ''}
        .values=${node.values ?? ''}
        .disabled=${node.disabled ?? false}
        .required=${node.required ?? false}
      ></ag-selection-card-group>`;

    case 'AgSpinner':
      return html`<ag-spinner
        .size=${node.size ?? ''}
        .ariaLabel=${node.ariaLabel ?? ''}
      ></ag-spinner>`;

    case 'AgTabs':
      return html`<ag-tabs
        .activation=${node.activation ?? ''}
        .activeTab=${node.activeTab ?? 0}
        .orientation=${node.orientation ?? ''}
        .ariaLabel=${node.ariaLabel ?? ''}
      ></ag-tabs>`;

    case 'AgTag':
      return html`<ag-tag
        .variant=${node.variant ?? ''}
        .shape=${node.shape ?? ''}
        .uppercase=${node.uppercase ?? false}
        .removable=${node.removable ?? false}
        @tag-remove=${() => doDispatch(node.on_remove, actions)}
      >${renderChildren(node.children)}</ag-tag>`;

    case 'AgToggle':
      return html`<ag-toggle
        .label=${node.label ?? ''}
        .labelPosition=${node.labelPosition ?? ''}
        .labelHidden=${node.labelHidden ?? false}
        .noLabel=${node.noLabel ?? false}
        .checked=${node.checked ?? false}
        .size=${node.size ?? ''}
        .variant=${node.variant ?? ''}
        .disabled=${node.disabled ?? false}
        .readonly=${node.readonly ?? false}
        .required=${node.required ?? false}
        .invalid=${node.invalid ?? false}
        .errorMessage=${node.errorMessage ?? ''}
        .helpText=${node.helpText ?? ''}
        .name=${node.name ?? ''}
        .value=${node.value ?? ''}
        @click=${() => doDispatch(node.on_click, actions)}
        @toggle-change=${() => doDispatch(node.on_change, actions)}
      ></ag-toggle>`;

    case 'AgTooltip':
      return html`<ag-tooltip
        .content=${node.content ?? ''}
        .placement=${node.placement ?? ''}
        .distance=${node.distance ?? 0}
        .skidding=${node.skidding ?? 0}
        .trigger=${node.trigger ?? ''}
        .disabled=${node.disabled ?? false}
        @show=${() => doDispatch(node.on_show, actions)}
        @hide=${() => doDispatch(node.on_hide, actions)}
      ></ag-tooltip>`;

    default:
      return nothing;
  }
}

/**
 * AgDynamicRenderer (Lit)
 *
 * A custom element that consumes a flat array of AgNode objects and renders
 * them using the AgnosticUI core web components directly. Renders into light
 * DOM so it works transparently inside any framework.
 *
 * Nodes not referenced as children by any other node are treated as roots.
 * Actions are routed through a whitelist map — unknown aliases are silently
 * ignored, providing an XSS boundary.
 *
 * @example
 * <ag-dynamic-renderer></ag-dynamic-renderer>
 *
 * el.nodes = [{ id: 'btn-1', component: 'AgButton', label: 'Click', on_click: 'SUBMIT' }];
 * el.actions = { SUBMIT: () => console.log('submitted') };
 */
export class AgDynamicRenderer extends LitElement {
  // Render into light DOM so child elements are accessible to parent frameworks
  override createRenderRoot() {
    return this;
  }

  @property({ type: Array }) nodes: AgNode[] = [];
  @property({ type: Object }) actions: Actions = {};

  override render() {
    const nodeMap = new Map(this.nodes.map(n => [n.id, n]));
    const childIds = new Set(this.nodes.flatMap(n => n.children ?? []));
    const rootNodes = this.nodes.filter(n => !childIds.has(n.id));
    return html`${rootNodes.map(node => renderNode(node, nodeMap, this.actions))}`;
  }
}

if (!customElements.get('ag-dynamic-renderer')) {
  customElements.define('ag-dynamic-renderer', AgDynamicRenderer);
}

declare global {
  interface HTMLElementTagNameMap {
    'ag-dynamic-renderer': AgDynamicRenderer;
  }
}
