(function (factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(require, exports);
        if (v !== undefined) module.exports = v;
    }
    else if (typeof define === "function" && define.amd) {
        define(["require", "exports", "tslib", "react/jsx-runtime", "@storybook/addon-actions", "../Button"], factory);
    }
})(function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.Customizations = exports.Types = exports.DisabledAll = exports.Sizes = exports.Default = exports.Secondary = exports.Primary = void 0;
    var tslib_1 = require("tslib");
    var jsx_runtime_1 = require("react/jsx-runtime");
    // eslint-disable-next-line import/no-extraneous-dependencies
    var addon_actions_1 = require("@storybook/addon-actions");
    var Button_1 = require("../Button");
    var actionsData = {
        click: (0, addon_actions_1.action)('click'),
    };
    exports.default = {
        title: 'AG—React/Button',
        component: Button_1.Button,
        on: (0, tslib_1.__assign)({}, actionsData),
    };
    var Primary = function () { return ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ mode: "primary", onClick: (0, addon_actions_1.action)('click') }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ mode: "primary", onClick: (0, addon_actions_1.action)('click'), isBordered: true }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ mode: "primary", onClick: (0, addon_actions_1.action)('click'), isRounded: true }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ mode: "primary", onClick: (0, addon_actions_1.action)('click'), isRounded: true, isBordered: true }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ mode: "primary", onClick: (0, addon_actions_1.action)('click'), isRounded: true, isRaised: true }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ mode: "primary", onClick: (0, addon_actions_1.action)('click'), isCircle: true }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ mode: "primary", onClick: (0, addon_actions_1.action)('click'), isCircle: true, isBordered: true }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ mode: "primary", onClick: (0, addon_actions_1.action)('click'), isBlock: true }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ mode: "primary", onClick: (0, addon_actions_1.action)('click'), isBordered: true, isBlock: true }, { children: "Go" }), void 0)] }, void 0)); };
    exports.Primary = Primary;
    var Secondary = function () { return ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ mode: "secondary", onClick: (0, addon_actions_1.action)('click') }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ mode: "secondary", isBordered: true, onClick: (0, addon_actions_1.action)('click') }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ mode: "secondary", isRounded: true, onClick: (0, addon_actions_1.action)('click') }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ mode: "secondary", isBordered: true, isRounded: true, onClick: (0, addon_actions_1.action)('click') }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ mode: "secondary", isRaised: true, isRounded: true, onClick: (0, addon_actions_1.action)('click') }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ mode: "secondary", isCircle: true, onClick: (0, addon_actions_1.action)('click') }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ mode: "secondary", isCircle: true, isBordered: true, onClick: (0, addon_actions_1.action)('click') }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ mode: "secondary", isBlock: true, onClick: (0, addon_actions_1.action)('click') }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ mode: "secondary", isBordered: true, isBlock: true, onClick: (0, addon_actions_1.action)('click') }, { children: "Go" }), void 0)] }, void 0)); };
    exports.Secondary = Secondary;
    var Default = function () { return ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ onClick: (0, addon_actions_1.action)('click') }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ onClick: (0, addon_actions_1.action)('click'), isBordered: true }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ onClick: (0, addon_actions_1.action)('click'), isRounded: true }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ onClick: (0, addon_actions_1.action)('click'), isBordered: true, isRounded: true }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ onClick: (0, addon_actions_1.action)('click'), isRaised: true, isRounded: true }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ onClick: (0, addon_actions_1.action)('click'), isCircle: true }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ onClick: (0, addon_actions_1.action)('click'), isCircle: true, isBordered: true }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ onClick: (0, addon_actions_1.action)('click'), isBlock: true }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ onClick: (0, addon_actions_1.action)('click'), isBordered: true, isBlock: true }, { children: "Go" }), void 0)] }, void 0)); };
    exports.Default = Default;
    var Sizes = function () { return ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ onClick: (0, addon_actions_1.action)('click'), size: "small" }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ onClick: (0, addon_actions_1.action)('click'), size: "large" }, { children: "Go" }), void 0)] }, void 0)); };
    exports.Sizes = Sizes;
    var DisabledAll = function () { return ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ isDisabled: true }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ onClick: (0, addon_actions_1.action)('click'), mode: "primary", isDisabled: true }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ onClick: (0, addon_actions_1.action)('click'), mode: "secondary", isDisabled: true }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ onClick: (0, addon_actions_1.action)('click'), mode: "secondary", isDisabled: true, isBordered: true }, { children: "Go" }), void 0)] }, void 0)); };
    exports.DisabledAll = DisabledAll;
    var Types = function () { return ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ onClick: (0, addon_actions_1.action)('click'), type: "reset" }, { children: "Go" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ onClick: (0, addon_actions_1.action)('click'), type: "submit" }, { children: "Go" }), void 0)] }, void 0)); };
    exports.Types = Types;
    var Customizations = function () { return ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ onClick: (0, addon_actions_1.action)('click'), css: "my-custom-css-klass" }, { children: "Inspect me to find custom classes" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ onClick: (0, addon_actions_1.action)('click'), isBlank: true }, { children: "Blank button" }), void 0), (0, jsx_runtime_1.jsx)(Button_1.Button, (0, tslib_1.__assign)({ onClick: (0, addon_actions_1.action)('click'), isSkinned: false }, { children: "Unskinned" }), void 0)] }, void 0)); };
    exports.Customizations = Customizations;
});
//# sourceMappingURL=Button.stories.js.map