title: Disclose
notes: |
  AgnosticUI's Disclose component utilizes the <i>details</i> and <i>summary</i> [tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) and, essentially, acts as an Accordion if grouped together as in the provided demo. Unfortunately, these are not offered in IE11 (but AgnosticUI CSS does not support IE11 anyway!).

  The AgnosticUI HTML/CSS only implementation does not enforce Accordion rules that some implementations prefer such as: disabling the collapsing of an opened panel or only permitting one panel to be open at any given time, etc. As such, you can open or collapse any panel and multiple panels can be opened simultaneously.
  
  Accessibility is almost a freebie by using the aformentioned elements, which means code is more maintainable and readable. Specifically, we get the core tabbing and Enter/Space selection functionality; we do not get keyboard navigation via arrows, Home/End (labelled [optional in the wai-aria](https://www.w3.org/TR/wai-aria-practices-1.1/#keyboard-interaction) guidelines). Only a sprinkle of JavaScript would be needed to do so if you're only using the CSS from AgnosticUI (framework implementations will support arrow + navigation). See [wai-aria example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html) for robust coverage of Accordion accessibility.
collated: true
context:
  baseModifier: disclose
variants:
  - name: default
  - name: background
    context:
        variantModifiers: disclose-bg
  - name: single
