// AUTO-GENERATED by v2/schema/scripts/codegen.ts — do not edit by hand
// Run: npm run codegen   (from v2/schema/)
// Source: v2/lib/src/components/*/core/_*.ts

import * as React from 'react';
import type { AgNode } from '@agnosticui/schema';
import { ReactAccordion } from 'agnosticui-core/accordion/react';
import { ReactAlert } from 'agnosticui-core/alert/react';
import { ReactAspectRatio } from 'agnosticui-core/aspect-ratio/react';
import { ReactAvatar } from 'agnosticui-core/avatar/react';
import { ReactAvatarFx } from 'agnosticui-core/avatar-fx/react';
import { ReactBadge } from 'agnosticui-core/badge/react';
import { ReactBadgeFx } from 'agnosticui-core/badge-fx/react';
import { ReactBreadcrumb } from 'agnosticui-core/breadcrumb/react';
import { ReactButton } from 'agnosticui-core/button/react';
import { ReactButtonFx } from 'agnosticui-core/button-fx/react';
import { ReactCard } from 'agnosticui-core/card/react';
import { ReactCheckbox } from 'agnosticui-core/checkbox/react';
import { ReactCombobox } from 'agnosticui-core/combobox/react';
import { ReactCopyButton } from 'agnosticui-core/copy-button/react';
import { ReactDialog } from 'agnosticui-core/dialog/react';
import { ReactDivider } from 'agnosticui-core/divider/react';
import { ReactDrawer } from 'agnosticui-core/drawer/react';
import { ReactEmptyState } from 'agnosticui-core/empty-state/react';
import { ReactFieldset } from 'agnosticui-core/fieldset/react';
import { ReactHeader } from 'agnosticui-core/header/react';
import { ReactIcon } from 'agnosticui-core/icon/react';
import { ReactIconButton } from 'agnosticui-core/icon-button/react';
import { ReactIconButtonFx } from 'agnosticui-core/icon-button-fx/react';
import { ReactImage } from 'agnosticui-core/image/react';
import { ReactInput } from 'agnosticui-core/input/react';
import { ReactIntlFormatter } from 'agnosticui-core/intl-formatter/react';
import { ReactKbd } from 'agnosticui-core/kbd/react';
import { ReactLink } from 'agnosticui-core/link/react';
import { ReactLoader } from 'agnosticui-core/loader/react';
import { ReactMark } from 'agnosticui-core/mark/react';
import { ReactMessageBubble } from 'agnosticui-core/message-bubble/react';
import { ReactPagination } from 'agnosticui-core/pagination/react';
import { ReactPopover } from 'agnosticui-core/popover/react';
import { ReactProgress } from 'agnosticui-core/progress/react';
import { ReactProgressRing } from 'agnosticui-core/progress-ring/react';
import { ReactRadio } from 'agnosticui-core/radio/react';
import { ReactRating } from 'agnosticui-core/rating/react';
import { ReactSelect } from 'agnosticui-core/select/react';
import { ReactSelectionButton } from 'agnosticui-core/selection-button/react';
import { ReactSelectionButtonGroup } from 'agnosticui-core/selection-button-group/react';
import { ReactSelectionCard } from 'agnosticui-core/selection-card/react';
import { ReactSelectionCardGroup } from 'agnosticui-core/selection-card-group/react';
import { ReactSkeletonLoader } from 'agnosticui-core/skeleton-loader/react';
import { ReactSlider } from 'agnosticui-core/slider/react';
import { ReactSpinner } from 'agnosticui-core/spinner/react';
import { ReactTabs } from 'agnosticui-core/tabs/react';
import { ReactTag } from 'agnosticui-core/tag/react';
import { ReactTagFx } from 'agnosticui-core/tag-fx/react';
import { ReactTimeline } from 'agnosticui-core/timeline/react';
import { ReactToggle } from 'agnosticui-core/toggle/react';
import { ReactTooltip } from 'agnosticui-core/tooltip/react';
import { ReactTooltipFx } from 'agnosticui-core/tooltip-fx/react';
import { ReactCollapsible } from 'agnosticui-core/collapsible/react';

type Actions = Record<string, (payload?: unknown) => void>;

export interface AgDynamicRendererProps {
  nodes: AgNode[];
  actions?: Actions;
}

/**
 * Create an action dispatcher bound to a given actions map.
 *
 * This is the XSS boundary: only aliases present in the map are called;
 * unknown aliases are silently ignored. No eval(), no dynamic code execution.
 */
export function createDispatcher(actions: Actions) {
  return (alias?: string, payload?: unknown): void => {
    if (alias) actions[alias]?.(payload);
  };
}

function dispatch(alias: string | undefined, actions: Actions, payload?: unknown): void {
  if (alias) actions[alias]?.(payload);
}

function renderNode(
  node: AgNode,
  nodeMap: Map<string, AgNode>,
  actions: Actions,
): React.ReactNode {
  const renderChildren = (childIds?: string[]): React.ReactNode[] =>
    (childIds ?? [])
      .map(id => {
        const child = nodeMap.get(id);
        return child ? renderNode(child, nodeMap, actions) : null;
      })
      .filter((n): n is React.ReactNode => n !== null);

  switch (node.component) {
    case 'AgAccordion':
      return (
        <ReactAccordion
          key={node.id}
        >
          {renderChildren(node.children)}
        </ReactAccordion>
      );

    case 'AgAlert':
      return (
        <ReactAlert
          key={node.id}
          variant={node.variant}
          bordered={node.bordered}
          rounded={node.rounded}
          borderedLeft={node.borderedLeft}
          dismissible={node.dismissible}
          onAlertDismiss={() => dispatch(node.on_dismiss, actions)}
        >
          {renderChildren(node.children)}
        </ReactAlert>
      );

    case 'AgAspectRatio':
      return (
        <ReactAspectRatio
          key={node.id}
          width={node.width}
          height={node.height}
          maxWidth={node.maxWidth} />
      );

    case 'AgAvatar':
      return (
        <ReactAvatar
          key={node.id}
          text={node.text}
          imgSrc={node.imgSrc}
          imgAlt={node.imgAlt}
          size={node.size}
          shape={node.shape}
          variant={node.variant}
          aria-label={node.ariaLabel} />
      );

    case 'AgAvatarFx':
      return (
        <ReactAvatarFx
          key={node.id}
          text={node.text}
          imgSrc={node.imgSrc}
          imgAlt={node.imgAlt}
          size={node.size}
          shape={node.shape}
          variant={node.variant}
          aria-label={node.ariaLabel}
          fx={node.fx}
          fxSpeed={node.fxSpeed}
          fxEase={node.fxEase}
          fxDisabled={node.fxDisabled} />
      );

    case 'AgBadge':
      return (
        <ReactBadge
          key={node.id}
          variant={node.variant}
          size={node.size}
          dot={node.dot}
          value={node.value}
          max={node.max}
          interactive={node.interactive}
          statusLabel={node.statusLabel}
          live={node.live}
          hiddenFromAT={node.hiddenFromAT}
        >
          {renderChildren(node.children)}
        </ReactBadge>
      );

    case 'AgBadgeFx':
      return (
        <ReactBadgeFx
          key={node.id}
          variant={node.variant}
          size={node.size}
          dot={node.dot}
          value={node.value}
          max={node.max}
          interactive={node.interactive}
          statusLabel={node.statusLabel}
          live={node.live}
          hiddenFromAT={node.hiddenFromAT}
          fx={node.fx}
          fxSpeed={node.fxSpeed}
          fxEase={node.fxEase}
          fxDisabled={node.fxDisabled}
        >
          {renderChildren(node.children)}
        </ReactBadgeFx>
      );

    case 'AgBreadcrumb':
      return (
        <ReactBreadcrumb
          key={node.id}
          type={node.type}
          primary={node.primary}
          aria-label={node.ariaLabel}
          onBreadcrumbClick={() => dispatch(node.on_click, actions)} />
      );

    case 'AgButton':
      return (
        <ReactButton
          key={node.id}
          variant={node.variant}
          size={node.size}
          shape={node.shape}
          bordered={node.bordered}
          ghost={node.ghost}
          link={node.link}
          grouped={node.grouped}
          fullWidth={node.fullWidth}
          type={node.type}
          disabled={node.disabled}
          loading={node.loading}
          aria-label={node.ariaLabel}
          onClick={() => dispatch(node.on_click, actions)}
          onToggle={() => dispatch(node.on_toggle, actions)}
        >
          {node.children?.length ? renderChildren(node.children) : ((node as { label?: string }).label ?? '')}
        </ReactButton>
      );

    case 'AgButtonFx':
      return (
        <ReactButtonFx
          key={node.id}
          variant={node.variant}
          size={node.size}
          shape={node.shape}
          bordered={node.bordered}
          ghost={node.ghost}
          link={node.link}
          grouped={node.grouped}
          fullWidth={node.fullWidth}
          type={node.type}
          disabled={node.disabled}
          loading={node.loading}
          aria-label={node.ariaLabel}
          fx={node.fx}
          fxSpeed={node.fxSpeed}
          fxEase={node.fxEase}
          fxDisabled={node.fxDisabled}
          onClick={() => dispatch(node.on_click, actions)}
          onToggle={() => dispatch(node.on_toggle, actions)}
        >
          {node.children?.length ? renderChildren(node.children) : ((node as { label?: string }).label ?? '')}
        </ReactButtonFx>
      );

    case 'AgCard':
      return (
        <ReactCard
          key={node.id}
          stacked={node.stacked}
          shadow={node.shadow}
          animated={node.animated}
          rounded={node.rounded}
          variant={node.variant}
          hasMedia={node.hasMedia}
          mediaPosition={node.mediaPosition}
        >
          {renderChildren(node.children)}
        </ReactCard>
      );

    case 'AgCheckbox':
      return (
        <ReactCheckbox
          key={node.id}
          name={node.name}
          value={node.value}
          checked={node.checked}
          disabled={node.disabled}
          size={node.size}
          labelText={node.labelText}
          labelPosition={node.labelPosition}
          required={node.required}
          invalid={node.invalid}
          errorMessage={node.errorMessage}
          helpText={node.helpText}
          onClick={() => dispatch(node.on_click, actions)}
          onChange={(e) => dispatch(node.on_change, actions, { id: node.id, value: (e as CustomEvent<{ checked: boolean; value: string }>).detail?.checked })} />
      );

    case 'AgCombobox':
      return (
        <ReactCombobox
          key={node.id}
          {...(node.options !== undefined ? { options: node.options } : {})}
          {...(node.value !== undefined ? { value: node.value } : {})}
          placeholder={node.placeholder}
          label={node.label}
          labelPosition={node.labelPosition}
          labelHidden={node.labelHidden}
          noLabel={node.noLabel}
          aria-label={node.ariaLabel}
          helpText={node.helpText}
          errorMessage={node.errorMessage}
          autocomplete={node.autocomplete}
          filterMode={node.filterMode}
          clearable={node.clearable}
          disabled={node.disabled}
          readonly={node.readonly}
          required={node.required}
          invalid={node.invalid}
          {...(node.size !== undefined ? { size: node.size } : {})}
          closeOnSelect={node.closeOnSelect}
          {...(node.variant !== undefined ? { variant: node.variant } : {})}
          multiple={node.multiple}
          maxOptionsVisible={node.maxOptionsVisible}
          loading={node.loading}
          loadingText={node.loadingText}
          noResultsText={node.noResultsText}
          onChange={(e) => dispatch(node.on_change, actions, { id: node.id, value: (e as CustomEvent<{ value: string | string[] }>).detail?.value ?? '' })} />
      );

    case 'AgCopyButton':
      return (
        <ReactCopyButton
          key={node.id}
          text={node.text}
          label={node.label}
          successLabel={node.successLabel}
          errorLabel={node.errorLabel}
          timeout={node.timeout}
          size={node.size}
          variant={node.variant} />
      );

    case 'AgDialog':
      return (
        <ReactDialog
          key={node.id}
          open={node.open}
          heading={node.heading}
          description={node.description}
          noCloseOnEscape={node.noCloseOnEscape}
          noCloseOnBackdrop={node.noCloseOnBackdrop}
          showCloseButton={node.showCloseButton}
          drawerPosition={node.drawerPosition}
          onDialogOpen={() => dispatch(node.on_open, actions)}
          onDialogClose={() => dispatch(node.on_close, actions)}
          onDialogCancel={() => dispatch(node.on_cancel, actions)}
        >
          {renderChildren(node.children)}
        </ReactDialog>
      );

    case 'AgDivider':
      return (
        <ReactDivider
          key={node.id}
          vertical={node.vertical}
          justify={node.justify}
          size={node.size}
          variant={node.variant} />
      );

    case 'AgDrawer':
      return (
        <ReactDrawer
          key={node.id}
          open={node.open}
          heading={node.heading}
          description={node.description}
          noCloseOnEscape={node.noCloseOnEscape}
          noCloseOnBackdrop={node.noCloseOnBackdrop}
          showCloseButton={node.showCloseButton}
          position={node.position}
          onDrawerOpen={() => dispatch(node.on_open, actions)}
          onDrawerClose={() => dispatch(node.on_close, actions)}
          onDrawerCancel={() => dispatch(node.on_cancel, actions)}
        >
          {renderChildren(node.children)}
        </ReactDrawer>
      );

    case 'AgEmptyState':
      return (
        <ReactEmptyState
          key={node.id}
          title={node.title}
          subtitle={node.subtitle}
          buttonText={node.buttonText}
          size={node.size}
          bordered={node.bordered}
          rounded={node.rounded} />
      );

    case 'AgFieldset':
      return (
        <ReactFieldset
          key={node.id}
          legend={node.legend}
          bordered={node.bordered}
          layout={node.layout}
          legendHidden={node.legendHidden}
        >
          {renderChildren(node.children)}
        </ReactFieldset>
      );

    case 'AgHeader':
      return (
        <ReactHeader
          key={node.id}
          sticky={node.sticky}
          contentJustify={node.contentJustify}
        >
          {renderChildren(node.children)}
        </ReactHeader>
      );

    case 'AgIcon':
      return (
        <ReactIcon
          key={node.id}
          size={node.size}
          type={node.type}
          noFill={node.noFill} />
      );

    case 'AgIconButton':
      return (
        <ReactIconButton
          key={node.id}
          label={node.label}
          icon={node.icon}
          unicode={node.unicode}
          size={node.size}
          variant={node.variant}
          type={node.type}
          disabled={node.disabled}
          loading={node.loading}
          onIconButtonClick={() => dispatch(node.on_click, actions)}
          onIconButtonActivate={() => dispatch(node.on_activate, actions)} />
      );

    case 'AgIconButtonFx':
      return (
        <ReactIconButtonFx
          key={node.id}
          label={node.label}
          icon={node.icon}
          unicode={node.unicode}
          size={node.size}
          variant={node.variant}
          type={node.type}
          disabled={node.disabled}
          loading={node.loading}
          fx={node.fx}
          fxSpeed={node.fxSpeed}
          fxEase={node.fxEase}
          fxDisabled={node.fxDisabled}
          onIconButtonClick={() => dispatch(node.on_click, actions)}
          onIconButtonActivate={() => dispatch(node.on_activate, actions)} />
      );

    case 'AgImage':
      return (
        <ReactImage
          key={node.id}
          src={node.src}
          alt={node.alt}
          width={node.width}
          height={node.height}
          aspectRatio={node.aspectRatio}
          fit={node.fit}
          position={node.position}
          loading={node.loading}
          fade={node.fade}
          duration={node.duration}
          fallbackSrc={node.fallbackSrc} />
      );

    case 'AgInput':
      return (
        <ReactInput
          key={node.id}
          label={node.label}
          labelHidden={node.labelHidden}
          labelPosition={node.labelPosition}
          noLabel={node.noLabel}
          aria-label={node.ariaLabel}
          name={node.name}
          type={node.type}
          {...(node.value !== undefined ? { value: node.value } : {})}
          placeholder={node.placeholder}
          rows={node.rows}
          cols={node.cols}
          {...(node.size !== undefined ? { size: node.size } : {})}
          capsule={node.capsule}
          rounded={node.rounded}
          underlined={node.underlined}
          underlinedWithBackground={node.underlinedWithBackground}
          inline={node.inline}
          min={node.min}
          max={node.max}
          required={node.required}
          disabled={node.disabled}
          readonly={node.readonly}
          invalid={node.invalid}
          errorMessage={node.errorMessage}
          helpText={node.helpText}
          onClick={() => dispatch(node.on_click, actions)}
          onChange={(e) => dispatch(node.on_change, actions, { id: node.id, value: ((e as unknown) as React.ChangeEvent<HTMLInputElement>).target?.value ?? ((e as unknown) as CustomEvent<{ value: string }>).detail?.value ?? '' })} />
      );

    case 'AgIntlFormatter':
      return (
        <ReactIntlFormatter
          key={node.id}
          type={node.type}
          value={node.value}
          lang={node.lang}
          date={node.date}
          weekday={node.weekday}
          era={node.era}
          year={node.year}
          month={node.month}
          day={node.day}
          hour={node.hour}
          minute={node.minute}
          second={node.second}
          timeZoneName={node.timeZoneName}
          timeZone={node.timeZone}
          hourFormat={node.hourFormat}
          dateStyle={node.dateStyle}
          timeStyle={node.timeStyle}
          noGrouping={node.noGrouping}
          currency={node.currency}
          currencyDisplay={node.currencyDisplay}
          minimumIntegerDigits={node.minimumIntegerDigits}
          minimumFractionDigits={node.minimumFractionDigits}
          maximumFractionDigits={node.maximumFractionDigits}
          minimumSignificantDigits={node.minimumSignificantDigits}
          maximumSignificantDigits={node.maximumSignificantDigits} />
      );

    case 'AgKbd':
      return (
        <ReactKbd
          key={node.id}
          variant={node.variant}
          bordered={node.bordered}
          background={node.background}
          size={node.size}
        >
          {renderChildren(node.children)}
        </ReactKbd>
      );

    case 'AgLink':
      return (
        <ReactLink
          key={node.id}
          href={node.href}
          variant={node.variant}
          isButton={node.isButton}
          buttonSize={node.buttonSize}
          buttonShape={node.buttonShape}
          buttonBordered={node.buttonBordered}
          external={node.external}
          disabled={node.disabled}
          aria-label={node.ariaLabel}
          onClick={() => dispatch(node.on_click, actions)}
        >
          {renderChildren(node.children)}
        </ReactLink>
      );

    case 'AgLoader':
      return (
        <ReactLoader
          key={node.id}
          size={node.size}
          aria-label={node.ariaLabel} />
      );

    case 'AgMark':
      return (
        <ReactMark
          key={node.id}
          variant={node.variant}
          search={node.search}
          caseSensitive={node.caseSensitive}
          matchAll={node.matchAll}
        >
          {renderChildren(node.children)}
        </ReactMark>
      );

    case 'AgMessageBubble':
      return (
        <ReactMessageBubble
          key={node.id}
          from={node.from}
          message={node.message}
          time={node.time}
          author={node.author}
          avatarUrl={node.avatarUrl}
          footer={node.footer}
          variant={node.variant}
        >
          {renderChildren(node.children)}
        </ReactMessageBubble>
      );

    case 'AgPagination':
      return (
        <ReactPagination
          key={node.id}
          current={node.current}
          totalPages={node.totalPages}
          justify={node.justify}
          aria-label={node.ariaLabel}
          bordered={node.bordered}
          firstLastNavigation={node.firstLastNavigation}
          onPageChange={(e) => dispatch(node.on_change, actions, { id: node.id, value: (e as CustomEvent<{ page: number }>).detail?.page })} />
      );

    case 'AgPopover':
      return (
        <ReactPopover
          key={node.id}
          placement={node.placement}
          distance={node.distance}
          skidding={node.skidding}
          arrow={node.arrow}
          disabled={node.disabled}
          triggerType={node.triggerType}
          matchTriggerWidth={node.matchTriggerWidth}
          showCloseButton={node.showCloseButton}
          showHeader={node.showHeader}
          closeLabel={node.closeLabel}
          trapFocus={node.trapFocus}
          onShow={() => dispatch(node.on_show, actions)}
          onHide={() => dispatch(node.on_hide, actions)}
        >
          {renderChildren(node.children)}
        </ReactPopover>
      );

    case 'AgProgress':
      return (
        <ReactProgress
          key={node.id}
          value={node.value}
          max={node.max}
          label={node.label}
          size={node.size}
        >
          {renderChildren(node.children)}
        </ReactProgress>
      );

    case 'AgProgressRing':
      return (
        <ReactProgressRing
          key={node.id}
          value={node.value}
          size={node.size}
          variant={node.variant}
          label={node.label} />
      );

    case 'AgRadio':
      return (
        <ReactRadio
          key={node.id}
          name={node.name}
          value={node.value}
          checked={node.checked}
          disabled={node.disabled}
          size={node.size}
          theme={node.theme}
          labelText={node.labelText}
          labelPosition={node.labelPosition}
          label={node.label}
          labelHidden={node.labelHidden}
          noLabel={node.noLabel}
          required={node.required}
          invalid={node.invalid}
          errorMessage={node.errorMessage}
          helpText={node.helpText}
          onClick={() => dispatch(node.on_click, actions)}
          onChange={(e) => dispatch(node.on_change, actions, { id: node.id, value: (e as CustomEvent<{ value: string }>).detail?.value ?? '' })} />
      );

    case 'AgRating':
      return (
        <ReactRating
          key={node.id}
          value={node.value}
          max={node.max}
          precision={node.precision}
          readonly={node.readonly}
          allowClear={node.allowClear}
          variant={node.variant}
          size={node.size}
          name={node.name}
          label={node.label}
          labelPosition={node.labelPosition}
          labelHidden={node.labelHidden}
          noLabel={node.noLabel}
          required={node.required}
          invalid={node.invalid}
          errorMessage={node.errorMessage}
          helpText={node.helpText} />
      );

    case 'AgSelect':
      return (
        <ReactSelect
          key={node.id}
          size={node.size}
          multiple={node.multiple}
          disabled={node.disabled}
          name={node.name}
          multipleSize={node.multipleSize}
          label={node.label}
          labelPosition={node.labelPosition}
          labelHidden={node.labelHidden}
          noLabel={node.noLabel}
          required={node.required}
          invalid={node.invalid}
          errorMessage={node.errorMessage}
          helpText={node.helpText}
          onClick={() => dispatch(node.on_click, actions)}
          onChange={(e) => dispatch(node.on_change, actions, { id: node.id, value: ((e as unknown) as { value?: string | string[] })?.value ?? '' })} />
      );

    case 'AgSelectionButton':
      return (
        <ReactSelectionButton
          key={node.id}
          value={node.value}
          label={node.label}
          checked={node.checked}
          disabled={node.disabled}
        >
          {renderChildren(node.children)}
        </ReactSelectionButton>
      );

    case 'AgSelectionButtonGroup':
      return (
        <ReactSelectionButtonGroup
          key={node.id}
          type={node.type}
          name={node.name}
          legend={node.legend}
          legendHidden={node.legendHidden}
          theme={node.theme}
          size={node.size}
          shape={node.shape}
          value={node.value}
          values={node.values}
          disabled={node.disabled}
          required={node.required}
          onSelectionChange={(e) => dispatch(node.on_change, actions, { id: node.id, value: (e as CustomEvent<{ value: string }>).detail?.value })}
        >
          {renderChildren(node.children)}
        </ReactSelectionButtonGroup>
      );

    case 'AgSelectionCard':
      return (
        <ReactSelectionCard
          key={node.id}
          value={node.value}
          label={node.label}
          checked={node.checked}
          disabled={node.disabled}
        >
          {renderChildren(node.children)}
        </ReactSelectionCard>
      );

    case 'AgSelectionCardGroup':
      return (
        <ReactSelectionCardGroup
          key={node.id}
          type={node.type}
          name={node.name}
          legend={node.legend}
          legendHidden={node.legendHidden}
          theme={node.theme}
          value={node.value}
          values={node.values}
          disabled={node.disabled}
          required={node.required}
          onSelectionChange={(e) => dispatch(node.on_change, actions, { id: node.id, value: (e as CustomEvent<{ value: string }>).detail?.value })}
        >
          {renderChildren(node.children)}
        </ReactSelectionCardGroup>
      );

    case 'AgSkeletonLoader':
      return (
        <ReactSkeletonLoader
          key={node.id}
          variant={node.variant}
          effect={node.effect}
          intensity={node.intensity}
          width={node.width}
          height={node.height} />
      );

    case 'AgSlider':
      return (
        <ReactSlider
          key={node.id}
          label={node.label}
          labelPosition={node.labelPosition}
          labelHidden={node.labelHidden}
          noLabel={node.noLabel}
          aria-label={node.ariaLabel}
          min={node.min}
          max={node.max}
          step={node.step}
          dual={node.dual}
          vertical={node.vertical}
          size={node.size}
          filled={node.filled}
          monochrome={node.monochrome}
          disabled={node.disabled}
          readonly={node.readonly}
          required={node.required}
          invalid={node.invalid}
          errorMessage={node.errorMessage}
          helpText={node.helpText}
          name={node.name}
          showTooltip={node.showTooltip}
          showTicks={node.showTicks}
          tickStep={node.tickStep}
          onChange={(e) => dispatch(node.on_change, actions, { id: node.id, value: (e as CustomEvent<{ value: number | [number, number] }>).detail?.value })} />
      );

    case 'AgSpinner':
      return (
        <ReactSpinner
          key={node.id}
          size={node.size}
          aria-label={node.ariaLabel} />
      );

    case 'AgTabs':
      return (
        <ReactTabs
          key={node.id}
          activation={node.activation}
          activeTab={node.activeTab}
          orientation={node.orientation}
          aria-label={node.ariaLabel}
        >
          {renderChildren(node.children)}
        </ReactTabs>
      );

    case 'AgTag':
      return (
        <ReactTag
          key={node.id}
          variant={node.variant}
          shape={node.shape}
          uppercase={node.uppercase}
          removable={node.removable}
          onTagRemove={() => dispatch(node.on_remove, actions)}
        >
          {renderChildren(node.children)}
        </ReactTag>
      );

    case 'AgTagFx':
      return (
        <ReactTagFx
          key={node.id}
          variant={node.variant}
          shape={node.shape}
          uppercase={node.uppercase}
          removable={node.removable}
          fx={node.fx}
          fxSpeed={node.fxSpeed}
          fxEase={node.fxEase}
          fxDisabled={node.fxDisabled}
          onTagRemove={() => dispatch(node.on_remove, actions)} />
      );

    case 'AgTimeline':
      return (
        <ReactTimeline
          key={node.id}
          orientation={node.orientation}
          variant={node.variant}
          compact={node.compact}
          aria-label={node.ariaLabel} />
      );

    case 'AgToggle':
      return (
        <ReactToggle
          key={node.id}
          label={node.label}
          labelPosition={node.labelPosition}
          labelHidden={node.labelHidden}
          noLabel={node.noLabel}
          checked={node.checked}
          {...(node.size !== undefined ? { size: node.size } : {})}
          {...(node.variant !== undefined ? { variant: node.variant } : {})}
          disabled={node.disabled}
          readonly={node.readonly}
          required={node.required}
          invalid={node.invalid}
          errorMessage={node.errorMessage}
          helpText={node.helpText}
          name={node.name}
          value={node.value}
          onClick={() => dispatch(node.on_click, actions)}
          onToggleChange={(e) => dispatch(node.on_change, actions, { id: node.id, value: (e as CustomEvent<{ checked: boolean; value: string }>).detail?.checked })} />
      );

    case 'AgTooltip':
      return (
        <ReactTooltip
          key={node.id}
          content={node.content}
          placement={node.placement}
          distance={node.distance}
          skidding={node.skidding}
          trigger={node.trigger}
          disabled={node.disabled}
          onShow={() => dispatch(node.on_show, actions)}
          onHide={() => dispatch(node.on_hide, actions)} />
      );

    case 'AgTooltipFx':
      return (
        <ReactTooltipFx
          key={node.id}
          content={node.content}
          placement={node.placement}
          distance={node.distance}
          skidding={node.skidding}
          trigger={node.trigger}
          disabled={node.disabled}
          fx={node.fx}
          fxSpeed={node.fxSpeed}
          fxEase={node.fxEase}
          fxDisabled={node.fxDisabled}
          onShow={() => dispatch(node.on_show, actions)}
          onHide={() => dispatch(node.on_hide, actions)} />
      );

    case 'AgText': {
      const Tag = node.el ?? 'span';
      return <Tag key={node.id}>{node.text}</Tag>;
    }

    case 'AgCollapsible':
      return (
        <ReactCollapsible
          key={node.id}
          open={node.open}
          bordered={node.bordered}
          shadow={node.shadow}
          useChevron={node.useChevron}
          useX={node.useX}
          useMinus={node.useMinus}
          noIndicator={node.noIndicator}
          onToggle={(e) => dispatch(node.on_toggle, actions, { id: node.id, value: e.detail?.open })}
        >
          {node.summary && <span slot="summary">{node.summary}</span>}
          {renderChildren(node.children)}
        </ReactCollapsible>
      );

    default:
      return null;
  }
}

/**
 * AgDynamicRenderer (React)
 *
 * Consumes a flat array of AgNode objects and renders them using the
 * AgnosticUI React wrapper components. Nodes not referenced as children
 * by any other node are treated as roots.
 *
 * Actions are routed through a whitelist map — unknown aliases are
 * silently ignored, providing an XSS boundary.
 */
export function AgDynamicRenderer({ nodes, actions = {} }: AgDynamicRendererProps): React.ReactElement {
  const nodeMap = new Map(nodes.map(n => [n.id, n]));
  const childIds = new Set(nodes.flatMap(n => n.children ?? []));
  const rootNodes = nodes.filter(n => !childIds.has(n.id));

  return (
    <>
      {rootNodes.map(node => renderNode(node, nodeMap, actions))}
    </>
  );
}
