/**
 * Configuration for playbook StackBlitz integration.
 *
 * Each playbook defines the files needed for each framework example.
 * Binary files (like images) are handled via URL replacement - they're
 * referenced from raw.githubusercontent.com instead of being fetched.
 */

// Base URL for raw GitHub content
export const GITHUB_RAW_BASE = 'https://raw.githubusercontent.com/AgnosticUI/agnosticui/master/v2/playbooks'

// Shared component files used across frameworks (core implementations)
// Note: We only include components that are actually used in the login playbook
const SHARED_CORE_FILES = [
  'src/components/ag/Button/core/Button.ts',
  'src/components/ag/Button/core/_Button.ts',
  'src/components/ag/Card/core/Card.ts',
  'src/components/ag/Card/core/_Card.ts',
  'src/components/ag/Checkbox/core/Checkbox.ts',
  'src/components/ag/Checkbox/core/_Checkbox.ts',
  'src/components/ag/Divider/core/Divider.ts',
  'src/components/ag/Divider/core/_Divider.ts',
  'src/components/ag/Divider/core/index.ts',
  'src/components/ag/Image/core/Image.ts',
  'src/components/ag/Image/core/_Image.ts',
  'src/components/ag/Input/core/Input.ts',
  'src/components/ag/Input/core/_Input.ts',
  'src/components/ag/Input/core/_Input.BACKUP.ts',
  'src/components/ag/Link/core/Link.ts',
  'src/components/ag/Link/core/_Link.ts',
  'src/components/ag/shared/form-control-styles.ts',
  'src/components/ag/shared/form-control-utils.ts',
  'src/components/ag/styles/ag-tokens.css',
  'src/components/ag/styles/ag-tokens-dark.css',
  'src/components/ag/styles/skins-bundle.css',
  'src/components/ag/styles/skin-switcher.css',
  'src/components/ag/styles/motion.styles.ts',
  'src/components/ag/styles/nav-button-styles.ts',
  'src/components/ag/styles/nav-sublink-styles.ts',
  'src/components/ag/styles/table.css',
  'src/components/ag/types/fx.ts',
  'src/components/ag/types/vue.d.ts',
  'src/components/ag/utils/handleBackdropClick.ts',
  'src/components/ag/utils/isElementInContainer.ts',
  'src/components/ag/utils/positioning.ts',
  'src/components/ag/utils/slot.ts',
  'src/components/ag/utils/unique-id.ts',
]

// React wrapper files
const REACT_WRAPPER_FILES = [
  'src/components/ag/Button/react/ReactButton.tsx',
  'src/components/ag/Button/react/index.ts',
  'src/components/ag/Card/react/ReactCard.tsx',
  'src/components/ag/Card/react/index.ts',
  'src/components/ag/Checkbox/react/ReactCheckbox.tsx',
  'src/components/ag/Checkbox/react/index.ts',
  'src/components/ag/Divider/react/ReactDivider.tsx',
  'src/components/ag/Divider/react/index.ts',
  'src/components/ag/Image/react/ReactImage.tsx',
  'src/components/ag/Image/react/index.ts',
  'src/components/ag/Input/react/ReactInput.tsx',
  'src/components/ag/Input/react/index.ts',
  'src/components/ag/Link/react/ReactLink.tsx',
  'src/components/ag/Link/react/index.ts',
]

// Vue wrapper files
const VUE_WRAPPER_FILES = [
  'src/components/ag/Button/vue/VueButton.vue',
  'src/components/ag/Button/vue/index.ts',
  'src/components/ag/Card/vue/VueCard.vue',
  'src/components/ag/Card/vue/index.ts',
  'src/components/ag/Checkbox/vue/VueCheckbox.vue',
  'src/components/ag/Checkbox/vue/index.ts',
  'src/components/ag/Divider/vue/VueDivider.vue',
  'src/components/ag/Divider/vue/index.ts',
  'src/components/ag/Image/vue/VueImage.vue',
  'src/components/ag/Image/vue/index.ts',
  'src/components/ag/Input/vue/VueInput.vue',
  'src/components/ag/Input/vue/index.ts',
  'src/components/ag/Link/vue/VueLink.vue',
  'src/components/ag/Link/vue/index.ts',
]

export interface PlaybookConfig {
  /** Display title for the playbook */
  title: string
  /** Files for each framework, relative to the example folder */
  frameworks: {
    react?: string[]
    vue?: string[]
    lit?: string[]
  }
  /** Binary files that need URL replacement (local path -> raw GitHub URL) */
  binaryFiles?: Record<string, string>
  /** Files outside the example directory (StackBlitz dest path -> raw GitHub URL) */
  externalFiles?: Record<string, string>
  /** String replacements applied to all file contents (e.g. import path rewrites) */
  contentReplacements?: Record<string, string>
}

// Shared component files used by the onboarding playbook
const ONBOARDING_SHARED_CORE_FILES = [
  'src/components/ag/Alert/core/Alert.ts',
  'src/components/ag/Alert/core/_Alert.ts',
  'src/components/ag/Button/core/Button.ts',
  'src/components/ag/Button/core/_Button.ts',
  'src/components/ag/Icon/core/Icon.ts',
  'src/components/ag/Icon/core/_Icon.ts',
  'src/components/ag/SelectionButton/core/SelectionButton.ts',
  'src/components/ag/SelectionButton/core/_SelectionButton.ts',
  'src/components/ag/SelectionButtonGroup/core/SelectionButtonGroup.ts',
  'src/components/ag/SelectionButtonGroup/core/_SelectionButtonGroup.ts',
  'src/components/ag/SelectionCard/core/SelectionCard.ts',
  'src/components/ag/SelectionCard/core/_SelectionCard.ts',
  'src/components/ag/SelectionCardGroup/core/SelectionCardGroup.ts',
  'src/components/ag/SelectionCardGroup/core/_SelectionCardGroup.ts',
  'src/components/ag/Timeline/core/Timeline.ts',
  'src/components/ag/Timeline/core/_Timeline.ts',
  'src/components/ag/shared/CloseButton/CloseButton.ts',
  'src/components/ag/shared/CloseButton/_CloseButton.ts',
  'src/components/ag/shared/form-control-styles.ts',
  'src/components/ag/shared/form-control-utils.ts',
  'src/components/ag/styles/ag-tokens.css',
  'src/components/ag/styles/ag-tokens-dark.css',
  'src/components/ag/styles/skins-bundle.css',
  'src/components/ag/styles/skin-switcher.css',
  'src/components/ag/styles/motion.styles.ts',
  'src/components/ag/styles/nav-button-styles.ts',
  'src/components/ag/styles/nav-sublink-styles.ts',
  'src/components/ag/styles/table.css',
  'src/components/ag/types/fx.ts',
  'src/components/ag/types/vue.d.ts',
  'src/components/ag/utils/handleBackdropClick.ts',
  'src/components/ag/utils/isElementInContainer.ts',
  'src/components/ag/utils/positioning.ts',
  'src/components/ag/utils/slot.ts',
  'src/components/ag/utils/unique-id.ts',
]

// React wrapper files for onboarding
const ONBOARDING_REACT_WRAPPER_FILES = [
  'src/components/ag/Alert/react/ReactAlert.tsx',
  'src/components/ag/Alert/react/index.ts',
  'src/components/ag/Button/react/ReactButton.tsx',
  'src/components/ag/Button/react/index.ts',
  'src/components/ag/Icon/react/ReactIcon.tsx',
  'src/components/ag/Icon/react/index.ts',
  'src/components/ag/SelectionButton/react/ReactSelectionButton.tsx',
  'src/components/ag/SelectionButton/react/index.ts',
  'src/components/ag/SelectionButtonGroup/react/ReactSelectionButtonGroup.tsx',
  'src/components/ag/SelectionButtonGroup/react/index.ts',
  'src/components/ag/SelectionCard/react/ReactSelectionCard.tsx',
  'src/components/ag/SelectionCard/react/index.ts',
  'src/components/ag/SelectionCardGroup/react/ReactSelectionCardGroup.tsx',
  'src/components/ag/SelectionCardGroup/react/index.ts',
  'src/components/ag/Timeline/react/ReactTimeline.tsx',
  'src/components/ag/Timeline/react/index.ts',
]

// Vue wrapper files for onboarding
const ONBOARDING_VUE_WRAPPER_FILES = [
  'src/components/ag/Alert/vue/VueAlert.vue',
  'src/components/ag/Alert/vue/index.ts',
  'src/components/ag/Button/vue/VueButton.vue',
  'src/components/ag/Button/vue/index.ts',
  'src/components/ag/Icon/vue/VueIcon.vue',
  'src/components/ag/Icon/vue/index.ts',
  'src/components/ag/SelectionButton/vue/VueSelectionButton.vue',
  'src/components/ag/SelectionButton/vue/index.ts',
  'src/components/ag/SelectionButtonGroup/vue/VueSelectionButtonGroup.vue',
  'src/components/ag/SelectionButtonGroup/vue/index.ts',
  'src/components/ag/SelectionCard/vue/VueSelectionCard.vue',
  'src/components/ag/SelectionCard/vue/index.ts',
  'src/components/ag/SelectionCardGroup/vue/VueSelectionCardGroup.vue',
  'src/components/ag/SelectionCardGroup/vue/index.ts',
  'src/components/ag/Timeline/vue/Timeline.vue',
  'src/components/ag/Timeline/vue/TimelineItem.vue',
  'src/components/ag/Timeline/vue/index.ts',
]

// Shared component files used by the dashboard playbook
const DASHBOARD_SHARED_CORE_FILES = [
  'src/components/ag/Accordion/core/Accordion.ts',
  'src/components/ag/Accordion/core/_Accordion.ts',
  'src/components/ag/Accordion/core/AccordionGroup.ts',
  'src/components/ag/Alert/core/Alert.ts',
  'src/components/ag/Alert/core/_Alert.ts',
  'src/components/ag/Avatar/core/Avatar.ts',
  'src/components/ag/Avatar/core/_Avatar.ts',
  'src/components/ag/Avatar/core/AvatarGroup.ts',
  'src/components/ag/Badge/core/Badge.ts',
  'src/components/ag/Badge/core/_Badge.ts',
  'src/components/ag/Breadcrumb/core/Breadcrumb.ts',
  'src/components/ag/Breadcrumb/core/_Breadcrumb.ts',
  'src/components/ag/Button/core/Button.ts',
  'src/components/ag/Button/core/_Button.ts',
  'src/components/ag/Card/core/Card.ts',
  'src/components/ag/Card/core/_Card.ts',
  'src/components/ag/Divider/core/Divider.ts',
  'src/components/ag/Divider/core/_Divider.ts',
  'src/components/ag/Divider/core/index.ts',
  'src/components/ag/EmptyState/core/EmptyState.ts',
  'src/components/ag/EmptyState/core/_EmptyState.ts',
  'src/components/ag/Flex/core/FlexContainer.ts',
  'src/components/ag/Flex/core/_FlexContainer.ts',
  'src/components/ag/Flex/core/FlexCol.ts',
  'src/components/ag/Flex/core/FlexInline.ts',
  'src/components/ag/Flex/core/FlexRow.ts',
  'src/components/ag/Flex/core/index.ts',
  'src/components/ag/Header/core/Header.ts',
  'src/components/ag/Header/core/_Header.ts',
  'src/components/ag/IconButton/core/IconButton.ts',
  'src/components/ag/IconButton/core/_IconButton.ts',
  'src/components/ag/Progress/core/Progress.ts',
  'src/components/ag/Progress/core/_Progress.ts',
  'src/components/ag/Sidebar/core/Sidebar.ts',
  'src/components/ag/Sidebar/core/_Sidebar.ts',
  'src/components/ag/SkeletonLoader/core/SkeletonLoader.ts',
  'src/components/ag/SkeletonLoader/core/_SkeletonLoader.ts',
  'src/components/ag/Tabs/core/Tabs.ts',
  'src/components/ag/Tabs/core/_Tabs.ts',
  'src/components/ag/Tag/core/Tag.ts',
  'src/components/ag/Tag/core/_Tag.ts',
  'src/components/ag/Toast/core/Toast.ts',
  'src/components/ag/Toast/core/_Toast.ts',
  'src/components/ag/shared/CloseButton/CloseButton.ts',
  'src/components/ag/shared/CloseButton/_CloseButton.ts',
  'src/components/ag/shared/form-control-styles.ts',
  'src/components/ag/shared/form-control-utils.ts',
  'src/components/ag/styles/ag-tokens.css',
  'src/components/ag/styles/ag-tokens-dark.css',
  'src/components/ag/styles/skins-bundle.css',
  'src/components/ag/styles/skin-switcher.css',
  'src/components/ag/styles/motion.styles.ts',
  'src/components/ag/styles/nav-button-styles.ts',
  'src/components/ag/styles/nav-sublink-styles.ts',
  'src/components/ag/styles/table.css',
  'src/components/ag/types/fx.ts',
  'src/components/ag/types/vue.d.ts',
  'src/components/ag/utils/handleBackdropClick.ts',
  'src/components/ag/utils/isElementInContainer.ts',
  'src/components/ag/utils/positioning.ts',
  'src/components/ag/utils/slot.ts',
  'src/components/ag/utils/unique-id.ts',
]

// React wrapper files for dashboard
const DASHBOARD_REACT_WRAPPER_FILES = [
  'src/components/ag/Accordion/react/ReactAccordion.tsx',
  'src/components/ag/Accordion/react/index.ts',
  'src/components/ag/Alert/react/ReactAlert.tsx',
  'src/components/ag/Alert/react/index.ts',
  'src/components/ag/Avatar/react/ReactAvatar.tsx',
  'src/components/ag/Avatar/react/index.ts',
  'src/components/ag/Badge/react/ReactBadge.tsx',
  'src/components/ag/Badge/react/index.ts',
  'src/components/ag/Breadcrumb/react/ReactBreadcrumb.tsx',
  'src/components/ag/Breadcrumb/react/index.ts',
  'src/components/ag/Button/react/ReactButton.tsx',
  'src/components/ag/Button/react/index.ts',
  'src/components/ag/Card/react/ReactCard.tsx',
  'src/components/ag/Card/react/index.ts',
  'src/components/ag/Divider/react/ReactDivider.tsx',
  'src/components/ag/Divider/react/index.ts',
  'src/components/ag/EmptyState/react/ReactEmptyState.tsx',
  'src/components/ag/EmptyState/react/index.ts',
  'src/components/ag/Flex/react/ReactFlexCol.tsx',
  'src/components/ag/Flex/react/ReactFlexContainer.tsx',
  'src/components/ag/Flex/react/ReactFlexInline.tsx',
  'src/components/ag/Flex/react/ReactFlexRow.tsx',
  'src/components/ag/Flex/react/ReactGroup.tsx',
  'src/components/ag/Flex/react/ReactStack.tsx',
  'src/components/ag/Flex/react/index.ts',
  'src/components/ag/Header/react/ReactHeader.tsx',
  'src/components/ag/Header/react/index.ts',
  'src/components/ag/IconButton/react/ReactIconButton.tsx',
  'src/components/ag/IconButton/react/index.ts',
  'src/components/ag/Progress/react/ReactProgress.tsx',
  'src/components/ag/Progress/react/index.ts',
  'src/components/ag/Sidebar/react/ReactSidebar.ts',
  'src/components/ag/SkeletonLoader/react/ReactSkeletonLoader.tsx',
  'src/components/ag/SkeletonLoader/react/index.ts',
  'src/components/ag/Tabs/react/ReactTabs.tsx',
  'src/components/ag/Tabs/react/index.ts',
  'src/components/ag/Tag/react/ReactTag.tsx',
  'src/components/ag/Tag/react/index.ts',
  'src/components/ag/Toast/react/ReactToast.tsx',
  'src/components/ag/Toast/react/index.ts',
]

// Vue wrapper files for dashboard
const DASHBOARD_VUE_WRAPPER_FILES = [
  'src/components/ag/Accordion/vue/VueAccordion.vue',
  'src/components/ag/Accordion/vue/VueAccordionContent.vue',
  'src/components/ag/Accordion/vue/VueAccordionHeader.vue',
  'src/components/ag/Accordion/vue/VueAccordionItem.vue',
  'src/components/ag/Accordion/vue/index.ts',
  'src/components/ag/Alert/vue/VueAlert.vue',
  'src/components/ag/Alert/vue/index.ts',
  'src/components/ag/Avatar/vue/VueAvatar.vue',
  'src/components/ag/Avatar/vue/VueAvatarGroup.vue',
  'src/components/ag/Avatar/vue/index.ts',
  'src/components/ag/Badge/vue/VueBadge.vue',
  'src/components/ag/Badge/vue/index.ts',
  'src/components/ag/Breadcrumb/vue/VueBreadcrumb.vue',
  'src/components/ag/Breadcrumb/vue/index.ts',
  'src/components/ag/Button/vue/VueButton.vue',
  'src/components/ag/Button/vue/index.ts',
  'src/components/ag/Card/vue/VueCard.vue',
  'src/components/ag/Card/vue/index.ts',
  'src/components/ag/Divider/vue/VueDivider.vue',
  'src/components/ag/Divider/vue/index.ts',
  'src/components/ag/EmptyState/vue/VueEmptyState.vue',
  'src/components/ag/EmptyState/vue/index.ts',
  'src/components/ag/Flex/vue/VueFlexCol.vue',
  'src/components/ag/Flex/vue/VueFlexContainer.vue',
  'src/components/ag/Flex/vue/VueFlexInline.vue',
  'src/components/ag/Flex/vue/VueFlexRow.vue',
  'src/components/ag/Flex/vue/VueGroup.vue',
  'src/components/ag/Flex/vue/VueStack.vue',
  'src/components/ag/Flex/vue/index.ts',
  'src/components/ag/Header/vue/VueHeader.vue',
  'src/components/ag/Header/vue/index.ts',
  'src/components/ag/IconButton/vue/VueIconButton.vue',
  'src/components/ag/IconButton/vue/index.ts',
  'src/components/ag/Progress/vue/VueProgress.vue',
  'src/components/ag/Progress/vue/index.ts',
  'src/components/ag/Sidebar/vue/VueSidebar.vue',
  'src/components/ag/Sidebar/vue/index.ts',
  'src/components/ag/SkeletonLoader/vue/VueSkeletonLoader.vue',
  'src/components/ag/SkeletonLoader/vue/index.ts',
  'src/components/ag/Tabs/vue/VueTab.vue',
  'src/components/ag/Tabs/vue/VueTabPanel.vue',
  'src/components/ag/Tabs/vue/VueTabs.vue',
  'src/components/ag/Tabs/vue/index.ts',
  'src/components/ag/Tag/vue/VueTag.vue',
  'src/components/ag/Tag/vue/index.ts',
  'src/components/ag/Toast/vue/VueToast.vue',
  'src/components/ag/Toast/vue/index.ts',
]

// Shared component files used by the support playbook
const SUPPORT_SHARED_CORE_FILES = [
  'src/components/ag/Button/core/Button.ts',
  'src/components/ag/Button/core/_Button.ts',
  'src/components/ag/Checkbox/core/Checkbox.ts',
  'src/components/ag/Checkbox/core/_Checkbox.ts',
  'src/components/ag/Combobox/core/Combobox.ts',
  'src/components/ag/Combobox/core/_Combobox.ts',
  'src/components/ag/Dialog/core/Dialog.ts',
  'src/components/ag/Dialog/core/_dialog.ts',
  'src/components/ag/Drawer/core/Drawer.ts',
  'src/components/ag/Drawer/core/_drawer.ts',
  'src/components/ag/Kbd/core/Kbd.ts',
  'src/components/ag/Kbd/core/_Kbd.ts',
  'src/components/ag/Menu/core/Menu.ts',
  'src/components/ag/Menu/core/_Menu.ts',
  'src/components/ag/MessageBubble/core/MessageBubble.ts',
  'src/components/ag/MessageBubble/core/_MessageBubble.ts',
  'src/components/ag/Pagination/core/Pagination.ts',
  'src/components/ag/Pagination/core/_Pagination.ts',
  'src/components/ag/Pagination/core/ContentPagination.ts',
  'src/components/ag/Pagination/core/_ContentPagination.ts',
  'src/components/ag/Popover/core/Popover.ts',
  'src/components/ag/Popover/core/_Popover.ts',
  'src/components/ag/Radio/core/Radio.ts',
  'src/components/ag/Radio/core/_Radio.ts',
  'src/components/ag/Rating/core/Rating.ts',
  'src/components/ag/Rating/core/_Rating.ts',
  'src/components/ag/Select/core/Select.ts',
  'src/components/ag/Select/core/_Select.ts',
  'src/components/ag/Slider/core/Slider.ts',
  'src/components/ag/Slider/core/_Slider.ts',
  'src/components/ag/Tag/core/Tag.ts',
  'src/components/ag/Tag/core/_Tag.ts',
  'src/components/ag/Tabs/core/Tabs.ts',
  'src/components/ag/Tabs/core/_Tabs.ts',
  'src/components/ag/Toggle/core/Toggle.ts',
  'src/components/ag/Toggle/core/_Toggle.ts',
  'src/components/ag/Tooltip/core/Tooltip.ts',
  'src/components/ag/Tooltip/core/_Tooltip.ts',
  'src/components/ag/shared/CloseButton/CloseButton.ts',
  'src/components/ag/shared/CloseButton/_CloseButton.ts',
  'src/components/ag/shared/form-control-styles.ts',
  'src/components/ag/shared/form-control-utils.ts',
  'src/components/ag/styles/ag-tokens.css',
  'src/components/ag/styles/ag-tokens-dark.css',
  'src/components/ag/styles/skins-bundle.css',
  'src/components/ag/styles/skin-switcher.css',
  'src/components/ag/styles/motion.styles.ts',
  'src/components/ag/styles/nav-button-styles.ts',
  'src/components/ag/styles/nav-sublink-styles.ts',
  'src/components/ag/styles/table.css',
  'src/components/ag/types/fx.ts',
  'src/components/ag/types/vue.d.ts',
  'src/components/ag/utils/handleBackdropClick.ts',
  'src/components/ag/utils/isElementInContainer.ts',
  'src/components/ag/utils/positioning.ts',
  'src/components/ag/utils/slot.ts',
  'src/components/ag/utils/unique-id.ts',
]

// React wrapper files for support
const SUPPORT_REACT_WRAPPER_FILES = [
  'src/components/ag/Button/react/ReactButton.tsx',
  'src/components/ag/Button/react/index.ts',
  'src/components/ag/Combobox/react/ReactCombobox.tsx',
  'src/components/ag/Combobox/react/index.ts',
  'src/components/ag/Dialog/react/ReactDialog.tsx',
  'src/components/ag/Dialog/react/index.ts',
  'src/components/ag/Drawer/react/ReactDrawer.tsx',
  'src/components/ag/Drawer/react/index.ts',
  'src/components/ag/Kbd/react/ReactKbd.tsx',
  'src/components/ag/Kbd/react/index.ts',
  'src/components/ag/Menu/react/ReactMenu.tsx',
  'src/components/ag/Menu/react/index.ts',
  'src/components/ag/MessageBubble/react/ReactMessageBubble.tsx',
  'src/components/ag/Pagination/react/ReactPagination.tsx',
  'src/components/ag/Pagination/react/ReactContentPagination.tsx',
  'src/components/ag/Pagination/react/index.ts',
  'src/components/ag/Popover/react/ReactPopover.tsx',
  'src/components/ag/Popover/react/index.ts',
  'src/components/ag/Radio/react/ReactRadio.tsx',
  'src/components/ag/Radio/react/index.ts',
  'src/components/ag/Rating/react/ReactRating.tsx',
  'src/components/ag/Rating/react/index.ts',
  'src/components/ag/Select/react/ReactSelect.tsx',
  'src/components/ag/Select/react/index.ts',
  'src/components/ag/Slider/react/ReactSlider.tsx',
  'src/components/ag/Slider/react/index.ts',
  'src/components/ag/Tabs/react/ReactTabs.tsx',
  'src/components/ag/Tabs/react/index.ts',
  'src/components/ag/Toggle/react/ReactToggle.tsx',
  'src/components/ag/Toggle/react/index.ts',
  'src/components/ag/Tooltip/react/ReactTooltip.tsx',
  'src/components/ag/Tooltip/react/index.ts',
]

// Vue wrapper files for support
const SUPPORT_VUE_WRAPPER_FILES = [
  'src/components/ag/Button/vue/VueButton.vue',
  'src/components/ag/Button/vue/index.ts',
  'src/components/ag/Combobox/vue/VueCombobox.vue',
  'src/components/ag/Combobox/vue/index.ts',
  'src/components/ag/Dialog/vue/VueDialog.vue',
  'src/components/ag/Dialog/vue/VueDialogFooter.vue',
  'src/components/ag/Dialog/vue/VueDialogHeader.vue',
  'src/components/ag/Dialog/vue/index.ts',
  'src/components/ag/Drawer/vue/VueDrawer.vue',
  'src/components/ag/Drawer/vue/index.ts',
  'src/components/ag/Kbd/vue/VueKbd.vue',
  'src/components/ag/Kbd/vue/index.ts',
  'src/components/ag/Menu/vue/VueMenu.vue',
  'src/components/ag/Menu/vue/VueMenuItem.vue',
  'src/components/ag/Menu/vue/VueMenuSeparator.vue',
  'src/components/ag/Menu/vue/index.ts',
  'src/components/ag/MessageBubble/vue/VueMessageBubble.vue',
  'src/components/ag/MessageBubble/vue/index.ts',
  'src/components/ag/Pagination/vue/VuePagination.vue',
  'src/components/ag/Pagination/vue/VueContentPagination.vue',
  'src/components/ag/Pagination/vue/index.ts',
  'src/components/ag/Popover/vue/VuePopover.vue',
  'src/components/ag/Popover/vue/index.ts',
  'src/components/ag/Radio/vue/VueRadio.vue',
  'src/components/ag/Radio/vue/index.ts',
  'src/components/ag/Rating/vue/VueRating.vue',
  'src/components/ag/Rating/vue/index.ts',
  'src/components/ag/Select/vue/VueSelect.vue',
  'src/components/ag/Select/vue/index.ts',
  'src/components/ag/Slider/vue/VueSlider.vue',
  'src/components/ag/Slider/vue/index.ts',
  'src/components/ag/Tabs/vue/VueTabs.vue',
  'src/components/ag/Tabs/vue/VueTab.vue',
  'src/components/ag/Tabs/vue/VueTabPanel.vue',
  'src/components/ag/Tabs/vue/index.ts',
  'src/components/ag/Toggle/vue/VueToggle.vue',
  'src/components/ag/Toggle/vue/index.ts',
  'src/components/ag/Tooltip/vue/VueTooltip.vue',
  'src/components/ag/Tooltip/vue/index.ts',
]

// Base URL for raw GitHub content at the v2 root (for files outside playbooks/)
const GITHUB_RAW_V2_BASE = 'https://raw.githubusercontent.com/AgnosticUI/agnosticui/master/v2'

// Shared skin-switcher external files and import rewrites used by all playbooks
const SKIN_SWITCHER_EXTERNAL_FILES = {
  'src/skins/skin-switcher-core.js': `${GITHUB_RAW_V2_BASE}/skins/skin-switcher-core.js`,
  'src/skins/skins-css-data.js': `${GITHUB_RAW_V2_BASE}/skins/skins-css-data.js`,
}

const SKIN_SWITCHER_CONTENT_REPLACEMENTS = {
  '../../../../skins/skin-switcher-core.js': './skins/skin-switcher-core.js',
}

export const playbooksConfig: Record<string, PlaybookConfig> = {
  login: {
    title: 'Login',
    frameworks: {
      react: [
        // Config files
        'index.html',
        'package.json',
        'vite.config.ts',
        'tsconfig.json',
        'tsconfig.app.json',
        'tsconfig.node.json',
        'eslint.config.js',
        // Public assets
        'public/facebook-icon.svg',
        'public/google-icon.svg',
        'public/logo.svg',
        // App files
        'src/App.tsx',
        'src/SkinSwitcher.tsx',
        'src/index.css',
        'src/main.tsx',
        // Component files
        ...SHARED_CORE_FILES,
        ...REACT_WRAPPER_FILES,
      ],
      vue: [
        // Config files
        'index.html',
        'package.json',
        'vite.config.ts',
        'tsconfig.json',
        'tsconfig.app.json',
        'tsconfig.node.json',
        // Public assets
        'public/facebook-icon.svg',
        'public/google-icon.svg',
        'public/logo.svg',
        // App files
        'src/App.vue',
        'src/SkinSwitcher.vue',
        'src/style.css',
        'src/main.ts',
        // Component files
        ...SHARED_CORE_FILES,
        ...VUE_WRAPPER_FILES,
      ],
      lit: [
        // Config files
        'index.html',
        'package.json',
        'tsconfig.json',
        // Public assets
        'public/facebook-icon.svg',
        'public/google-icon.svg',
        'public/logo.svg',
        // App files
        'src/index.css',
        'src/login-page.ts',
        'src/skin-switcher.ts',
        // Component files (Lit uses core directly, no wrappers)
        ...SHARED_CORE_FILES,
      ],
    },
    binaryFiles: {
      '/login-bg.jpg': `${GITHUB_RAW_BASE}/login/react-example/public/login-bg.jpg`,
    },
    externalFiles: SKIN_SWITCHER_EXTERNAL_FILES,
    contentReplacements: SKIN_SWITCHER_CONTENT_REPLACEMENTS,
  },
  onboarding: {
    title: 'Onboarding',
    frameworks: {
      react: [
        // Config files
        'index.html',
        'package.json',
        'vite.config.ts',
        'tsconfig.json',
        'tsconfig.app.json',
        'tsconfig.node.json',
        'eslint.config.js',
        // App files
        'src/App.tsx',
        'src/App.css',
        'src/SkinSwitcher.tsx',
        'src/index.css',
        'src/main.tsx',
        // Component files
        ...ONBOARDING_SHARED_CORE_FILES,
        ...ONBOARDING_REACT_WRAPPER_FILES,
      ],
      vue: [
        // Config files
        'index.html',
        'package.json',
        'vite.config.ts',
        'tsconfig.json',
        'tsconfig.app.json',
        'tsconfig.node.json',
        // App files
        'src/App.vue',
        'src/SkinSwitcher.vue',
        'src/style.css',
        'src/main.ts',
        // Component files
        ...ONBOARDING_SHARED_CORE_FILES,
        ...ONBOARDING_VUE_WRAPPER_FILES,
      ],
      lit: [
        // Config files
        'index.html',
        'package.json',
        'tsconfig.json',
        // App files
        'src/index.css',
        'src/onboarding-wizard.ts',
        'src/skin-switcher.ts',
        // Component files (Lit uses core directly, no wrappers)
        ...ONBOARDING_SHARED_CORE_FILES,
      ],
    },
    externalFiles: SKIN_SWITCHER_EXTERNAL_FILES,
    contentReplacements: SKIN_SWITCHER_CONTENT_REPLACEMENTS,
  },
  dashboard: {
    title: 'Dashboard',
    frameworks: {
      react: [
        // Config files
        'index.html',
        'package.json',
        'vite.config.ts',
        'tsconfig.json',
        'tsconfig.app.json',
        'tsconfig.node.json',
        'eslint.config.js',
        // Public assets
        'public/logo.svg',
        'public/logo-dark-mode.svg',
        'public/vite.svg',
        // App files
        'src/App.tsx',
        'src/SkinSwitcher.tsx',
        'src/index.css',
        'src/main.tsx',
        // Component files
        ...DASHBOARD_SHARED_CORE_FILES,
        ...DASHBOARD_REACT_WRAPPER_FILES,
      ],
      vue: [
        // Config files
        'index.html',
        'package.json',
        'vite.config.ts',
        'tsconfig.json',
        'tsconfig.app.json',
        'tsconfig.node.json',
        // Public assets
        'public/logo.svg',
        'public/logo-dark-mode.svg',
        'public/vite.svg',
        // App files
        'src/App.vue',
        'src/SkinSwitcher.vue',
        'src/style.css',
        'src/main.ts',
        // Component files
        ...DASHBOARD_SHARED_CORE_FILES,
        ...DASHBOARD_VUE_WRAPPER_FILES,
      ],
      lit: [
        // Config files
        'index.html',
        'package.json',
        'tsconfig.json',
        // Public assets
        'public/logo.svg',
        'public/logo-dark-mode.svg',
        'public/vite.svg',
        // App files
        'src/index.css',
        'src/dashboard-app.ts',
        'src/my-element.ts',
        'src/skin-switcher.ts',
        // Component files (Lit uses core directly, no wrappers)
        ...DASHBOARD_SHARED_CORE_FILES,
      ],
    },
    externalFiles: SKIN_SWITCHER_EXTERNAL_FILES,
    contentReplacements: SKIN_SWITCHER_CONTENT_REPLACEMENTS,
  },
  support: {
    title: 'Support Center',
    frameworks: {
      react: [
        // Config files
        'index.html',
        'package.json',
        'vite.config.ts',
        'tsconfig.json',
        'tsconfig.app.json',
        'tsconfig.node.json',
        'eslint.config.js',
        // Public assets
        'public/logo.svg',
        'public/logo-dark-mode.svg',
        // App files
        'src/App.tsx',
        'src/SkinSwitcher.tsx',
        'src/index.css',
        'src/main.tsx',
        // Component files
        ...SUPPORT_SHARED_CORE_FILES,
        ...SUPPORT_REACT_WRAPPER_FILES,
      ],
      vue: [
        // Config files
        'index.html',
        'package.json',
        'vite.config.ts',
        'tsconfig.json',
        'tsconfig.app.json',
        'tsconfig.node.json',
        // Public assets
        'public/logo.svg',
        'public/logo-dark-mode.svg',
        // App files
        'src/App.vue',
        'src/SkinSwitcher.vue',
        'src/style.css',
        'src/main.ts',
        // Component files
        ...SUPPORT_SHARED_CORE_FILES,
        ...SUPPORT_VUE_WRAPPER_FILES,
      ],
      lit: [
        // Config files
        'index.html',
        'package.json',
        'tsconfig.json',
        // Public assets
        'public/logo.svg',
        'public/logo-dark-mode.svg',
        // App files
        'src/index.css',
        'src/support-app.ts',
        'src/skin-switcher.ts',
        // Component files (Lit uses core directly, no wrappers)
        ...SUPPORT_SHARED_CORE_FILES,
      ],
    },
    externalFiles: SKIN_SWITCHER_EXTERNAL_FILES,
    contentReplacements: SKIN_SWITCHER_CONTENT_REPLACEMENTS,
  },
}

// ── Grid Playbook ─────────────────────────────────────────────────────────────

const GRID_SHARED_CORE_FILES = [
  'src/components/ag/Alert/core/Alert.ts',
  'src/components/ag/Alert/core/_Alert.ts',
  'src/components/ag/Avatar/core/Avatar.ts',
  'src/components/ag/Avatar/core/_Avatar.ts',
  'src/components/ag/Avatar/core/AvatarGroup.ts',
  'src/components/ag/Breadcrumb/core/Breadcrumb.ts',
  'src/components/ag/Breadcrumb/core/_Breadcrumb.ts',
  'src/components/ag/Button/core/Button.ts',
  'src/components/ag/Button/core/_Button.ts',
  'src/components/ag/Checkbox/core/Checkbox.ts',
  'src/components/ag/Checkbox/core/_Checkbox.ts',
  'src/components/ag/Dialog/core/Dialog.ts',
  'src/components/ag/Dialog/core/_dialog.ts',
  'src/components/ag/EmptyState/core/EmptyState.ts',
  'src/components/ag/EmptyState/core/_EmptyState.ts',
  'src/components/ag/Header/core/Header.ts',
  'src/components/ag/Header/core/_Header.ts',
  'src/components/ag/IconButton/core/IconButton.ts',
  'src/components/ag/IconButton/core/_IconButton.ts',
  'src/components/ag/Input/core/Input.ts',
  'src/components/ag/Input/core/_Input.ts',
  'src/components/ag/Input/core/_Input.BACKUP.ts',
  'src/components/ag/Menu/core/Menu.ts',
  'src/components/ag/Menu/core/_Menu.ts',
  'src/components/ag/Pagination/core/Pagination.ts',
  'src/components/ag/Pagination/core/_Pagination.ts',
  'src/components/ag/Pagination/core/ContentPagination.ts',
  'src/components/ag/Pagination/core/_ContentPagination.ts',
  'src/components/ag/Select/core/Select.ts',
  'src/components/ag/Select/core/_Select.ts',
  'src/components/ag/SelectionButton/core/SelectionButton.ts',
  'src/components/ag/SelectionButton/core/_SelectionButton.ts',
  'src/components/ag/SelectionButtonGroup/core/SelectionButtonGroup.ts',
  'src/components/ag/SelectionButtonGroup/core/_SelectionButtonGroup.ts',
  'src/components/ag/Tag/core/Tag.ts',
  'src/components/ag/Tag/core/_Tag.ts',
  'src/components/ag/Toast/core/Toast.ts',
  'src/components/ag/Toast/core/_Toast.ts',
  'src/components/ag/shared/CloseButton/CloseButton.ts',
  'src/components/ag/shared/CloseButton/_CloseButton.ts',
  'src/components/ag/shared/form-control-styles.ts',
  'src/components/ag/shared/form-control-utils.ts',
  'src/components/ag/styles/ag-tokens.css',
  'src/components/ag/styles/ag-tokens-dark.css',
  'src/components/ag/styles/skins-bundle.css',
  'src/components/ag/styles/skin-switcher.css',
  'src/components/ag/styles/motion.styles.ts',
  'src/components/ag/styles/nav-button-styles.ts',
  'src/components/ag/styles/nav-sublink-styles.ts',
  'src/components/ag/styles/table.css',
  'src/components/ag/types/fx.ts',
  'src/components/ag/types/vue.d.ts',
  'src/components/ag/utils/handleBackdropClick.ts',
  'src/components/ag/utils/isElementInContainer.ts',
  'src/components/ag/utils/positioning.ts',
  'src/components/ag/utils/slot.ts',
  'src/components/ag/utils/unique-id.ts',
]

const GRID_REACT_WRAPPER_FILES = [
  'src/components/ag/Alert/react/ReactAlert.tsx',
  'src/components/ag/Alert/react/index.ts',
  'src/components/ag/Avatar/react/ReactAvatar.tsx',
  'src/components/ag/Avatar/react/index.ts',
  'src/components/ag/Breadcrumb/react/ReactBreadcrumb.tsx',
  'src/components/ag/Breadcrumb/react/index.ts',
  'src/components/ag/Button/react/ReactButton.tsx',
  'src/components/ag/Button/react/index.ts',
  'src/components/ag/Checkbox/react/ReactCheckbox.tsx',
  'src/components/ag/Checkbox/react/index.ts',
  'src/components/ag/Dialog/react/ReactDialog.tsx',
  'src/components/ag/Dialog/react/index.ts',
  'src/components/ag/EmptyState/react/ReactEmptyState.tsx',
  'src/components/ag/EmptyState/react/index.ts',
  'src/components/ag/Header/react/ReactHeader.tsx',
  'src/components/ag/Header/react/index.ts',
  'src/components/ag/IconButton/react/ReactIconButton.tsx',
  'src/components/ag/IconButton/react/index.ts',
  'src/components/ag/Input/react/ReactInput.tsx',
  'src/components/ag/Input/react/index.ts',
  'src/components/ag/Menu/react/ReactMenu.tsx',
  'src/components/ag/Menu/react/index.ts',
  'src/components/ag/Pagination/react/ReactPagination.tsx',
  'src/components/ag/Pagination/react/ReactContentPagination.tsx',
  'src/components/ag/Pagination/react/index.ts',
  'src/components/ag/Select/react/ReactSelect.tsx',
  'src/components/ag/Select/react/index.ts',
  'src/components/ag/SelectionButton/react/ReactSelectionButton.tsx',
  'src/components/ag/SelectionButton/react/index.ts',
  'src/components/ag/SelectionButtonGroup/react/ReactSelectionButtonGroup.tsx',
  'src/components/ag/SelectionButtonGroup/react/index.ts',
  'src/components/ag/Tag/react/ReactTag.tsx',
  'src/components/ag/Tag/react/index.ts',
  'src/components/ag/Toast/react/ReactToast.tsx',
  'src/components/ag/Toast/react/index.ts',
]

const GRID_VUE_WRAPPER_FILES = [
  'src/components/ag/Alert/vue/VueAlert.vue',
  'src/components/ag/Alert/vue/index.ts',
  'src/components/ag/Avatar/vue/VueAvatar.vue',
  'src/components/ag/Avatar/vue/VueAvatarGroup.vue',
  'src/components/ag/Avatar/vue/index.ts',
  'src/components/ag/Breadcrumb/vue/VueBreadcrumb.vue',
  'src/components/ag/Breadcrumb/vue/index.ts',
  'src/components/ag/Button/vue/VueButton.vue',
  'src/components/ag/Button/vue/index.ts',
  'src/components/ag/Checkbox/vue/VueCheckbox.vue',
  'src/components/ag/Checkbox/vue/index.ts',
  'src/components/ag/Dialog/vue/VueDialog.vue',
  'src/components/ag/Dialog/vue/VueDialogFooter.vue',
  'src/components/ag/Dialog/vue/VueDialogHeader.vue',
  'src/components/ag/Dialog/vue/index.ts',
  'src/components/ag/EmptyState/vue/VueEmptyState.vue',
  'src/components/ag/EmptyState/vue/index.ts',
  'src/components/ag/Header/vue/VueHeader.vue',
  'src/components/ag/Header/vue/index.ts',
  'src/components/ag/IconButton/vue/VueIconButton.vue',
  'src/components/ag/IconButton/vue/index.ts',
  'src/components/ag/Input/vue/VueInput.vue',
  'src/components/ag/Input/vue/index.ts',
  'src/components/ag/Menu/vue/VueMenu.vue',
  'src/components/ag/Menu/vue/VueMenuItem.vue',
  'src/components/ag/Menu/vue/VueMenuSeparator.vue',
  'src/components/ag/Menu/vue/index.ts',
  'src/components/ag/Pagination/vue/VuePagination.vue',
  'src/components/ag/Pagination/vue/VueContentPagination.vue',
  'src/components/ag/Pagination/vue/index.ts',
  'src/components/ag/Select/vue/VueSelect.vue',
  'src/components/ag/Select/vue/index.ts',
  'src/components/ag/SelectionButton/vue/VueSelectionButton.vue',
  'src/components/ag/SelectionButton/vue/index.ts',
  'src/components/ag/SelectionButtonGroup/vue/VueSelectionButtonGroup.vue',
  'src/components/ag/SelectionButtonGroup/vue/index.ts',
  'src/components/ag/Tag/vue/VueTag.vue',
  'src/components/ag/Tag/vue/index.ts',
  'src/components/ag/Toast/vue/VueToast.vue',
  'src/components/ag/Toast/vue/index.ts',
]

// Merge the grid entry into the exported config
Object.assign(playbooksConfig, {
  grid: {
    title: 'Data Grid',
    frameworks: {
      react: [
        // Config files
        'index.html',
        'package.json',
        'vite.config.ts',
        'tsconfig.json',
        'tsconfig.app.json',
        'tsconfig.node.json',
        'eslint.config.js',
        // App files
        'src/App.tsx',
        'src/App.css',
        'src/SkinSwitcher.tsx',
        'src/index.css',
        'src/main.tsx',
        // Data
        'src/data/products.ts',
        // Panels
        'src/panels/SimplePanel.tsx',
        'src/panels/GridJsPanel.tsx',
        'src/panels/TanstackPanel.tsx',
        // Component files
        ...GRID_SHARED_CORE_FILES,
        ...GRID_REACT_WRAPPER_FILES,
      ],
      vue: [
        // Config files
        'index.html',
        'package.json',
        'vite.config.ts',
        'tsconfig.json',
        'tsconfig.app.json',
        'tsconfig.node.json',
        // App files
        'src/App.vue',
        'src/SkinSwitcher.vue',
        'src/app.css',
        'src/main.ts',
        // Data
        'src/data/products.ts',
        // Panels
        'src/panels/SimplePanel.vue',
        'src/panels/GridJsPanel.vue',
        'src/panels/TanstackPanel.vue',
        // Component files
        ...GRID_SHARED_CORE_FILES,
        ...GRID_VUE_WRAPPER_FILES,
      ],
      lit: [
        // Config files
        'index.html',
        'package.json',
        'tsconfig.json',
        // App files
        'src/inventory-app.ts',
        'src/app.css',
        'src/skin-switcher.ts',
        'src/main.ts',
        'src/index.css',
        // Data
        'src/data/products.ts',
        // Panels
        'src/panels/simple-panel.ts',
        'src/panels/gridjs-panel.ts',
        'src/panels/tanstack-panel.ts',
        // Component files (Lit uses core directly, no wrappers)
        ...GRID_SHARED_CORE_FILES,
      ],
    },
    externalFiles: SKIN_SWITCHER_EXTERNAL_FILES,
    contentReplacements: SKIN_SWITCHER_CONTENT_REPLACEMENTS,
  } satisfies PlaybookConfig,
})
