// AUTO-GENERATED by v2/schema/scripts/codegen.ts — do not edit by hand
// Run: npm run codegen   (from v2/schema/)
// Source: v2/lib/src/components/*/core/_*.ts

import * as React from 'react';
import type { AgNode } from '@agnosticui/schema';
import { ReactAccordion } from 'agnosticui-core/accordion/react';
import { ReactAlert } from 'agnosticui-core/alert/react';
import { ReactAspectRatio } from 'agnosticui-core/aspect-ratio/react';
import { ReactAvatar } from 'agnosticui-core/avatar/react';
import { ReactBadge } from 'agnosticui-core/badge/react';
import { ReactBadgeFx } from 'agnosticui-core/badge-fx/react';
import { ReactBreadcrumb } from 'agnosticui-core/breadcrumb/react';
import { ReactButton } from 'agnosticui-core/button/react';
import { ReactButtonFx } from 'agnosticui-core/button-fx/react';
import { ReactCard } from 'agnosticui-core/card/react';
import { ReactCheckbox } from 'agnosticui-core/checkbox/react';
import { ReactDivider } from 'agnosticui-core/divider/react';
import { ReactFieldset } from 'agnosticui-core/fieldset/react';
import { ReactHeader } from 'agnosticui-core/header/react';
import { ReactIcon } from 'agnosticui-core/icon/react';
import { ReactIconButton } from 'agnosticui-core/icon-button/react';
import { ReactIconButtonFx } from 'agnosticui-core/icon-button-fx/react';
import { ReactInput } from 'agnosticui-core/input/react';
import { ReactIntlFormatter } from 'agnosticui-core/intl-formatter/react';
import { ReactKbd } from 'agnosticui-core/kbd/react';
import { ReactLink } from 'agnosticui-core/link/react';
import { ReactLoader } from 'agnosticui-core/loader/react';
import { ReactMark } from 'agnosticui-core/mark/react';
import { ReactMessageBubble } from 'agnosticui-core/message-bubble/react';
import { ReactProgress } from 'agnosticui-core/progress/react';
import { ReactRadio } from 'agnosticui-core/radio/react';
import { ReactRating } from 'agnosticui-core/rating/react';
import { ReactSelect } from 'agnosticui-core/select/react';
import { ReactSelectionButton } from 'agnosticui-core/selection-button/react';
import { ReactSelectionButtonGroup } from 'agnosticui-core/selection-button-group/react';
import { ReactSelectionCard } from 'agnosticui-core/selection-card/react';
import { ReactSelectionCardGroup } from 'agnosticui-core/selection-card-group/react';
import { ReactSpinner } from 'agnosticui-core/spinner/react';
import { ReactTabs } from 'agnosticui-core/tabs/react';
import { ReactTag } from 'agnosticui-core/tag/react';
import { ReactToggle } from 'agnosticui-core/toggle/react';
import { ReactTooltip } from 'agnosticui-core/tooltip/react';

type Actions = Record<string, (payload?: unknown) => void>;

export interface AgDynamicRendererProps {
  nodes: AgNode[];
  actions?: Actions;
}

/**
 * Create an action dispatcher bound to a given actions map.
 *
 * This is the XSS boundary: only aliases present in the map are called;
 * unknown aliases are silently ignored. No eval(), no dynamic code execution.
 */
export function createDispatcher(actions: Actions) {
  return (alias?: string): void => {
    if (alias) actions[alias]?.();
  };
}

function dispatch(alias: string | undefined, actions: Actions): void {
  if (alias) actions[alias]?.();
}

function renderNode(
  node: AgNode,
  nodeMap: Map<string, AgNode>,
  actions: Actions,
): React.ReactNode {
  const renderChildren = (childIds?: string[]): React.ReactNode[] =>
    (childIds ?? [])
      .map(id => {
        const child = nodeMap.get(id);
        return child ? renderNode(child, nodeMap, actions) : null;
      })
      .filter((n): n is React.ReactNode => n !== null);

  switch (node.component) {
    case 'AgAccordion':
      return (
        <ReactAccordion
          key={node.id}
        >
          {renderChildren(node.children)}
        </ReactAccordion>
      );

    case 'AgAlert':
      return (
        <ReactAlert
          key={node.id}
          variant={node.variant}
          bordered={node.bordered}
          rounded={node.rounded}
          borderedLeft={node.borderedLeft}
          dismissible={node.dismissible}
          onAlertDismiss={() => dispatch(node.on_dismiss, actions)}
        >
          {renderChildren(node.children)}
        </ReactAlert>
      );

    case 'AgAspectRatio':
      return (
        <ReactAspectRatio
          key={node.id}
          width={node.width}
          height={node.height}
          maxWidth={node.maxWidth} />
      );

    case 'AgAvatar':
      return (
        <ReactAvatar
          key={node.id}
          text={node.text}
          imgSrc={node.imgSrc}
          imgAlt={node.imgAlt}
          size={node.size}
          shape={node.shape}
          variant={node.variant}
          ariaLabel={node.ariaLabel} />
      );

    case 'AgBadge':
      return (
        <ReactBadge
          key={node.id}
          variant={node.variant}
          size={node.size}
          dot={node.dot}
          value={node.value}
          max={node.max}
          interactive={node.interactive}
          statusLabel={node.statusLabel}
          live={node.live}
          hiddenFromAT={node.hiddenFromAT} />
      );

    case 'AgBadgeFx':
      return (
        <ReactBadgeFx
          key={node.id}
          variant={node.variant}
          size={node.size}
          dot={node.dot}
          value={node.value}
          max={node.max}
          interactive={node.interactive}
          statusLabel={node.statusLabel}
          live={node.live}
          hiddenFromAT={node.hiddenFromAT}
          fx={node.fx}
          fxSpeed={node.fxSpeed}
          fxEase={node.fxEase}
          fxDisabled={node.fxDisabled} />
      );

    case 'AgBreadcrumb':
      return (
        <ReactBreadcrumb
          key={node.id}
          type={node.type}
          primary={node.primary}
          ariaLabel={node.ariaLabel}
          onBreadcrumbClick={() => dispatch(node.on_click, actions)} />
      );

    case 'AgButton':
      return (
        <ReactButton
          key={node.id}
          variant={node.variant}
          size={node.size}
          shape={node.shape}
          bordered={node.bordered}
          ghost={node.ghost}
          link={node.link}
          grouped={node.grouped}
          fullWidth={node.fullWidth}
          type={node.type}
          disabled={node.disabled}
          loading={node.loading}
          ariaLabel={node.ariaLabel}
          onClick={() => dispatch(node.on_click, actions)}
          onToggle={() => dispatch(node.on_toggle, actions)}
        >
          {node.children?.length ? renderChildren(node.children) : (node.label ?? '')}
        </ReactButton>
      );

    case 'AgButtonFx':
      return (
        <ReactButtonFx
          key={node.id}
          variant={node.variant}
          size={node.size}
          shape={node.shape}
          bordered={node.bordered}
          ghost={node.ghost}
          link={node.link}
          grouped={node.grouped}
          fullWidth={node.fullWidth}
          type={node.type}
          disabled={node.disabled}
          loading={node.loading}
          ariaLabel={node.ariaLabel}
          fx={node.fx}
          fxSpeed={node.fxSpeed}
          fxEase={node.fxEase}
          fxDisabled={node.fxDisabled}
          onClick={() => dispatch(node.on_click, actions)}
          onToggle={() => dispatch(node.on_toggle, actions)}
        >
          {node.children?.length ? renderChildren(node.children) : (node.label ?? '')}
        </ReactButtonFx>
      );

    case 'AgCard':
      return (
        <ReactCard
          key={node.id}
          stacked={node.stacked}
          shadow={node.shadow}
          animated={node.animated}
          rounded={node.rounded}
          variant={node.variant}
          hasMedia={node.hasMedia}
          mediaPosition={node.mediaPosition}
        >
          {renderChildren(node.children)}
        </ReactCard>
      );

    case 'AgCheckbox':
      return (
        <ReactCheckbox
          key={node.id}
          name={node.name}
          value={node.value}
          checked={node.checked}
          disabled={node.disabled}
          size={node.size}
          labelText={node.labelText}
          labelPosition={node.labelPosition}
          required={node.required}
          invalid={node.invalid}
          errorMessage={node.errorMessage}
          helpText={node.helpText}
          onClick={() => dispatch(node.on_click, actions)}
          onChange={() => dispatch(node.on_change, actions)} />
      );

    case 'AgDivider':
      return (
        <ReactDivider
          key={node.id}
          vertical={node.vertical}
          justify={node.justify}
          size={node.size}
          variant={node.variant} />
      );

    case 'AgFieldset':
      return (
        <ReactFieldset
          key={node.id}
          legend={node.legend}
          bordered={node.bordered}
          layout={node.layout}
          legendHidden={node.legendHidden}
        >
          {renderChildren(node.children)}
        </ReactFieldset>
      );

    case 'AgHeader':
      return (
        <ReactHeader
          key={node.id}
          sticky={node.sticky}
          contentJustify={node.contentJustify}
        >
          {renderChildren(node.children)}
        </ReactHeader>
      );

    case 'AgIcon':
      return (
        <ReactIcon
          key={node.id}
          size={node.size}
          type={node.type}
          noFill={node.noFill} />
      );

    case 'AgIconButton':
      return (
        <ReactIconButton
          key={node.id}
          label={node.label}
          icon={node.icon}
          unicode={node.unicode}
          size={node.size}
          variant={node.variant}
          type={node.type}
          disabled={node.disabled}
          loading={node.loading}
          onIconButtonClick={() => dispatch(node.on_click, actions)}
          onIconButtonActivate={() => dispatch(node.on_activate, actions)} />
      );

    case 'AgIconButtonFx':
      return (
        <ReactIconButtonFx
          key={node.id}
          label={node.label}
          icon={node.icon}
          unicode={node.unicode}
          size={node.size}
          variant={node.variant}
          type={node.type}
          disabled={node.disabled}
          loading={node.loading}
          fx={node.fx}
          fxSpeed={node.fxSpeed}
          fxEase={node.fxEase}
          fxDisabled={node.fxDisabled}
          onIconButtonClick={() => dispatch(node.on_click, actions)}
          onIconButtonActivate={() => dispatch(node.on_activate, actions)} />
      );

    case 'AgInput':
      return (
        <ReactInput
          key={node.id}
          label={node.label}
          labelHidden={node.labelHidden}
          labelPosition={node.labelPosition}
          noLabel={node.noLabel}
          ariaLabel={node.ariaLabel}
          name={node.name}
          type={node.type}
          value={node.value}
          placeholder={node.placeholder}
          rows={node.rows}
          cols={node.cols}
          size={node.size}
          capsule={node.capsule}
          rounded={node.rounded}
          underlined={node.underlined}
          underlinedWithBackground={node.underlinedWithBackground}
          inline={node.inline}
          required={node.required}
          disabled={node.disabled}
          readonly={node.readonly}
          invalid={node.invalid}
          errorMessage={node.errorMessage}
          helpText={node.helpText}
          onClick={() => dispatch(node.on_click, actions)}
          onChange={() => dispatch(node.on_change, actions)} />
      );

    case 'AgIntlFormatter':
      return (
        <ReactIntlFormatter
          key={node.id}
          type={node.type}
          value={node.value}
          lang={node.lang}
          date={node.date}
          weekday={node.weekday}
          era={node.era}
          year={node.year}
          month={node.month}
          day={node.day}
          hour={node.hour}
          minute={node.minute}
          second={node.second}
          timeZoneName={node.timeZoneName}
          timeZone={node.timeZone}
          hourFormat={node.hourFormat}
          dateStyle={node.dateStyle}
          timeStyle={node.timeStyle}
          noGrouping={node.noGrouping}
          currency={node.currency}
          currencyDisplay={node.currencyDisplay}
          minimumIntegerDigits={node.minimumIntegerDigits}
          minimumFractionDigits={node.minimumFractionDigits}
          maximumFractionDigits={node.maximumFractionDigits}
          minimumSignificantDigits={node.minimumSignificantDigits}
          maximumSignificantDigits={node.maximumSignificantDigits} />
      );

    case 'AgKbd':
      return (
        <ReactKbd
          key={node.id}
          variant={node.variant}
          bordered={node.bordered}
          background={node.background}
          size={node.size}
        >
          {renderChildren(node.children)}
        </ReactKbd>
      );

    case 'AgLink':
      return (
        <ReactLink
          key={node.id}
          href={node.href}
          variant={node.variant}
          isButton={node.isButton}
          buttonSize={node.buttonSize}
          buttonShape={node.buttonShape}
          buttonBordered={node.buttonBordered}
          external={node.external}
          disabled={node.disabled}
          ariaLabel={node.ariaLabel}
          onClick={() => dispatch(node.on_click, actions)}
        >
          {renderChildren(node.children)}
        </ReactLink>
      );

    case 'AgLoader':
      return (
        <ReactLoader
          key={node.id}
          size={node.size}
          ariaLabel={node.ariaLabel} />
      );

    case 'AgMark':
      return (
        <ReactMark
          key={node.id}
          variant={node.variant}
          search={node.search}
          caseSensitive={node.caseSensitive}
          matchAll={node.matchAll}
        >
          {renderChildren(node.children)}
        </ReactMark>
      );

    case 'AgMessageBubble':
      return (
        <ReactMessageBubble
          key={node.id}
          from={node.from}
          message={node.message}
          time={node.time}
          author={node.author}
          avatarUrl={node.avatarUrl}
          footer={node.footer}
          variant={node.variant}
        >
          {renderChildren(node.children)}
        </ReactMessageBubble>
      );

    case 'AgProgress':
      return (
        <ReactProgress
          key={node.id}
          value={node.value}
          max={node.max}
          label={node.label}
          size={node.size}
        >
          {renderChildren(node.children)}
        </ReactProgress>
      );

    case 'AgRadio':
      return (
        <ReactRadio
          key={node.id}
          name={node.name}
          value={node.value}
          checked={node.checked}
          disabled={node.disabled}
          size={node.size}
          theme={node.theme}
          labelText={node.labelText}
          labelPosition={node.labelPosition}
          label={node.label}
          labelHidden={node.labelHidden}
          noLabel={node.noLabel}
          required={node.required}
          invalid={node.invalid}
          errorMessage={node.errorMessage}
          helpText={node.helpText}
          onClick={() => dispatch(node.on_click, actions)}
          onChange={() => dispatch(node.on_change, actions)} />
      );

    case 'AgRating':
      return (
        <ReactRating
          key={node.id}
          value={node.value}
          max={node.max}
          precision={node.precision}
          readonly={node.readonly}
          allowClear={node.allowClear}
          variant={node.variant}
          size={node.size}
          name={node.name}
          label={node.label}
          labelPosition={node.labelPosition}
          labelHidden={node.labelHidden}
          noLabel={node.noLabel}
          required={node.required}
          invalid={node.invalid}
          errorMessage={node.errorMessage}
          helpText={node.helpText} />
      );

    case 'AgSelect':
      return (
        <ReactSelect
          key={node.id}
          size={node.size}
          multiple={node.multiple}
          disabled={node.disabled}
          name={node.name}
          multipleSize={node.multipleSize}
          label={node.label}
          labelPosition={node.labelPosition}
          labelHidden={node.labelHidden}
          noLabel={node.noLabel}
          required={node.required}
          invalid={node.invalid}
          errorMessage={node.errorMessage}
          helpText={node.helpText}
          onClick={() => dispatch(node.on_click, actions)}
          onChange={() => dispatch(node.on_change, actions)} />
      );

    case 'AgSelectionButton':
      return (
        <ReactSelectionButton
          key={node.id}
          value={node.value}
          label={node.label}
          checked={node.checked}
          disabled={node.disabled} />
      );

    case 'AgSelectionButtonGroup':
      return (
        <ReactSelectionButtonGroup
          key={node.id}
          type={node.type}
          name={node.name}
          legend={node.legend}
          legendHidden={node.legendHidden}
          theme={node.theme}
          size={node.size}
          shape={node.shape}
          value={node.value}
          values={node.values}
          disabled={node.disabled}
          required={node.required} />
      );

    case 'AgSelectionCard':
      return (
        <ReactSelectionCard
          key={node.id}
          value={node.value}
          label={node.label}
          checked={node.checked}
          disabled={node.disabled} />
      );

    case 'AgSelectionCardGroup':
      return (
        <ReactSelectionCardGroup
          key={node.id}
          type={node.type}
          name={node.name}
          legend={node.legend}
          legendHidden={node.legendHidden}
          theme={node.theme}
          value={node.value}
          values={node.values}
          disabled={node.disabled}
          required={node.required} />
      );

    case 'AgSpinner':
      return (
        <ReactSpinner
          key={node.id}
          size={node.size}
          ariaLabel={node.ariaLabel} />
      );

    case 'AgTabs':
      return (
        <ReactTabs
          key={node.id}
          activation={node.activation}
          activeTab={node.activeTab}
          orientation={node.orientation}
          ariaLabel={node.ariaLabel} />
      );

    case 'AgTag':
      return (
        <ReactTag
          key={node.id}
          variant={node.variant}
          shape={node.shape}
          uppercase={node.uppercase}
          removable={node.removable}
          onTagRemove={() => dispatch(node.on_remove, actions)}
        >
          {renderChildren(node.children)}
        </ReactTag>
      );

    case 'AgToggle':
      return (
        <ReactToggle
          key={node.id}
          label={node.label}
          labelPosition={node.labelPosition}
          labelHidden={node.labelHidden}
          noLabel={node.noLabel}
          checked={node.checked}
          size={node.size}
          variant={node.variant}
          disabled={node.disabled}
          readonly={node.readonly}
          required={node.required}
          invalid={node.invalid}
          errorMessage={node.errorMessage}
          helpText={node.helpText}
          name={node.name}
          value={node.value}
          onClick={() => dispatch(node.on_click, actions)}
          onToggleChange={() => dispatch(node.on_change, actions)} />
      );

    case 'AgTooltip':
      return (
        <ReactTooltip
          key={node.id}
          content={node.content}
          placement={node.placement}
          distance={node.distance}
          skidding={node.skidding}
          trigger={node.trigger}
          disabled={node.disabled} />
      );

    default:
      return null;
  }
}

/**
 * AgDynamicRenderer (React)
 *
 * Consumes a flat array of AgNode objects and renders them using the
 * AgnosticUI React wrapper components. Nodes not referenced as children
 * by any other node are treated as roots.
 *
 * Actions are routed through a whitelist map — unknown aliases are
 * silently ignored, providing an XSS boundary.
 */
export function AgDynamicRenderer({ nodes, actions = {} }: AgDynamicRendererProps): React.ReactElement {
  const nodeMap = new Map(nodes.map(n => [n.id, n]));
  const childIds = new Set(nodes.flatMap(n => n.children ?? []));
  const rootNodes = nodes.filter(n => !childIds.has(n.id));

  return (
    <>
      {rootNodes.map(node => renderNode(node, nodeMap, actions))}
    </>
  );
}
