// AUTO-GENERATED by v2/schema/scripts/codegen.ts — do not edit by hand
// Run: npm run codegen   (from v2/schema/)
// Source: v2/lib/src/components/*/core/_*.ts

import { Project, type Type, type InterfaceDeclaration, type Symbol as MorphSymbol } from 'ts-morph';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { writeFileSync } from 'fs';
import { omitConfig, actionAliasMap, typeOverrides, skipComponents } from './codegen.config.js';

// scripts/ -> schema/ -> v2/ -> agnosticui/
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
const SCHEMA_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const GLOB = `${ROOT}/v2/lib/src/components/*/core/_*.ts`;

const FILE_HEADER = `// AUTO-GENERATED by v2/schema/scripts/codegen.ts — do not edit by hand
// Run: npm run codegen   (from v2/schema/)
// Source: v2/lib/src/components/*/core/_*.ts
`;

// ─── Type mapping ──────────────────────────────────────────────────────────────

type PropMapping = { tsType: string; zodExpr: string };

function mapType(type: Type): PropMapping | null {
  // Strip undefined/null (optional / nullable props)
  const t = type.getNonNullableType();

  if (t.isBoolean()) return { tsType: 'boolean', zodExpr: 'z.boolean()' };
  if (t.isString()) return { tsType: 'string', zodExpr: 'z.string()' };
  if (t.isNumber()) return { tsType: 'number', zodExpr: 'z.number()' };

  // Array types: only handle string[] and number[] for SDUI
  if (t.isArray()) {
    const el = t.getArrayElementType();
    if (!el) return null;
    const elMap = mapType(el);
    if (!elMap) return null;
    return { tsType: `${elMap.tsType}[]`, zodExpr: `z.array(${elMap.zodExpr})` };
  }

  // Union types
  if (t.isUnion()) {
    const members = t.getUnionTypes().filter(m =>
      !m.isUndefined() &&
      !m.isNull() &&
      !m.isBoolean() &&
      !m.isBooleanLiteral() &&
      !(m.isStringLiteral() && m.getLiteralValue() === '')
    );

    if (members.length === 0) return null;
    if (members.length === 1) return mapType(members[0]);

    // All string literals → z.enum
    if (members.every(m => m.isStringLiteral())) {
      const values = members.map(m => m.getLiteralValue() as string);
      const tsType = values.map(v => `'${v}'`).join(' | ');
      const zodExpr = `z.enum([${values.map(v => `'${v}'`).join(', ')}])`;
      return { tsType, zodExpr };
    }

    // string | number (or literals of each)
    const allPrimitive = members.every(m =>
      m.isString() || m.isNumber() || m.isStringLiteral() || m.isNumberLiteral()
    );
    if (allPrimitive) {
      const hasStr = members.some(m => m.isString() || m.isStringLiteral());
      const hasNum = members.some(m => m.isNumber() || m.isNumberLiteral());
      if (hasStr && hasNum) {
        return { tsType: 'string | number', zodExpr: 'z.union([z.string(), z.number()])' };
      }
    }

    // Fallback: if a string member is present (e.g. string | Date), use string
    if (members.some(m => m.isString() || m.isStringLiteral())) {
      return { tsType: 'string', zodExpr: 'z.string()' };
    }

    return null;
  }

  // Single string literal
  if (t.isStringLiteral()) {
    const v = t.getLiteralValue() as string;
    if (v === '') return null;
    return { tsType: `'${v}'`, zodExpr: `z.literal('${v}')` };
  }

  // Single number literal
  if (t.isNumberLiteral()) {
    const v = t.getLiteralValue() as number;
    return { tsType: `${v}`, zodExpr: `z.literal(${v})` };
  }

  return null; // objects, complex types — skip
}

// ─── Prop extraction ───────────────────────────────────────────────────────────

interface PropInfo {
  name: string;
  tsType: string;
  zodExpr: string;
}

function isFunctionSymbol(sym: MorphSymbol): boolean {
  const decl = sym.getValueDeclaration();
  if (!decl) return false;
  return decl.getType().getNonNullableType().getCallSignatures().length > 0;
}

function getPropsForComponent(componentName: string, iface: InterfaceDeclaration): PropInfo[] {
  const sdui = `Ag${componentName}`;
  const manualOmit = new Set(omitConfig[sdui] ?? []);
  const overrides = (typeOverrides as Record<string, Record<string, PropMapping>>)[sdui] ?? {};
  const seenAliases = new Set<string>();
  const result: PropInfo[] = [];

  for (const sym of iface.getType().getProperties()) {
    const propName = sym.getName();

    if (manualOmit.has(propName)) continue;

    const decl = sym.getValueDeclaration();
    if (!decl) continue;

    if (isFunctionSymbol(sym)) {
      const alias = actionAliasMap[propName];
      if (alias && !seenAliases.has(alias)) {
        seenAliases.add(alias);
        result.push({ name: alias, tsType: 'string', zodExpr: 'z.string()' });
      }
      continue;
    }

    if (overrides[propName]) {
      result.push({ name: propName, ...overrides[propName] });
      continue;
    }

    const mapping = mapType(decl.getType());
    if (!mapping) {
      console.warn(`  WARN: cannot map type for ${sdui}.${propName} — prop skipped`);
      continue;
    }

    result.push({ name: propName, tsType: mapping.tsType, zodExpr: mapping.zodExpr });
  }

  return result;
}

// ─── Code generators ──────────────────────────────────────────────────────────

function quoteName(name: string): string {
  return /[^a-zA-Z0-9_$]/.test(name) ? `'${name}'` : name;
}

function generateNodeInterface(componentName: string, props: PropInfo[]): string {
  const sdui = `Ag${componentName}`;
  const lines = [
    `export interface ${sdui}Node {`,
    `  id: string;`,
    `  component: '${sdui}';`,
  ];
  for (const p of props) {
    lines.push(`  ${quoteName(p.name)}?: ${p.tsType};`);
  }
  lines.push(`  children?: string[];`);
  lines.push(`}`);
  return lines.join('\n');
}

function generateZodSchema(componentName: string, props: PropInfo[]): string {
  const sdui = `Ag${componentName}`;
  const lines = [
    `export const ${sdui}Schema = z.object({`,
    `  id: z.string(),`,
    `  component: z.literal('${sdui}'),`,
  ];
  for (const p of props) {
    lines.push(`  ${quoteName(p.name)}: ${p.zodExpr}.optional(),`);
  }
  lines.push(`  children: z.array(z.string()).optional(),`);
  lines.push(`});`);
  return lines.join('\n');
}

function generateTypesTs(components: Array<{ name: string; props: PropInfo[] }>): string {
  const interfaces = components.map(c => generateNodeInterface(c.name, c.props)).join('\n\n');
  const union = components.map(c => `  | Ag${c.name}Node`).join('\n');
  return [
    FILE_HEADER,
    interfaces,
    '',
    `export type AgNode =`,
    `${union};`,
    '',
    `export type AgComponentName = AgNode['component'];`,
    '',
  ].join('\n');
}

function generateSchemaTs(components: Array<{ name: string; props: PropInfo[] }>): string {
  const schemas = components.map(c => generateZodSchema(c.name, c.props)).join('\n\n');
  const union = components.map(c => `  Ag${c.name}Schema`).join(',\n');
  return [
    FILE_HEADER,
    `import { z } from 'zod';`,
    '',
    schemas,
    '',
    `export const AgNodeSchema = z.discriminatedUnion('component', [`,
    `${union},`,
    `]);`,
    '',
  ].join('\n');
}

function generateIndexTs(componentNames: string[]): string {
  const nodeTypes = componentNames.map(n => `  Ag${n}Node`).join(',\n');
  const schemas = componentNames.map(n => `  Ag${n}Schema`).join(',\n');
  return [
    FILE_HEADER,
    `export type {`,
    `  AgNode,`,
    `${nodeTypes},`,
    `  AgComponentName,`,
    `} from './types.js';`,
    '',
    `export {`,
    `  AgNodeSchema,`,
    `${schemas},`,
    `} from './schema.js';`,
    '',
    `export { validate } from './validate.js';`,
    `export type { ValidateResult, ValidateSuccess, ValidateFailure } from './validate.js';`,
    '',
  ].join('\n');
}

// ─── Stale omit validation ─────────────────────────────────────────────────────

function validateOmitConfig(
  sourceFiles: ReturnType<typeof Project.prototype.getSourceFiles>
): number {
  let errors = 0;
  for (const sf of sourceFiles) {
    const parts = sf.getFilePath().split('/');
    const coreIdx = parts.lastIndexOf('core');
    if (coreIdx < 1) continue;
    const componentName = parts[coreIdx - 1];
    if (skipComponents.includes(componentName)) continue;
    const sdui = `Ag${componentName}`;
    if (!(sdui in omitConfig)) continue;

    const iface = sf.getInterface(`${componentName}Props`);
    if (!iface) {
      console.warn(`WARN: no ${componentName}Props — skipping stale check for ${sdui}`);
      continue;
    }

    const propByName = new Map(iface.getType().getProperties().map(sym => [sym.getName(), sym]));

    for (const omittedProp of omitConfig[sdui]) {
      if (!propByName.has(omittedProp)) {
        console.error(
          `ERROR: omitConfig lists '${omittedProp}' in ${sdui} ` +
          `but ${componentName}Props no longer has that property. Remove it.`
        );
        errors++;
        continue;
      }
      if (isFunctionSymbol(propByName.get(omittedProp)!)) {
        console.error(
          `ERROR: omitConfig lists '${omittedProp}' in ${sdui} but it is function-typed. ` +
          `Remove it from omitConfig (add to actionAliasMap if it needs a string alias).`
        );
        errors++;
      }
    }
  }
  return errors;
}

// ─── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  const project = new Project({
    tsConfigFilePath: resolve(ROOT, 'v2/lib/tsconfig.json'),
    skipAddingFilesFromTsConfig: true,
  });
  project.addSourceFilesAtPaths(GLOB);

  const sourceFiles = project.getSourceFiles().filter(
    sf => !sf.getFilePath().endsWith('.spec.ts')
  );

  // Fail-fast: validate omit config before generating anything
  const omitErrors = validateOmitConfig(sourceFiles);
  if (omitErrors > 0) process.exit(1);

  // Discover and process components
  const components: Array<{ name: string; props: PropInfo[] }> = [];

  for (const sf of sourceFiles) {
    const parts = sf.getFilePath().split('/');
    const coreIdx = parts.lastIndexOf('core');
    if (coreIdx < 1) continue;
    const componentName = parts[coreIdx - 1];

    if (skipComponents.includes(componentName)) continue;

    const iface = sf.getInterface(`${componentName}Props`);
    if (!iface) {
      console.warn(`WARN: no ${componentName}Props — skipping`);
      continue;
    }

    // Deduplicate: a component directory may match multiple files (shouldn't happen post-spec-filter)
    if (components.some(c => c.name === componentName)) continue;

    console.log(`Processing ${componentName}...`);
    const props = getPropsForComponent(componentName, iface);
    components.push({ name: componentName, props });
  }

  // Alphabetical order for deterministic output
  components.sort((a, b) => a.name.localeCompare(b.name));

  // Write generated files
  writeFileSync(resolve(SCHEMA_ROOT, 'src/types.ts'), generateTypesTs(components));
  writeFileSync(resolve(SCHEMA_ROOT, 'src/schema.ts'), generateSchemaTs(components));
  writeFileSync(resolve(SCHEMA_ROOT, 'src/index.ts'), generateIndexTs(components.map(c => c.name)));

  console.log(`\nGenerated ${components.length} component schemas.`);
  console.log('src/types.ts, src/schema.ts, src/index.ts updated.');
}

main().catch(err => { console.error(err); process.exit(1); });
