// AUTO-GENERATED by v2/schema/scripts/codegen.ts — do not edit by hand
// Run: npm run codegen   (from v2/schema/)
// Source: v2/lib/src/components/*/core/_*.ts

import { Project, type Type, type InterfaceDeclaration, type Symbol as MorphSymbol } from 'ts-morph';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { writeFileSync } from 'fs';
import { omitConfig, actionAliasMap, actionPayloadMap, typeOverrides, skipComponents, rendererSlotConfig, vueDefaultImportComponents, reactPropRenames, rendererPrimitives, noUndefinedProps, type RendererSlot, type RendererPrimitive } from './codegen.config.js';

// scripts/ -> schema/ -> v2/ -> agnosticui/
export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
export const SCHEMA_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const GLOB = `${ROOT}/v2/lib/src/components/*/core/_*.ts`;

const FILE_HEADER = `// AUTO-GENERATED by v2/schema/scripts/codegen.ts — do not edit by hand
// Run: npm run codegen   (from v2/schema/)
// Source: v2/lib/src/components/*/core/_*.ts
`;

// ─── Type mapping ──────────────────────────────────────────────────────────────

type PropMapping = { tsType: string; zodExpr: string };

function mapType(type: Type): PropMapping | null {
  // Strip undefined/null (optional / nullable props)
  const t = type.getNonNullableType();

  if (t.isBoolean()) return { tsType: 'boolean', zodExpr: 'z.boolean()' };
  if (t.isString()) return { tsType: 'string', zodExpr: 'z.string()' };
  if (t.isNumber()) return { tsType: 'number', zodExpr: 'z.number()' };

  // Array types: only handle string[] and number[] for SDUI
  if (t.isArray()) {
    const el = t.getArrayElementType();
    if (!el) return null;
    const elMap = mapType(el);
    if (!elMap) return null;
    return { tsType: `${elMap.tsType}[]`, zodExpr: `z.array(${elMap.zodExpr})` };
  }

  // Union types
  if (t.isUnion()) {
    const members = t.getUnionTypes().filter(m =>
      !m.isUndefined() &&
      !m.isNull() &&
      !m.isBoolean() &&
      !m.isBooleanLiteral() &&
      !(m.isStringLiteral() && m.getLiteralValue() === '')
    );

    if (members.length === 0) return null;
    if (members.length === 1) return mapType(members[0]);

    // All string literals → z.enum
    if (members.every(m => m.isStringLiteral())) {
      const values = members.map(m => m.getLiteralValue() as string);
      const tsType = values.map(v => `'${v}'`).join(' | ');
      const zodExpr = `z.enum([${values.map(v => `'${v}'`).join(', ')}])`;
      return { tsType, zodExpr };
    }

    // string | number (or literals of each)
    const allPrimitive = members.every(m =>
      m.isString() || m.isNumber() || m.isStringLiteral() || m.isNumberLiteral()
    );
    if (allPrimitive) {
      const hasStr = members.some(m => m.isString() || m.isStringLiteral());
      const hasNum = members.some(m => m.isNumber() || m.isNumberLiteral());
      if (hasStr && hasNum) {
        return { tsType: 'string | number', zodExpr: 'z.union([z.string(), z.number()])' };
      }
    }

    // Fallback: if a string member is present (e.g. string | Date), use string
    if (members.some(m => m.isString() || m.isStringLiteral())) {
      return { tsType: 'string', zodExpr: 'z.string()' };
    }

    return null;
  }

  // Single string literal
  if (t.isStringLiteral()) {
    const v = t.getLiteralValue() as string;
    if (v === '') return null;
    return { tsType: `'${v}'`, zodExpr: `z.literal('${v}')` };
  }

  // Single number literal
  if (t.isNumberLiteral()) {
    const v = t.getLiteralValue() as number;
    return { tsType: `${v}`, zodExpr: `z.literal(${v})` };
  }

  return null; // objects, complex types — skip
}

// ─── Prop extraction ───────────────────────────────────────────────────────────

export interface PropInfo {
  name: string;
  tsType: string;
  zodExpr: string;
}

export interface ActionPropInfo {
  sourceName: string;  // e.g., 'onClick', 'onToggleChange'
  alias: string;       // e.g., 'on_click', 'on_change'
  litEvent: string;    // e.g., 'click', 'toggle-change'
}

export function isFunctionSymbol(sym: MorphSymbol): boolean {
  const decl = sym.getValueDeclaration();
  if (!decl) return false;
  return decl.getType().getNonNullableType().getCallSignatures().length > 0;
}

// Convert PascalCase component name to kebab-case slug (e.g. 'ButtonFx' -> 'button-fx')
export function toKebab(name: string): string {
  return name.replace(/([A-Z])/g, (_, c) => '-' + c.toLowerCase()).replace(/^-/, '');
}

// Convert function prop name to Lit event name (e.g. 'onToggleChange' → 'toggle-change')
function toLitEvent(propName: string): string {
  return toKebab(propName.slice(2)); // remove 'on', then kebab-case
}

export function getComponentInfo(
  componentName: string,
  iface: InterfaceDeclaration,
): { props: PropInfo[]; actions: ActionPropInfo[] } {
  const sdui = `Ag${componentName}`;
  const manualOmit = new Set(omitConfig[sdui] ?? []);
  const overrides = (typeOverrides as Record<string, Record<string, PropMapping>>)[sdui] ?? {};
  const seenAliases = new Set<string>();
  const props: PropInfo[] = [];
  const actions: ActionPropInfo[] = [];

  for (const sym of iface.getType().getProperties()) {
    const propName = sym.getName();

    if (manualOmit.has(propName)) continue;

    const decl = sym.getValueDeclaration();
    if (!decl) continue;

    if (isFunctionSymbol(sym)) {
      const alias = actionAliasMap[propName];
      if (alias && !seenAliases.has(alias)) {
        seenAliases.add(alias);
        props.push({ name: alias, tsType: 'string', zodExpr: 'z.string()' });
      }
      if (alias) {
        actions.push({ sourceName: propName, alias, litEvent: toLitEvent(propName) });
      }
      continue;
    }

    if (overrides[propName]) {
      props.push({ name: propName, ...overrides[propName] });
      continue;
    }

    const mapping = mapType(decl.getType());
    if (!mapping) {
      console.warn(`  WARN: cannot map type for ${sdui}.${propName} — prop skipped`);
      continue;
    }

    props.push({ name: propName, tsType: mapping.tsType, zodExpr: mapping.zodExpr });
  }

  return { props, actions };
}

// Legacy wrapper for schema generation (returns only props)
function getPropsForComponent(componentName: string, iface: InterfaceDeclaration): PropInfo[] {
  return getComponentInfo(componentName, iface).props;
}

// ─── Code generators ──────────────────────────────────────────────────────────

function quoteName(name: string): string {
  return /[^a-zA-Z0-9_$]/.test(name) ? `'${name}'` : name;
}

function generateNodeInterface(componentName: string, props: PropInfo[]): string {
  const sdui = `Ag${componentName}`;
  const lines = [
    `export interface ${sdui}Node {`,
    `  id: string;`,
    `  component: '${sdui}';`,
  ];
  for (const p of props) {
    lines.push(`  ${quoteName(p.name)}?: ${p.tsType};`);
  }
  lines.push(`  children?: string[];`);
  lines.push(`}`);
  return lines.join('\n');
}

function generateZodSchema(componentName: string, props: PropInfo[]): string {
  const sdui = `Ag${componentName}`;
  const lines = [
    `export const ${sdui}Schema = z.object({`,
    `  id: z.string(),`,
    `  component: z.literal('${sdui}'),`,
  ];
  for (const p of props) {
    lines.push(`  ${quoteName(p.name)}: ${p.zodExpr}.optional(),`);
  }
  lines.push(`  children: z.array(z.string()).optional(),`);
  lines.push(`});`);
  return lines.join('\n');
}

export function generateTypesTs(
  components: Array<{ name: string; props: PropInfo[] }>,
  primitives: RendererPrimitive[] = rendererPrimitives,
): string {
  const interfaces = components.map(c => generateNodeInterface(c.name, c.props)).join('\n\n');
  const allMembers = [
    ...components.map(c => `  | Ag${c.name}Node`),
    ...primitives.map(p => `  | Ag${p.name}Node`),
  ].join('\n');
  const parts: string[] = [FILE_HEADER, interfaces];
  if (primitives.length > 0) {
    parts.push(primitives.map(p => p.typesBlock).join('\n\n'));
  }
  parts.push('');
  parts.push(`export type AgNode =`);
  parts.push(`${allMembers};`);
  parts.push('');
  parts.push(`export type AgComponentName = AgNode['component'];`);
  parts.push('');
  return parts.join('\n');
}

export function generateSchemaTs(
  components: Array<{ name: string; props: PropInfo[] }>,
  primitives: RendererPrimitive[] = rendererPrimitives,
): string {
  const schemas = components.map(c => generateZodSchema(c.name, c.props)).join('\n\n');
  const allUnionMembers = [
    ...components.map(c => `  Ag${c.name}Schema`),
    ...primitives.map(p => `  Ag${p.name}Schema`),
  ].join(',\n');
  const parts: string[] = [FILE_HEADER, `import { z } from 'zod';`, '', schemas];
  if (primitives.length > 0) {
    parts.push('');
    parts.push(primitives.map(p => p.schemaBlock).join('\n\n'));
  }
  parts.push('');
  parts.push(`export const AgNodeSchema = z.discriminatedUnion('component', [`);
  parts.push(`${allUnionMembers},`);
  parts.push(`]);`);
  parts.push('');
  return parts.join('\n');
}

export function generateIndexTs(
  componentNames: string[],
  primitives: RendererPrimitive[] = rendererPrimitives,
): string {
  const compNodeTypes = componentNames.map(n => `  Ag${n}Node`).join(',\n');
  const primNodeTypes = primitives.map(p => `  Ag${p.name}Node`).join(',\n');
  const nodeTypes = primNodeTypes ? compNodeTypes + ',\n' + primNodeTypes : compNodeTypes;
  const compSchemas = componentNames.map(n => `  Ag${n}Schema`).join(',\n');
  const primSchemas = primitives.map(p => `  Ag${p.name}Schema`).join(',\n');
  const schemas = primSchemas ? compSchemas + ',\n' + primSchemas : compSchemas;
  return [
    FILE_HEADER,
    `export type {`,
    `  AgNode,`,
    `${nodeTypes},`,
    `  AgComponentName,`,
    `} from './types.js';`,
    '',
    `export {`,
    `  AgNodeSchema,`,
    `${schemas},`,
    `} from './schema.js';`,
    '',
    `export { validate } from './validate.js';`,
    `export type { ValidateResult, ValidateSuccess, ValidateFailure } from './validate.js';`,
    '',
  ].join('\n');
}

// ─── Renderer generators ───────────────────────────────────────────────────────

export interface ComponentData {
  name: string;
  props: PropInfo[];
  actions: ActionPropInfo[];
  slotType: RendererSlot;
}

function litDefault(tsType: string): string {
  if (tsType === 'boolean') return ' ?? false';
  if (tsType === 'number') return ' ?? 0';
  return " ?? ''";
}

function generateReactCase(c: ComponentData): string {
  const sdui = `Ag${c.name}`;
  const wrapper = `React${c.name}`;
  const slug = toKebab(c.name);
  const directProps = c.props.filter(
    p => !p.name.startsWith('on_') && p.name !== 'children'
      && !(c.slotType === 'label-child' && p.name === 'label'),
  );
  const lines: string[] = [];
  lines.push(`    case '${sdui}':`);
  lines.push(`      return (`);

  const propLines: string[] = [];
  propLines.push(`        <${wrapper}`);
  propLines.push(`          key={node.id}`);
  const noUndef = new Set(noUndefinedProps[sdui] ?? []);
  for (const p of directProps) {
    const jsxAttr = reactPropRenames[p.name] ?? p.name;
    if (noUndef.has(p.name)) {
      propLines.push(`          {...(node.${quoteName(p.name)} !== undefined ? { ${jsxAttr}: node.${quoteName(p.name)} } : {})}`);
    } else {
      propLines.push(`          ${jsxAttr}={node.${quoteName(p.name)}}`);
    }
  }
  for (const a of c.actions) {
    const payloadExpr = actionPayloadMap[a.sourceName];
    if (payloadExpr) {
      propLines.push(`          ${a.sourceName}={(e) => dispatch(node.${quoteName(a.alias)}, actions, ${payloadExpr})}`);
    } else {
      propLines.push(`          ${a.sourceName}={() => dispatch(node.${quoteName(a.alias)}, actions)}`);
    }
  }

  if (c.slotType === 'none') {
    propLines[propLines.length - 1] += ' />';
    lines.push(...propLines);
    lines.push(`      );`);
  } else if (c.slotType === 'label-child') {
    propLines.push(`        >`);
    lines.push(...propLines);
    lines.push(`          {node.children?.length ? renderChildren(node.children) : ((node as { label?: string }).label ?? '')}`);
    lines.push(`        </${wrapper}>`);
    lines.push(`      );`);
  } else {
    // children
    propLines.push(`        >`);
    lines.push(...propLines);
    lines.push(`          {renderChildren(node.children)}`);
    lines.push(`        </${wrapper}>`);
    lines.push(`      );`);
  }

  // Suppress unused-import warnings when a component has no import path yet
  void slug;
  return lines.join('\n');
}

export function generateReactRenderer(
  components: ComponentData[],
  primitives: RendererPrimitive[] = rendererPrimitives,
): string {
  const imports = components.map(c => {
    const slug = toKebab(c.name);
    return `import { React${c.name} } from 'agnosticui-core/${slug}/react';`;
  }).join('\n');

  const compCases = components.map(c => generateReactCase(c)).join('\n\n');
  const cases = primitives.length > 0
    ? compCases + '\n\n' + primitives.map(p => p.reactCase).join('\n\n')
    : compCases;

  return [
    FILE_HEADER,
    `import * as React from 'react';`,
    `import type { AgNode } from '@agnosticui/schema';`,
    imports,
    '',
    `type Actions = Record<string, (payload?: unknown) => void>;`,
    '',
    `export interface AgDynamicRendererProps {`,
    `  nodes: AgNode[];`,
    `  actions?: Actions;`,
    `}`,
    '',
    `/**`,
    ` * Create an action dispatcher bound to a given actions map.`,
    ` *`,
    ` * This is the XSS boundary: only aliases present in the map are called;`,
    ` * unknown aliases are silently ignored. No eval(), no dynamic code execution.`,
    ` */`,
    `export function createDispatcher(actions: Actions) {`,
    `  return (alias?: string, payload?: unknown): void => {`,
    `    if (alias) actions[alias]?.(payload);`,
    `  };`,
    `}`,
    '',
    `function dispatch(alias: string | undefined, actions: Actions, payload?: unknown): void {`,
    `  if (alias) actions[alias]?.(payload);`,
    `}`,
    '',
    `function renderNode(`,
    `  node: AgNode,`,
    `  nodeMap: Map<string, AgNode>,`,
    `  actions: Actions,`,
    `): React.ReactNode {`,
    `  const renderChildren = (childIds?: string[]): React.ReactNode[] =>`,
    `    (childIds ?? [])`,
    `      .map(id => {`,
    `        const child = nodeMap.get(id);`,
    `        return child ? renderNode(child, nodeMap, actions) : null;`,
    `      })`,
    `      .filter((n): n is React.ReactNode => n !== null);`,
    '',
    `  switch (node.component) {`,
    cases,
    '',
    `    default:`,
    `      return null;`,
    `  }`,
    `}`,
    '',
    `/**`,
    ` * AgDynamicRenderer (React)`,
    ` *`,
    ` * Consumes a flat array of AgNode objects and renders them using the`,
    ` * AgnosticUI React wrapper components. Nodes not referenced as children`,
    ` * by any other node are treated as roots.`,
    ` *`,
    ` * Actions are routed through a whitelist map — unknown aliases are`,
    ` * silently ignored, providing an XSS boundary.`,
    ` */`,
    `export function AgDynamicRenderer({ nodes, actions = {} }: AgDynamicRendererProps): React.ReactElement {`,
    `  const nodeMap = new Map(nodes.map(n => [n.id, n]));`,
    `  const childIds = new Set(nodes.flatMap(n => n.children ?? []));`,
    `  const rootNodes = nodes.filter(n => !childIds.has(n.id));`,
    '',
    `  return (`,
    `    <>`,
    `      {rootNodes.map(node => renderNode(node, nodeMap, actions))}`,
    `    </>`,
    `  );`,
    `}`,
    '',
  ].join('\n');
}

function generateVueCase(c: ComponentData): string {
  const sdui = `Ag${c.name}`;
  const wrapper = `Vue${c.name}`;
  const directProps = c.props.filter(
    p => !p.name.startsWith('on_') && p.name !== 'children'
      && !(c.slotType === 'label-child' && p.name === 'label'),
  );
  const lines: string[] = [];
  lines.push(`    case '${sdui}':`);

  const propsObj: string[] = [];
  for (const p of directProps) {
    propsObj.push(`        ${p.name}: node.${quoteName(p.name)},`);
  }
  for (const a of c.actions) {
    const payloadExpr = actionPayloadMap[a.sourceName];
    if (payloadExpr) {
      propsObj.push(`        ${a.sourceName}: (e: Event) => doDispatch(node.${quoteName(a.alias)}, actions, ${payloadExpr}),`);
    } else {
      propsObj.push(`        ${a.sourceName}: () => doDispatch(node.${quoteName(a.alias)}, actions),`);
    }
  }

  if (c.slotType === 'none') {
    lines.push(`      return h(`);
    lines.push(`        ${wrapper},`);
    lines.push(`        {`);
    lines.push(...propsObj);
    lines.push(`        },`);
    lines.push(`      );`);
  } else if (c.slotType === 'label-child') {
    lines.push(`      return h(`);
    lines.push(`        ${wrapper},`);
    lines.push(`        {`);
    lines.push(...propsObj);
    lines.push(`        },`);
    lines.push(`        {`);
    lines.push(`          default: () =>`);
    lines.push(`            node.children?.length`);
    lines.push(`              ? renderChildren(node.children)`);
    lines.push(`              : ((node as { label?: string }).label ?? ''),`);
    lines.push(`        },`);
    lines.push(`      );`);
  } else {
    // children
    lines.push(`      return h(`);
    lines.push(`        ${wrapper},`);
    lines.push(`        {`);
    lines.push(...propsObj);
    lines.push(`        },`);
    lines.push(`        { default: () => renderChildren(node.children) },`);
    lines.push(`      );`);
  }

  return lines.join('\n');
}

export function generateVueRenderer(
  components: ComponentData[],
  primitives: RendererPrimitive[] = rendererPrimitives,
): string {
  const defaultSet = new Set(vueDefaultImportComponents);
  const imports = components.map(c => {
    const slug = toKebab(c.name);
    if (defaultSet.has(c.name)) {
      // This component's vue export resolves to the compiled .vue file directly (default only)
      return `import Vue${c.name} from 'agnosticui-core/${slug}/vue';`;
    }
    return `import { Vue${c.name} } from 'agnosticui-core/${slug}/vue';`;
  }).join('\n');

  const compCases = components.map(c => generateVueCase(c)).join('\n\n');
  const cases = primitives.length > 0
    ? compCases + '\n\n' + primitives.map(p => p.vueCase).join('\n\n')
    : compCases;

  return [
    FILE_HEADER,
    `import { defineComponent, h, type PropType, type VNode } from 'vue';`,
    `import type { AgNode } from '@agnosticui/schema';`,
    imports,
    '',
    `type Actions = Record<string, (payload?: unknown) => void>;`,
    '',
    `/**`,
    ` * Create an action dispatcher bound to a given actions map.`,
    ` *`,
    ` * This is the XSS boundary: only aliases present in the map are called;`,
    ` * unknown aliases are silently ignored. No eval(), no dynamic code execution.`,
    ` */`,
    `export function createDispatcher(actions: Actions) {`,
    `  return (alias?: string, payload?: unknown): void => {`,
    `    if (alias) actions[alias]?.(payload);`,
    `  };`,
    `}`,
    '',
    `function doDispatch(alias: string | undefined, actions: Actions, payload?: unknown): void {`,
    `  if (alias) actions[alias]?.(payload);`,
    `}`,
    '',
    `function renderNode(`,
    `  node: AgNode,`,
    `  nodeMap: Map<string, AgNode>,`,
    `  actions: Actions,`,
    `): VNode | null {`,
    `  const renderChildren = (childIds?: string[]): (VNode | null)[] =>`,
    `    (childIds ?? []).map(id => {`,
    `      const child = nodeMap.get(id);`,
    `      return child ? renderNode(child, nodeMap, actions) : null;`,
    `    });`,
    '',
    `  switch (node.component) {`,
    cases,
    '',
    `    default:`,
    `      return null;`,
    `  }`,
    `}`,
    '',
    `/**`,
    ` * AgDynamicRenderer (Vue)`,
    ` *`,
    ` * Consumes a flat array of AgNode objects and renders them using the`,
    ` * AgnosticUI Vue wrapper components. Nodes not referenced as children`,
    ` * by any other node are treated as roots.`,
    ` *`,
    ` * Actions are routed through a whitelist map — unknown aliases are`,
    ` * silently ignored, providing an XSS boundary.`,
    ` */`,
    `export const AgDynamicRenderer = defineComponent({`,
    `  name: 'AgDynamicRenderer',`,
    '',
    `  props: {`,
    `    nodes: {`,
    `      type: Array as PropType<AgNode[]>,`,
    `      required: true,`,
    `    },`,
    `    actions: {`,
    `      type: Object as PropType<Actions>,`,
    `      default: () => ({}),`,
    `    },`,
    `  },`,
    '',
    `  setup(props) {`,
    `    return () => {`,
    `      const nodeMap = new Map(props.nodes.map(n => [n.id, n]));`,
    `      const childIds = new Set(props.nodes.flatMap(n => n.children ?? []));`,
    `      const rootNodes = props.nodes.filter(n => !childIds.has(n.id));`,
    `      return rootNodes.map(node => renderNode(node, nodeMap, props.actions));`,
    `    };`,
    `  },`,
    `});`,
    '',
  ].join('\n');
}

function generateLitCase(c: ComponentData): string {
  const sdui = `Ag${c.name}`;
  const tag = `ag-${toKebab(c.name)}`;
  const directProps = c.props.filter(
    p => !p.name.startsWith('on_') && p.name !== 'children'
      && !(c.slotType === 'label-child' && p.name === 'label'),
  );

  const litNoUndef = new Set(noUndefinedProps[sdui] ?? []);
  const attrLines = directProps.map(p => {
    if (litNoUndef.has(p.name)) {
      return `        .${p.name}=\${node.${quoteName(p.name)} ?? nothing}`;
    }
    const def = litDefault(p.tsType);
    return `        .${p.name}=\${node.${quoteName(p.name)}${def}}`;
  });
  for (const a of c.actions) {
    const payloadExpr = actionPayloadMap[a.sourceName];
    if (payloadExpr) {
      attrLines.push(`        @${a.litEvent}=\${(e: Event) => doDispatch(node.${a.alias}, actions, ${payloadExpr})}`);
    } else {
      attrLines.push(`        @${a.litEvent}=\${() => doDispatch(node.${a.alias}, actions)}`);
    }
  }

  const attrs = attrLines.length > 0 ? '\n' + attrLines.join('\n') + '\n      ' : '';

  let innerContent: string;
  if (c.slotType === 'label-child') {
    innerContent = `\${node.children?.length ? renderChildren(node.children) : ((node as { label?: string }).label ?? '')}`;
  } else if (c.slotType === 'children') {
    innerContent = `\${renderChildren(node.children)}`;
  } else {
    innerContent = '';
  }

  return [
    `    case '${sdui}':`,
    `      return html\`<${tag}${attrs}>${innerContent}</${tag}>\`;`,
  ].join('\n');
}

export function generateLitRenderer(
  components: ComponentData[],
  primitives: RendererPrimitive[] = rendererPrimitives,
): string {
  const coreImports = components.map(c => {
    const slug = toKebab(c.name);
    return `import 'agnosticui-core/${slug}';`;
  }).join('\n');

  const compCases = components.map(c => generateLitCase(c)).join('\n\n');
  const cases = primitives.length > 0
    ? compCases + '\n\n' + primitives.map(p => p.litCase).join('\n\n')
    : compCases;

  return [
    FILE_HEADER,
    `import { LitElement, html, nothing, type TemplateResult } from 'lit';`,
    `import { property } from 'lit/decorators.js';`,
    `import type { AgNode } from '@agnosticui/schema';`,
    '',
    `// Register AgnosticUI core custom elements`,
    coreImports,
    '',
    `type Actions = Record<string, (payload?: unknown) => void>;`,
    '',
    `/**`,
    ` * Create an action dispatcher bound to a given actions map.`,
    ` *`,
    ` * This is the XSS boundary: only aliases present in the map are called;`,
    ` * unknown aliases are silently ignored. No eval(), no dynamic code execution.`,
    ` */`,
    `export function createDispatcher(actions: Actions) {`,
    `  return (alias?: string, payload?: unknown): void => {`,
    `    if (alias) actions[alias]?.(payload);`,
    `  };`,
    `}`,
    '',
    `function doDispatch(alias: string | undefined, actions: Actions, payload?: unknown): void {`,
    `  if (alias) actions[alias]?.(payload);`,
    `}`,
    '',
    `function renderNode(`,
    `  node: AgNode,`,
    `  nodeMap: Map<string, AgNode>,`,
    `  actions: Actions,`,
    `): TemplateResult | typeof nothing {`,
    `  const renderChildren = (childIds?: string[]) =>`,
    `    (childIds ?? []).map(id => {`,
    `      const child = nodeMap.get(id);`,
    `      return child ? renderNode(child, nodeMap, actions) : nothing;`,
    `    });`,
    '',
    `  switch (node.component) {`,
    cases,
    '',
    `    default:`,
    `      return nothing;`,
    `  }`,
    `}`,
    '',
    `/**`,
    ` * AgDynamicRenderer (Lit)`,
    ` *`,
    ` * A custom element that consumes a flat array of AgNode objects and renders`,
    ` * them using the AgnosticUI core web components directly. Renders into light`,
    ` * DOM so it works transparently inside any framework.`,
    ` *`,
    ` * Nodes not referenced as children by any other node are treated as roots.`,
    ` * Actions are routed through a whitelist map — unknown aliases are silently`,
    ` * ignored, providing an XSS boundary.`,
    ` *`,
    ` * @example`,
    ` * <ag-dynamic-renderer></ag-dynamic-renderer>`,
    ` *`,
    ` * el.nodes = [{ id: 'btn-1', component: 'AgButton', label: 'Click', on_click: 'SUBMIT' }];`,
    ` * el.actions = { SUBMIT: () => console.log('submitted') };`,
    ` */`,
    `export class AgDynamicRenderer extends LitElement {`,
    `  // Render into light DOM so child elements are accessible to parent frameworks`,
    `  override createRenderRoot() {`,
    `    return this;`,
    `  }`,
    '',
    `  @property({ type: Array }) nodes: AgNode[] = [];`,
    `  @property({ type: Object }) actions: Actions = {};`,
    '',
    `  override render() {`,
    `    const nodeMap = new Map(this.nodes.map(n => [n.id, n]));`,
    `    const childIds = new Set(this.nodes.flatMap(n => n.children ?? []));`,
    `    const rootNodes = this.nodes.filter(n => !childIds.has(n.id));`,
    `    return html\`\${rootNodes.map(node => renderNode(node, nodeMap, this.actions))}\`;`,
    `  }`,
    `}`,
    '',
    `if (!customElements.get('ag-dynamic-renderer')) {`,
    `  customElements.define('ag-dynamic-renderer', AgDynamicRenderer);`,
    `}`,
    '',
    `declare global {`,
    `  interface HTMLElementTagNameMap {`,
    `    'ag-dynamic-renderer': AgDynamicRenderer;`,
    `  }`,
    `}`,
    '',
  ].join('\n');
}

// ─── Stale omit validation ─────────────────────────────────────────────────────

export function validateOmitConfig(
  sourceFiles: ReturnType<typeof Project.prototype.getSourceFiles>
): number {
  let errors = 0;
  for (const sf of sourceFiles) {
    const parts = sf.getFilePath().split('/');
    const coreIdx = parts.lastIndexOf('core');
    if (coreIdx < 1) continue;
    const componentName = parts[coreIdx - 1];
    if (skipComponents.includes(componentName)) continue;
    const sdui = `Ag${componentName}`;
    if (!(sdui in omitConfig)) continue;

    const iface = sf.getInterface(`${componentName}Props`);
    if (!iface) {
      console.warn(`WARN: no ${componentName}Props — skipping stale check for ${sdui}`);
      continue;
    }

    const propByName = new Map(iface.getType().getProperties().map(sym => [sym.getName(), sym]));

    for (const omittedProp of omitConfig[sdui]) {
      if (!propByName.has(omittedProp)) {
        console.error(
          `ERROR: omitConfig lists '${omittedProp}' in ${sdui} ` +
          `but ${componentName}Props no longer has that property. Remove it.`
        );
        errors++;
        continue;
      }
      if (isFunctionSymbol(propByName.get(omittedProp)!)) {
        console.error(
          `ERROR: omitConfig lists '${omittedProp}' in ${sdui} but it is function-typed. ` +
          `Remove it from omitConfig (add to actionAliasMap if it needs a string alias).`
        );
        errors++;
      }
    }
  }
  return errors;
}

// ─── Main ──────────────────────────────────────────────────────────────────────

/**
 * Discover and process all components from the ts-morph project.
 * Returns sorted ComponentData[] ready for code generation.
 * Exits with code 1 if omitConfig has stale entries.
 */
export async function buildComponents(): Promise<ComponentData[]> {
  const project = new Project({
    tsConfigFilePath: resolve(ROOT, 'v2/lib/tsconfig.json'),
    skipAddingFilesFromTsConfig: true,
  });
  project.addSourceFilesAtPaths(GLOB);

  const sourceFiles = project.getSourceFiles().filter(
    sf => !sf.getFilePath().endsWith('.spec.ts')
  );

  const omitErrors = validateOmitConfig(sourceFiles);
  if (omitErrors > 0) process.exit(1);

  const components: ComponentData[] = [];

  for (const sf of sourceFiles) {
    const parts = sf.getFilePath().split('/');
    const coreIdx = parts.lastIndexOf('core');
    if (coreIdx < 1) continue;
    const componentName = parts[coreIdx - 1];

    if (skipComponents.includes(componentName)) continue;

    const iface = sf.getInterface(`${componentName}Props`);
    if (!iface) {
      console.warn(`WARN: no ${componentName}Props — skipping`);
      continue;
    }

    if (components.some(c => c.name === componentName)) continue;

    console.log(`Processing ${componentName}...`);
    const { props, actions } = getComponentInfo(componentName, iface);
    const sdui = `Ag${componentName}`;
    const slotType: RendererSlot = rendererSlotConfig[sdui] ?? 'none';
    components.push({ name: componentName, props, actions, slotType });
  }

  components.sort((a, b) => a.name.localeCompare(b.name));
  return components;
}

async function main() {
  const components = await buildComponents();

  // Write schema files
  writeFileSync(resolve(SCHEMA_ROOT, 'src/types.ts'), generateTypesTs(components));
  writeFileSync(resolve(SCHEMA_ROOT, 'src/schema.ts'), generateSchemaTs(components));
  writeFileSync(resolve(SCHEMA_ROOT, 'src/index.ts'), generateIndexTs(components.map(c => c.name)));

  // Write renderer files
  const RENDERERS_ROOT = resolve(ROOT, 'v2/renderers');
  writeFileSync(
    resolve(RENDERERS_ROOT, 'react/src/AgDynamicRenderer.tsx'),
    generateReactRenderer(components),
  );
  writeFileSync(
    resolve(RENDERERS_ROOT, 'vue/src/AgDynamicRenderer.ts'),
    generateVueRenderer(components),
  );
  writeFileSync(
    resolve(RENDERERS_ROOT, 'lit/src/AgDynamicRenderer.ts'),
    generateLitRenderer(components),
  );

  console.log(`\nGenerated ${components.length} component schemas.`);
  console.log('src/types.ts, src/schema.ts, src/index.ts updated.');
  console.log('v2/renderers/react/src/AgDynamicRenderer.tsx updated.');
  console.log('v2/renderers/vue/src/AgDynamicRenderer.ts updated.');
  console.log('v2/renderers/lit/src/AgDynamicRenderer.ts updated.');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch(err => { console.error(err); process.exit(1); });
}
