
title: Card Stacked
context:
    title: Stacked Card Title
    text: Lorem ipsum yoyoyo dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.
    buttonCopy: Click me
    cardClasses: card card-stacked
