title: "Card"
collated: true
context:
  description: Note that the AgnosticUI Card component is a very thin layer and only supplies the card as a shell for you to project your own content (and thus HTML and CSS) onto. For example, this card is essentially a row-based horizontal layout as the image is on the left and the body of the card (where you're reading now!) is on the right. But that aspect of this layout is demo code. Some things are offered by the card component though — if the viewport narrows enough, for example, it becomes a stacked card. If you want the card always be stacked, see the example below which applies the appropriate stacked card class.
variants:
  - name: Card
    context:
      title: Card
      modifier:
  - name: Card Border
    context:
      title: Card Border
      modifier: card-border
  - name: Card Rounded
    context:
      title: Card Rounded
      modifier: card-border card-rounded
  - name: Card Shadow
    context:
      title: Card Shadow
      modifier: card-shadow
  - name: Card animated 
    context:
      title: Card (animated)
      modifier: card-animated card-shadow
  - name: stacked
    context:
      title: Stacked Card Title
      text: Lorem ipsum yoyoyo dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.
      modifier: card-animated 
      buttonCopy: Click me
      cardClasses: card card-border card-stacked  mbe16
  - name: Card Success
    context:
      title: Card Success
      modifier: card-success
  - name: Card Info
    context:
      title: Card Info
      modifier: card-info
  - name: Card Warning
    context:
      title: Card Warning
      modifier: card-warning
  - name: Card Error
    context:
      title: Card Error
      modifier: card-error
