title: "Card"
collated: true
context:
  description: This card is essentially a row-based horizontal layout as the image is on the left and the body of the card (where you're reading now!) is on the right. If the viewport narrows enough though, it becomes a stacked card at that point. If you want the card to always be stacked, see the example below which applies the appropriate stacked card class.
variants:
  - name: Card
    context:
      title: Card
      modifier:
  - name: Card animated 
    context:
      title: Card (animated)
      modifier: card-animated 
