<template>
  <div>
    <div>
      <Button @click="clickHandler">
        Go
      </Button>
      <Button
        :is-bordered="true"
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        :is-capsule="true"
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        is-blank
        @click="clickHandler"
      >
        Blank
      </Button>
      <Button
        is-link
        @click="clickHandler"
      >
        Link
      </Button>
      <Button
        is-link
        :is-skinned="false"
        @click="clickHandler"
      >
        Link unskinned
      </Button>
      <Button
        is-block
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        is-block
        is-capsule
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        is-rounded
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        is-rounded
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        is-bordered
        is-rounded
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        is-capsule
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        is-circle
        is-bordered
        @click="clickHandler"
      >
        Go
      </Button>
    </div>
    <div>
      <Button
        mode="primary"
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        mode="primary"
        :is-bordered="true"
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        mode="primary"
        :is-capsule="true"
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        mode="primary"
        is-blank
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        mode="primary"
        is-block
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        mode="primary"
        is-block
        is-capsule
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        mode="primary"
        is-rounded
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        mode="primary"
        is-rounded
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        mode="primary"
        is-bordered
        is-rounded
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        mode="primary"
        is-circle
        is-bordered
        @click="clickHandler"
      >
        Go
      </Button>
    </div>
    <div>
      <Button
        mode="secondary"
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        mode="secondary"
        :is-bordered="true"
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        mode="secondary"
        :is-capsule="true"
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        mode="secondary"
        is-blank
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        mode="secondary"
        is-block
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        mode="secondary"
        is-rounded
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        mode="secondary"
        is-rounded
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        mode="secondary"
        is-bordered
        is-rounded
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        mode="secondary"
        is-circle
        is-bordered
        @click="clickHandler"
      >
        Go
      </Button>
    </div>

    <div>
      <Button
        :is-disabled="true"
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        mode="primary"
        is-disabled
      >
        Go
      </Button>
      <Button
        mode="secondary"
        is-disabled
      >
        Go
      </Button>
    </div>
    <div>
      <Button
        size="small"
        @click="clickHandler"
      >
        Go
      </Button>
      <Button
        size="large"
        @click="clickHandler"
      >
        Go
      </Button>
      <Button :is-skinned="false">
        No Skin
      </Button>
    </div>
    <div>
      <Button css="foo bar baz">
        CSS (inspect to see 'foo bar baz')
      </Button>
    </div>
  </div>
</template>

<script>
import Button from "./Button.vue";
import { action } from "@storybook/addon-actions";

const actionsData = {
  clickHandler: action("click"),
};

export default {
  name: "ButtonsTests",
  components: { Button },
  methods: actionsData,
};
</script>
