// AUTO-GENERATED by v2/schema/scripts/codegen.ts — do not edit by hand
// Run: npm run codegen   (from v2/schema/)
// Source: v2/lib/src/components/*/core/_*.ts

import { z } from 'zod';

export const AgAccordionSchema = z.object({
  id: z.string(),
  component: z.literal('AgAccordion'),
  children: z.array(z.string()).optional(),
});

export const AgAlertSchema = z.object({
  id: z.string(),
  component: z.literal('AgAlert'),
  variant: z.enum(['default', 'primary', 'success', 'monochrome', 'warning', 'info', 'error', 'danger']).optional(),
  bordered: z.boolean().optional(),
  rounded: z.boolean().optional(),
  borderedLeft: z.boolean().optional(),
  dismissible: z.boolean().optional(),
  on_dismiss: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgAspectRatioSchema = z.object({
  id: z.string(),
  component: z.literal('AgAspectRatio'),
  width: z.number().optional(),
  height: z.number().optional(),
  maxWidth: z.number().optional(),
  children: z.array(z.string()).optional(),
});

export const AgAvatarSchema = z.object({
  id: z.string(),
  component: z.literal('AgAvatar'),
  text: z.string().optional(),
  imgSrc: z.string().optional(),
  imgAlt: z.string().optional(),
  size: z.enum(['xs', 'sm', 'md', 'lg', 'xl']).optional(),
  shape: z.enum(['circle', 'square', 'rounded']).optional(),
  variant: z.enum(['default', 'success', 'monochrome', 'warning', 'info', 'error', 'transparent']).optional(),
  ariaLabel: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgBadgeSchema = z.object({
  id: z.string(),
  component: z.literal('AgBadge'),
  variant: z.enum(['default', 'primary', 'success', 'monochrome', 'warning', 'info', 'danger', 'neutral']).optional(),
  size: z.enum(['xs', 'sm', 'md']).optional(),
  dot: z.boolean().optional(),
  value: z.number().optional(),
  max: z.number().optional(),
  interactive: z.boolean().optional(),
  statusLabel: z.string().optional(),
  live: z.enum(['off', 'polite', 'assertive']).optional(),
  hiddenFromAT: z.boolean().optional(),
  children: z.array(z.string()).optional(),
});

export const AgBadgeFxSchema = z.object({
  id: z.string(),
  component: z.literal('AgBadgeFx'),
  variant: z.enum(['default', 'primary', 'success', 'monochrome', 'warning', 'info', 'danger', 'neutral']).optional(),
  size: z.enum(['xs', 'sm', 'md']).optional(),
  dot: z.boolean().optional(),
  value: z.number().optional(),
  max: z.number().optional(),
  interactive: z.boolean().optional(),
  statusLabel: z.string().optional(),
  live: z.enum(['off', 'polite', 'assertive']).optional(),
  hiddenFromAT: z.boolean().optional(),
  fx: z.string().optional(),
  fxSpeed: z.enum(['xs', 'sm', 'md', 'lg', 'xl']).optional(),
  fxEase: z.enum(['ease', 'ease-in', 'ease-out', 'ease-in-out', 'bounce', 'spring-sm', 'spring-md', 'spring-lg']).optional(),
  fxDisabled: z.boolean().optional(),
  children: z.array(z.string()).optional(),
});

export const AgBreadcrumbSchema = z.object({
  id: z.string(),
  component: z.literal('AgBreadcrumb'),
  type: z.enum(['default', 'slash', 'bullet', 'arrow']).optional(),
  primary: z.boolean().optional(),
  ariaLabel: z.string().optional(),
  on_click: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgButtonSchema = z.object({
  id: z.string(),
  component: z.literal('AgButton'),
  variant: z.enum(['primary', 'success', 'monochrome', 'warning', 'danger', 'secondary']).optional(),
  size: z.enum(['sm', 'md', 'lg', 'xl', 'x-sm']).optional(),
  shape: z.enum(['circle', 'square', 'rounded', 'capsule', 'rounded-square']).optional(),
  bordered: z.boolean().optional(),
  ghost: z.boolean().optional(),
  link: z.boolean().optional(),
  grouped: z.boolean().optional(),
  fullWidth: z.boolean().optional(),
  type: z.enum(['button', 'submit', 'reset']).optional(),
  disabled: z.boolean().optional(),
  loading: z.boolean().optional(),
  ariaLabel: z.string().optional(),
  on_click: z.string().optional(),
  on_toggle: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgButtonFxSchema = z.object({
  id: z.string(),
  component: z.literal('AgButtonFx'),
  variant: z.enum(['primary', 'success', 'monochrome', 'warning', 'danger', 'secondary']).optional(),
  size: z.enum(['sm', 'md', 'lg', 'xl', 'x-sm']).optional(),
  shape: z.enum(['circle', 'square', 'rounded', 'capsule', 'rounded-square']).optional(),
  bordered: z.boolean().optional(),
  ghost: z.boolean().optional(),
  link: z.boolean().optional(),
  grouped: z.boolean().optional(),
  fullWidth: z.boolean().optional(),
  type: z.enum(['button', 'submit', 'reset']).optional(),
  disabled: z.boolean().optional(),
  loading: z.boolean().optional(),
  ariaLabel: z.string().optional(),
  on_click: z.string().optional(),
  on_toggle: z.string().optional(),
  fx: z.string().optional(),
  fxSpeed: z.enum(['xs', 'sm', 'md', 'lg', 'xl']).optional(),
  fxEase: z.enum(['ease', 'ease-in', 'ease-out', 'ease-in-out', 'bounce', 'spring-sm', 'spring-md', 'spring-lg']).optional(),
  fxDisabled: z.boolean().optional(),
  children: z.array(z.string()).optional(),
});

export const AgCardSchema = z.object({
  id: z.string(),
  component: z.literal('AgCard'),
  stacked: z.boolean().optional(),
  shadow: z.boolean().optional(),
  animated: z.boolean().optional(),
  rounded: z.enum(['sm', 'md', 'lg']).optional(),
  variant: z.enum(['success', 'monochrome', 'warning', 'info', 'error']).optional(),
  hasMedia: z.boolean().optional(),
  mediaPosition: z.enum(['top', 'bottom']).optional(),
  children: z.array(z.string()).optional(),
});

export const AgCheckboxSchema = z.object({
  id: z.string(),
  component: z.literal('AgCheckbox'),
  name: z.string().optional(),
  value: z.string().optional(),
  checked: z.boolean().optional(),
  disabled: z.boolean().optional(),
  size: z.enum(['small', 'medium', 'large']).optional(),
  labelText: z.string().optional(),
  labelPosition: z.enum(['end', 'start']).optional(),
  required: z.boolean().optional(),
  invalid: z.boolean().optional(),
  errorMessage: z.string().optional(),
  helpText: z.string().optional(),
  on_click: z.string().optional(),
  on_change: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgDialogSchema = z.object({
  id: z.string(),
  component: z.literal('AgDialog'),
  open: z.boolean().optional(),
  heading: z.string().optional(),
  description: z.string().optional(),
  noCloseOnEscape: z.boolean().optional(),
  noCloseOnBackdrop: z.boolean().optional(),
  showCloseButton: z.boolean().optional(),
  drawerPosition: z.enum(['top', 'bottom', 'start', 'end']).optional(),
  on_open: z.string().optional(),
  on_close: z.string().optional(),
  on_cancel: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgDividerSchema = z.object({
  id: z.string(),
  component: z.literal('AgDivider'),
  vertical: z.boolean().optional(),
  justify: z.enum(['end', 'start', 'center']).optional(),
  size: z.enum(['default', 'small', 'large', 'xlarge']).optional(),
  variant: z.enum(['default', 'success', 'monochrome', 'warning', 'info', 'error']).optional(),
  children: z.array(z.string()).optional(),
});

export const AgDrawerSchema = z.object({
  id: z.string(),
  component: z.literal('AgDrawer'),
  open: z.boolean().optional(),
  heading: z.string().optional(),
  description: z.string().optional(),
  noCloseOnEscape: z.boolean().optional(),
  noCloseOnBackdrop: z.boolean().optional(),
  showCloseButton: z.boolean().optional(),
  position: z.enum(['top', 'bottom', 'end', 'start']).optional(),
  on_open: z.string().optional(),
  on_close: z.string().optional(),
  on_cancel: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgFieldsetSchema = z.object({
  id: z.string(),
  component: z.literal('AgFieldset'),
  legend: z.string().optional(),
  bordered: z.boolean().optional(),
  layout: z.enum(['vertical', 'horizontal']).optional(),
  legendHidden: z.boolean().optional(),
  children: z.array(z.string()).optional(),
});

export const AgHeaderSchema = z.object({
  id: z.string(),
  component: z.literal('AgHeader'),
  sticky: z.boolean().optional(),
  contentJustify: z.enum(['end', 'start', 'center', 'between', 'around']).optional(),
  children: z.array(z.string()).optional(),
});

export const AgIconSchema = z.object({
  id: z.string(),
  component: z.literal('AgIcon'),
  size: z.enum(['14', '16', '18', '20', '24', '32', '36', '40', '48', '56', '64']).optional(),
  type: z.enum(['primary', 'success', 'monochrome', 'warning', 'info', 'error', 'action']).optional(),
  noFill: z.boolean().optional(),
  children: z.array(z.string()).optional(),
});

export const AgIconButtonSchema = z.object({
  id: z.string(),
  component: z.literal('AgIconButton'),
  label: z.string().optional(),
  icon: z.string().optional(),
  unicode: z.string().optional(),
  size: z.enum(['xs', 'sm', 'md', 'lg', 'xl']).optional(),
  variant: z.enum(['primary', 'success', 'monochrome', 'warning', 'danger', 'secondary', 'ghost']).optional(),
  type: z.enum(['button', 'submit', 'reset']).optional(),
  disabled: z.boolean().optional(),
  loading: z.boolean().optional(),
  on_click: z.string().optional(),
  on_activate: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgIconButtonFxSchema = z.object({
  id: z.string(),
  component: z.literal('AgIconButtonFx'),
  label: z.string().optional(),
  icon: z.string().optional(),
  unicode: z.string().optional(),
  size: z.enum(['xs', 'sm', 'md', 'lg', 'xl']).optional(),
  variant: z.enum(['primary', 'success', 'monochrome', 'warning', 'danger', 'secondary', 'ghost']).optional(),
  type: z.enum(['button', 'submit', 'reset']).optional(),
  disabled: z.boolean().optional(),
  loading: z.boolean().optional(),
  on_click: z.string().optional(),
  on_activate: z.string().optional(),
  fx: z.string().optional(),
  fxSpeed: z.enum(['xs', 'sm', 'md', 'lg', 'xl']).optional(),
  fxEase: z.enum(['ease', 'ease-in', 'ease-out', 'ease-in-out', 'bounce', 'spring-sm', 'spring-md', 'spring-lg']).optional(),
  fxDisabled: z.boolean().optional(),
  children: z.array(z.string()).optional(),
});

export const AgInputSchema = z.object({
  id: z.string(),
  component: z.literal('AgInput'),
  label: z.string().optional(),
  labelHidden: z.boolean().optional(),
  labelPosition: z.enum(['top', 'bottom', 'end', 'start']).optional(),
  noLabel: z.boolean().optional(),
  ariaLabel: z.string().optional(),
  name: z.string().optional(),
  type: z.enum(['text', 'password', 'email', 'number', 'search', 'tel', 'url', 'date', 'datetime-local', 'month', 'time', 'week']).optional(),
  value: z.string().optional(),
  placeholder: z.string().optional(),
  rows: z.number().optional(),
  cols: z.number().optional(),
  size: z.enum(['default', 'small', 'large']).optional(),
  capsule: z.boolean().optional(),
  rounded: z.boolean().optional(),
  underlined: z.boolean().optional(),
  underlinedWithBackground: z.boolean().optional(),
  inline: z.boolean().optional(),
  required: z.boolean().optional(),
  disabled: z.boolean().optional(),
  readonly: z.boolean().optional(),
  invalid: z.boolean().optional(),
  errorMessage: z.string().optional(),
  helpText: z.string().optional(),
  on_click: z.string().optional(),
  on_change: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgIntlFormatterSchema = z.object({
  id: z.string(),
  component: z.literal('AgIntlFormatter'),
  type: z.enum(['number', 'date', 'percent', 'currency']).optional(),
  value: z.string().optional(),
  lang: z.string().optional(),
  date: z.string().optional(),
  weekday: z.enum(['narrow', 'short', 'long']).optional(),
  era: z.enum(['narrow', 'short', 'long']).optional(),
  year: z.enum(['numeric', '2-digit']).optional(),
  month: z.enum(['narrow', 'short', 'long', 'numeric', '2-digit']).optional(),
  day: z.enum(['numeric', '2-digit']).optional(),
  hour: z.enum(['numeric', '2-digit']).optional(),
  minute: z.enum(['numeric', '2-digit']).optional(),
  second: z.enum(['numeric', '2-digit']).optional(),
  timeZoneName: z.enum(['short', 'long']).optional(),
  timeZone: z.string().optional(),
  hourFormat: z.enum(['24', 'auto', '12']).optional(),
  dateStyle: z.enum(['medium', 'short', 'long', 'full']).optional(),
  timeStyle: z.enum(['medium', 'short', 'long', 'full']).optional(),
  noGrouping: z.boolean().optional(),
  currency: z.string().optional(),
  currencyDisplay: z.enum(['symbol', 'narrowSymbol', 'code', 'name']).optional(),
  minimumIntegerDigits: z.number().optional(),
  minimumFractionDigits: z.number().optional(),
  maximumFractionDigits: z.number().optional(),
  minimumSignificantDigits: z.number().optional(),
  maximumSignificantDigits: z.number().optional(),
  children: z.array(z.string()).optional(),
});

export const AgKbdSchema = z.object({
  id: z.string(),
  component: z.literal('AgKbd'),
  variant: z.enum(['default', 'primary', 'success', 'monochrome', 'warning', 'info', 'error', 'danger', 'secondary']).optional(),
  bordered: z.boolean().optional(),
  background: z.boolean().optional(),
  size: z.enum(['sm', 'md', 'lg']).optional(),
  children: z.array(z.string()).optional(),
});

export const AgLinkSchema = z.object({
  id: z.string(),
  component: z.literal('AgLink'),
  href: z.string().optional(),
  variant: z.enum(['primary', 'success', 'monochrome', 'warning', 'danger']).optional(),
  isButton: z.boolean().optional(),
  buttonSize: z.enum(['sm', 'md', 'lg', 'xl', 'x-sm']).optional(),
  buttonShape: z.enum(['circle', 'square', 'rounded', 'capsule', 'rounded-square']).optional(),
  buttonBordered: z.boolean().optional(),
  external: z.boolean().optional(),
  disabled: z.boolean().optional(),
  ariaLabel: z.string().optional(),
  on_click: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgLoaderSchema = z.object({
  id: z.string(),
  component: z.literal('AgLoader'),
  size: z.enum(['default', 'small', 'large']).optional(),
  ariaLabel: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgMarkSchema = z.object({
  id: z.string(),
  component: z.literal('AgMark'),
  variant: z.enum(['primary', 'success', 'monochrome', 'warning', 'info', 'error', 'secondary']).optional(),
  search: z.string().optional(),
  caseSensitive: z.boolean().optional(),
  matchAll: z.boolean().optional(),
  children: z.array(z.string()).optional(),
});

export const AgMessageBubbleSchema = z.object({
  id: z.string(),
  component: z.literal('AgMessageBubble'),
  from: z.enum(['me', 'them']).optional(),
  message: z.string().optional(),
  time: z.string().optional(),
  author: z.string().optional(),
  avatarUrl: z.string().optional(),
  footer: z.string().optional(),
  variant: z.enum(['default', 'success', 'monochrome', 'warning', 'info', 'danger', 'neutral']).optional(),
  children: z.array(z.string()).optional(),
});

export const AgPopoverSchema = z.object({
  id: z.string(),
  component: z.literal('AgPopover'),
  placement: z.enum(['top', 'top-start', 'top-end', 'right', 'right-start', 'right-end', 'bottom', 'bottom-start', 'bottom-end', 'left', 'left-start', 'left-end']).optional(),
  distance: z.number().optional(),
  skidding: z.number().optional(),
  arrow: z.boolean().optional(),
  disabled: z.boolean().optional(),
  triggerType: z.enum(['click', 'hover', 'focus']).optional(),
  matchTriggerWidth: z.boolean().optional(),
  showCloseButton: z.boolean().optional(),
  showHeader: z.boolean().optional(),
  closeLabel: z.string().optional(),
  trapFocus: z.boolean().optional(),
  on_show: z.string().optional(),
  on_hide: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgProgressSchema = z.object({
  id: z.string(),
  component: z.literal('AgProgress'),
  value: z.number().optional(),
  max: z.number().optional(),
  label: z.string().optional(),
  size: z.enum(['small', 'medium', 'large']).optional(),
  children: z.array(z.string()).optional(),
});

export const AgRadioSchema = z.object({
  id: z.string(),
  component: z.literal('AgRadio'),
  name: z.string().optional(),
  value: z.string().optional(),
  checked: z.boolean().optional(),
  disabled: z.boolean().optional(),
  size: z.enum(['small', 'medium', 'large']).optional(),
  theme: z.enum(['default', 'primary', 'success', 'monochrome']).optional(),
  labelText: z.string().optional(),
  labelPosition: z.enum(['end', 'start']).optional(),
  label: z.string().optional(),
  labelHidden: z.boolean().optional(),
  noLabel: z.boolean().optional(),
  required: z.boolean().optional(),
  invalid: z.boolean().optional(),
  errorMessage: z.string().optional(),
  helpText: z.string().optional(),
  on_click: z.string().optional(),
  on_change: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgRatingSchema = z.object({
  id: z.string(),
  component: z.literal('AgRating'),
  value: z.number().optional(),
  max: z.number().optional(),
  precision: z.enum(['whole', 'half']).optional(),
  readonly: z.boolean().optional(),
  allowClear: z.boolean().optional(),
  variant: z.enum(['primary', 'secondary', 'success', 'warning', 'danger']).optional(),
  size: z.enum(['sm', 'md', 'lg']).optional(),
  name: z.string().optional(),
  label: z.string().optional(),
  labelPosition: z.enum(['top', 'bottom', 'end', 'start']).optional(),
  labelHidden: z.boolean().optional(),
  noLabel: z.boolean().optional(),
  required: z.boolean().optional(),
  invalid: z.boolean().optional(),
  errorMessage: z.string().optional(),
  helpText: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgSelectSchema = z.object({
  id: z.string(),
  component: z.literal('AgSelect'),
  size: z.enum(['small', 'large']).optional(),
  multiple: z.boolean().optional(),
  disabled: z.boolean().optional(),
  name: z.string().optional(),
  multipleSize: z.number().optional(),
  label: z.string().optional(),
  labelPosition: z.enum(['top', 'bottom', 'end', 'start']).optional(),
  labelHidden: z.boolean().optional(),
  noLabel: z.boolean().optional(),
  required: z.boolean().optional(),
  invalid: z.boolean().optional(),
  errorMessage: z.string().optional(),
  helpText: z.string().optional(),
  on_click: z.string().optional(),
  on_change: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgSelectionButtonSchema = z.object({
  id: z.string(),
  component: z.literal('AgSelectionButton'),
  value: z.string().optional(),
  label: z.string().optional(),
  checked: z.boolean().optional(),
  disabled: z.boolean().optional(),
  children: z.array(z.string()).optional(),
});

export const AgSelectionButtonGroupSchema = z.object({
  id: z.string(),
  component: z.literal('AgSelectionButtonGroup'),
  type: z.enum(['radio', 'checkbox']).optional(),
  name: z.string().optional(),
  legend: z.string().optional(),
  legendHidden: z.boolean().optional(),
  theme: z.enum(['success', 'monochrome', 'warning', 'info', 'error']).optional(),
  size: z.enum(['sm', 'md', 'lg']).optional(),
  shape: z.enum(['rounded', 'capsule']).optional(),
  value: z.string().optional(),
  values: z.array(z.string()).optional(),
  disabled: z.boolean().optional(),
  required: z.boolean().optional(),
  on_change: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgSelectionCardSchema = z.object({
  id: z.string(),
  component: z.literal('AgSelectionCard'),
  value: z.string().optional(),
  label: z.string().optional(),
  checked: z.boolean().optional(),
  disabled: z.boolean().optional(),
  children: z.array(z.string()).optional(),
});

export const AgSelectionCardGroupSchema = z.object({
  id: z.string(),
  component: z.literal('AgSelectionCardGroup'),
  type: z.enum(['radio', 'checkbox']).optional(),
  name: z.string().optional(),
  legend: z.string().optional(),
  legendHidden: z.boolean().optional(),
  theme: z.enum(['success', 'monochrome', 'warning', 'info', 'error']).optional(),
  value: z.string().optional(),
  values: z.array(z.string()).optional(),
  disabled: z.boolean().optional(),
  required: z.boolean().optional(),
  on_change: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgSpinnerSchema = z.object({
  id: z.string(),
  component: z.literal('AgSpinner'),
  size: z.enum(['default', 'small', 'large', 'xlarge']).optional(),
  ariaLabel: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgTabsSchema = z.object({
  id: z.string(),
  component: z.literal('AgTabs'),
  activation: z.enum(['manual', 'automatic']).optional(),
  activeTab: z.number().optional(),
  orientation: z.enum(['vertical', 'horizontal']).optional(),
  ariaLabel: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgTagSchema = z.object({
  id: z.string(),
  component: z.literal('AgTag'),
  variant: z.enum(['primary', 'success', 'monochrome', 'warning', 'info', 'error']).optional(),
  shape: z.enum(['circle', 'pill', 'round']).optional(),
  uppercase: z.boolean().optional(),
  removable: z.boolean().optional(),
  on_remove: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgToggleSchema = z.object({
  id: z.string(),
  component: z.literal('AgToggle'),
  label: z.string().optional(),
  labelPosition: z.enum(['top', 'bottom', 'end', 'start']).optional(),
  labelHidden: z.boolean().optional(),
  noLabel: z.boolean().optional(),
  checked: z.boolean().optional(),
  size: z.enum(['xs', 'sm', 'md', 'lg', 'xl']).optional(),
  variant: z.enum(['default', 'success', 'monochrome', 'warning', 'danger']).optional(),
  disabled: z.boolean().optional(),
  readonly: z.boolean().optional(),
  required: z.boolean().optional(),
  invalid: z.boolean().optional(),
  errorMessage: z.string().optional(),
  helpText: z.string().optional(),
  name: z.string().optional(),
  value: z.string().optional(),
  on_click: z.string().optional(),
  on_change: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgTooltipSchema = z.object({
  id: z.string(),
  component: z.literal('AgTooltip'),
  content: z.string().optional(),
  placement: z.enum(['top', 'top-start', 'top-end', 'right', 'right-start', 'right-end', 'bottom', 'bottom-start', 'bottom-end', 'left', 'left-start', 'left-end']).optional(),
  distance: z.number().optional(),
  skidding: z.number().optional(),
  trigger: z.string().optional(),
  disabled: z.boolean().optional(),
  on_show: z.string().optional(),
  on_hide: z.string().optional(),
  children: z.array(z.string()).optional(),
});

export const AgTextSchema = z.object({
  id: z.string(),
  component: z.literal('AgText'),
  text: z.string(),
  el: z.enum(['p', 'span', 'h1', 'h2', 'h3', 'h4', 'label']).optional(),
  children: z.array(z.string()).optional(),
});

export const AgNodeSchema = z.discriminatedUnion('component', [
  AgAccordionSchema,
  AgAlertSchema,
  AgAspectRatioSchema,
  AgAvatarSchema,
  AgBadgeSchema,
  AgBadgeFxSchema,
  AgBreadcrumbSchema,
  AgButtonSchema,
  AgButtonFxSchema,
  AgCardSchema,
  AgCheckboxSchema,
  AgDialogSchema,
  AgDividerSchema,
  AgDrawerSchema,
  AgFieldsetSchema,
  AgHeaderSchema,
  AgIconSchema,
  AgIconButtonSchema,
  AgIconButtonFxSchema,
  AgInputSchema,
  AgIntlFormatterSchema,
  AgKbdSchema,
  AgLinkSchema,
  AgLoaderSchema,
  AgMarkSchema,
  AgMessageBubbleSchema,
  AgPopoverSchema,
  AgProgressSchema,
  AgRadioSchema,
  AgRatingSchema,
  AgSelectSchema,
  AgSelectionButtonSchema,
  AgSelectionButtonGroupSchema,
  AgSelectionCardSchema,
  AgSelectionCardGroupSchema,
  AgSpinnerSchema,
  AgTabsSchema,
  AgTagSchema,
  AgToggleSchema,
  AgTooltipSchema,
  AgTextSchema,
]);
