// AUTO-GENERATED by v2/schema/scripts/codegen.ts — do not edit by hand
// Run: npm run codegen   (from v2/schema/)
// Source: v2/lib/src/components/*/core/_*.ts

export interface AgAccordionNode {
  id: string;
  component: 'AgAccordion';
  children?: string[];
}

export interface AgAlertNode {
  id: string;
  component: 'AgAlert';
  variant?: 'default' | 'primary' | 'success' | 'monochrome' | 'warning' | 'info' | 'error' | 'danger';
  bordered?: boolean;
  rounded?: boolean;
  borderedLeft?: boolean;
  dismissible?: boolean;
  on_dismiss?: string;
  children?: string[];
}

export interface AgAspectRatioNode {
  id: string;
  component: 'AgAspectRatio';
  width?: number;
  height?: number;
  maxWidth?: number;
  children?: string[];
}

export interface AgAvatarNode {
  id: string;
  component: 'AgAvatar';
  text?: string;
  imgSrc?: string;
  imgAlt?: string;
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  shape?: 'circle' | 'square' | 'rounded';
  variant?: 'default' | 'success' | 'monochrome' | 'warning' | 'info' | 'error' | 'transparent';
  ariaLabel?: string;
  children?: string[];
}

export interface AgBadgeNode {
  id: string;
  component: 'AgBadge';
  variant?: 'default' | 'primary' | 'success' | 'monochrome' | 'warning' | 'info' | 'danger' | 'neutral';
  size?: 'xs' | 'sm' | 'md';
  dot?: boolean;
  value?: number;
  max?: number;
  interactive?: boolean;
  statusLabel?: string;
  live?: 'off' | 'polite' | 'assertive';
  hiddenFromAT?: boolean;
  children?: string[];
}

export interface AgBadgeFxNode {
  id: string;
  component: 'AgBadgeFx';
  variant?: 'default' | 'primary' | 'success' | 'monochrome' | 'warning' | 'info' | 'danger' | 'neutral';
  size?: 'xs' | 'sm' | 'md';
  dot?: boolean;
  value?: number;
  max?: number;
  interactive?: boolean;
  statusLabel?: string;
  live?: 'off' | 'polite' | 'assertive';
  hiddenFromAT?: boolean;
  fx?: string;
  fxSpeed?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  fxEase?: 'ease' | 'ease-in' | 'ease-out' | 'ease-in-out' | 'bounce' | 'spring-sm' | 'spring-md' | 'spring-lg';
  fxDisabled?: boolean;
  children?: string[];
}

export interface AgBreadcrumbNode {
  id: string;
  component: 'AgBreadcrumb';
  type?: 'default' | 'slash' | 'bullet' | 'arrow';
  primary?: boolean;
  ariaLabel?: string;
  on_click?: string;
  children?: string[];
}

export interface AgButtonNode {
  id: string;
  component: 'AgButton';
  variant?: 'primary' | 'success' | 'monochrome' | 'warning' | 'danger' | 'secondary';
  size?: 'sm' | 'md' | 'lg' | 'xl' | 'x-sm';
  shape?: 'circle' | 'square' | 'rounded' | 'capsule' | 'rounded-square';
  bordered?: boolean;
  ghost?: boolean;
  link?: boolean;
  grouped?: boolean;
  fullWidth?: boolean;
  type?: 'button' | 'submit' | 'reset';
  disabled?: boolean;
  loading?: boolean;
  ariaLabel?: string;
  on_click?: string;
  on_toggle?: string;
  children?: string[];
}

export interface AgButtonFxNode {
  id: string;
  component: 'AgButtonFx';
  variant?: 'primary' | 'success' | 'monochrome' | 'warning' | 'danger' | 'secondary';
  size?: 'sm' | 'md' | 'lg' | 'xl' | 'x-sm';
  shape?: 'circle' | 'square' | 'rounded' | 'capsule' | 'rounded-square';
  bordered?: boolean;
  ghost?: boolean;
  link?: boolean;
  grouped?: boolean;
  fullWidth?: boolean;
  type?: 'button' | 'submit' | 'reset';
  disabled?: boolean;
  loading?: boolean;
  ariaLabel?: string;
  on_click?: string;
  on_toggle?: string;
  fx?: string;
  fxSpeed?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  fxEase?: 'ease' | 'ease-in' | 'ease-out' | 'ease-in-out' | 'bounce' | 'spring-sm' | 'spring-md' | 'spring-lg';
  fxDisabled?: boolean;
  children?: string[];
}

export interface AgCardNode {
  id: string;
  component: 'AgCard';
  stacked?: boolean;
  shadow?: boolean;
  animated?: boolean;
  rounded?: 'sm' | 'md' | 'lg';
  variant?: 'success' | 'monochrome' | 'warning' | 'info' | 'error';
  hasMedia?: boolean;
  mediaPosition?: 'top' | 'bottom';
  children?: string[];
}

export interface AgCheckboxNode {
  id: string;
  component: 'AgCheckbox';
  name?: string;
  value?: string;
  checked?: boolean;
  disabled?: boolean;
  size?: 'small' | 'medium' | 'large';
  labelText?: string;
  labelPosition?: 'end' | 'start';
  required?: boolean;
  invalid?: boolean;
  errorMessage?: string;
  helpText?: string;
  on_click?: string;
  on_change?: string;
  children?: string[];
}

export interface AgDialogNode {
  id: string;
  component: 'AgDialog';
  open?: boolean;
  heading?: string;
  description?: string;
  noCloseOnEscape?: boolean;
  noCloseOnBackdrop?: boolean;
  showCloseButton?: boolean;
  drawerPosition?: 'top' | 'bottom' | 'start' | 'end';
  on_open?: string;
  on_close?: string;
  on_cancel?: string;
  children?: string[];
}

export interface AgDividerNode {
  id: string;
  component: 'AgDivider';
  vertical?: boolean;
  justify?: 'end' | 'start' | 'center';
  size?: 'default' | 'small' | 'large' | 'xlarge';
  variant?: 'default' | 'success' | 'monochrome' | 'warning' | 'info' | 'error';
  children?: string[];
}

export interface AgDrawerNode {
  id: string;
  component: 'AgDrawer';
  open?: boolean;
  heading?: string;
  description?: string;
  noCloseOnEscape?: boolean;
  noCloseOnBackdrop?: boolean;
  showCloseButton?: boolean;
  position?: 'top' | 'bottom' | 'end' | 'start';
  on_open?: string;
  on_close?: string;
  on_cancel?: string;
  children?: string[];
}

export interface AgFieldsetNode {
  id: string;
  component: 'AgFieldset';
  legend?: string;
  bordered?: boolean;
  layout?: 'vertical' | 'horizontal';
  legendHidden?: boolean;
  children?: string[];
}

export interface AgHeaderNode {
  id: string;
  component: 'AgHeader';
  sticky?: boolean;
  contentJustify?: 'end' | 'start' | 'center' | 'between' | 'around';
  children?: string[];
}

export interface AgIconNode {
  id: string;
  component: 'AgIcon';
  size?: '14' | '16' | '18' | '20' | '24' | '32' | '36' | '40' | '48' | '56' | '64';
  type?: 'primary' | 'success' | 'monochrome' | 'warning' | 'info' | 'error' | 'action';
  noFill?: boolean;
  children?: string[];
}

export interface AgIconButtonNode {
  id: string;
  component: 'AgIconButton';
  label?: string;
  icon?: string;
  unicode?: string;
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  variant?: 'primary' | 'success' | 'monochrome' | 'warning' | 'danger' | 'secondary' | 'ghost';
  type?: 'button' | 'submit' | 'reset';
  disabled?: boolean;
  loading?: boolean;
  on_click?: string;
  on_activate?: string;
  children?: string[];
}

export interface AgIconButtonFxNode {
  id: string;
  component: 'AgIconButtonFx';
  label?: string;
  icon?: string;
  unicode?: string;
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  variant?: 'primary' | 'success' | 'monochrome' | 'warning' | 'danger' | 'secondary' | 'ghost';
  type?: 'button' | 'submit' | 'reset';
  disabled?: boolean;
  loading?: boolean;
  on_click?: string;
  on_activate?: string;
  fx?: string;
  fxSpeed?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  fxEase?: 'ease' | 'ease-in' | 'ease-out' | 'ease-in-out' | 'bounce' | 'spring-sm' | 'spring-md' | 'spring-lg';
  fxDisabled?: boolean;
  children?: string[];
}

export interface AgInputNode {
  id: string;
  component: 'AgInput';
  label?: string;
  labelHidden?: boolean;
  labelPosition?: 'top' | 'bottom' | 'end' | 'start';
  noLabel?: boolean;
  ariaLabel?: string;
  name?: string;
  type?: 'text' | 'password' | 'email' | 'number' | 'search' | 'tel' | 'url' | 'date' | 'datetime-local' | 'month' | 'time' | 'week';
  value?: string;
  placeholder?: string;
  rows?: number;
  cols?: number;
  size?: 'default' | 'small' | 'large';
  capsule?: boolean;
  rounded?: boolean;
  underlined?: boolean;
  underlinedWithBackground?: boolean;
  inline?: boolean;
  required?: boolean;
  disabled?: boolean;
  readonly?: boolean;
  invalid?: boolean;
  errorMessage?: string;
  helpText?: string;
  on_click?: string;
  on_change?: string;
  children?: string[];
}

export interface AgIntlFormatterNode {
  id: string;
  component: 'AgIntlFormatter';
  type?: 'number' | 'date' | 'percent' | 'currency';
  value?: string;
  lang?: string;
  date?: string;
  weekday?: 'narrow' | 'short' | 'long';
  era?: 'narrow' | 'short' | 'long';
  year?: 'numeric' | '2-digit';
  month?: 'narrow' | 'short' | 'long' | 'numeric' | '2-digit';
  day?: 'numeric' | '2-digit';
  hour?: 'numeric' | '2-digit';
  minute?: 'numeric' | '2-digit';
  second?: 'numeric' | '2-digit';
  timeZoneName?: 'short' | 'long';
  timeZone?: string;
  hourFormat?: '24' | 'auto' | '12';
  dateStyle?: 'medium' | 'short' | 'long' | 'full';
  timeStyle?: 'medium' | 'short' | 'long' | 'full';
  noGrouping?: boolean;
  currency?: string;
  currencyDisplay?: 'symbol' | 'narrowSymbol' | 'code' | 'name';
  minimumIntegerDigits?: number;
  minimumFractionDigits?: number;
  maximumFractionDigits?: number;
  minimumSignificantDigits?: number;
  maximumSignificantDigits?: number;
  children?: string[];
}

export interface AgKbdNode {
  id: string;
  component: 'AgKbd';
  variant?: 'default' | 'primary' | 'success' | 'monochrome' | 'warning' | 'info' | 'error' | 'danger' | 'secondary';
  bordered?: boolean;
  background?: boolean;
  size?: 'sm' | 'md' | 'lg';
  children?: string[];
}

export interface AgLinkNode {
  id: string;
  component: 'AgLink';
  href?: string;
  variant?: 'primary' | 'success' | 'monochrome' | 'warning' | 'danger';
  isButton?: boolean;
  buttonSize?: 'sm' | 'md' | 'lg' | 'xl' | 'x-sm';
  buttonShape?: 'circle' | 'square' | 'rounded' | 'capsule' | 'rounded-square';
  buttonBordered?: boolean;
  external?: boolean;
  disabled?: boolean;
  ariaLabel?: string;
  on_click?: string;
  children?: string[];
}

export interface AgLoaderNode {
  id: string;
  component: 'AgLoader';
  size?: 'default' | 'small' | 'large';
  ariaLabel?: string;
  children?: string[];
}

export interface AgMarkNode {
  id: string;
  component: 'AgMark';
  variant?: 'primary' | 'success' | 'monochrome' | 'warning' | 'info' | 'error' | 'secondary';
  search?: string;
  caseSensitive?: boolean;
  matchAll?: boolean;
  children?: string[];
}

export interface AgMessageBubbleNode {
  id: string;
  component: 'AgMessageBubble';
  from?: 'me' | 'them';
  message?: string;
  time?: string;
  author?: string;
  avatarUrl?: string;
  footer?: string;
  variant?: 'default' | 'success' | 'monochrome' | 'warning' | 'info' | 'danger' | 'neutral';
  children?: string[];
}

export interface AgPopoverNode {
  id: string;
  component: 'AgPopover';
  placement?: 'top' | 'top-start' | 'top-end' | 'right' | 'right-start' | 'right-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'left' | 'left-start' | 'left-end';
  distance?: number;
  skidding?: number;
  arrow?: boolean;
  disabled?: boolean;
  triggerType?: 'click' | 'hover' | 'focus';
  matchTriggerWidth?: boolean;
  showCloseButton?: boolean;
  showHeader?: boolean;
  closeLabel?: string;
  trapFocus?: boolean;
  on_show?: string;
  on_hide?: string;
  children?: string[];
}

export interface AgProgressNode {
  id: string;
  component: 'AgProgress';
  value?: number;
  max?: number;
  label?: string;
  size?: 'small' | 'medium' | 'large';
  children?: string[];
}

export interface AgRadioNode {
  id: string;
  component: 'AgRadio';
  name?: string;
  value?: string;
  checked?: boolean;
  disabled?: boolean;
  size?: 'small' | 'medium' | 'large';
  theme?: 'default' | 'primary' | 'success' | 'monochrome';
  labelText?: string;
  labelPosition?: 'end' | 'start';
  label?: string;
  labelHidden?: boolean;
  noLabel?: boolean;
  required?: boolean;
  invalid?: boolean;
  errorMessage?: string;
  helpText?: string;
  on_click?: string;
  on_change?: string;
  children?: string[];
}

export interface AgRatingNode {
  id: string;
  component: 'AgRating';
  value?: number;
  max?: number;
  precision?: 'whole' | 'half';
  readonly?: boolean;
  allowClear?: boolean;
  variant?: 'primary' | 'success' | 'monochrome' | 'warning' | 'danger' | 'secondary';
  size?: 'sm' | 'md' | 'lg';
  name?: string;
  label?: string;
  labelPosition?: 'top' | 'bottom' | 'end' | 'start';
  labelHidden?: boolean;
  noLabel?: boolean;
  required?: boolean;
  invalid?: boolean;
  errorMessage?: string;
  helpText?: string;
  children?: string[];
}

export interface AgSelectNode {
  id: string;
  component: 'AgSelect';
  size?: 'small' | 'large';
  multiple?: boolean;
  disabled?: boolean;
  name?: string;
  multipleSize?: number;
  label?: string;
  labelPosition?: 'top' | 'bottom' | 'end' | 'start';
  labelHidden?: boolean;
  noLabel?: boolean;
  required?: boolean;
  invalid?: boolean;
  errorMessage?: string;
  helpText?: string;
  on_click?: string;
  on_change?: string;
  children?: string[];
}

export interface AgSelectionButtonNode {
  id: string;
  component: 'AgSelectionButton';
  value?: string;
  label?: string;
  checked?: boolean;
  disabled?: boolean;
  children?: string[];
}

export interface AgSelectionButtonGroupNode {
  id: string;
  component: 'AgSelectionButtonGroup';
  type?: 'radio' | 'checkbox';
  name?: string;
  legend?: string;
  legendHidden?: boolean;
  theme?: 'success' | 'monochrome' | 'warning' | 'info' | 'error';
  size?: 'sm' | 'md' | 'lg';
  shape?: 'rounded' | 'capsule';
  value?: string;
  values?: string[];
  disabled?: boolean;
  required?: boolean;
  children?: string[];
}

export interface AgSelectionCardNode {
  id: string;
  component: 'AgSelectionCard';
  value?: string;
  label?: string;
  checked?: boolean;
  disabled?: boolean;
  children?: string[];
}

export interface AgSelectionCardGroupNode {
  id: string;
  component: 'AgSelectionCardGroup';
  type?: 'radio' | 'checkbox';
  name?: string;
  legend?: string;
  legendHidden?: boolean;
  theme?: 'success' | 'monochrome' | 'warning' | 'info' | 'error';
  value?: string;
  values?: string[];
  disabled?: boolean;
  required?: boolean;
  children?: string[];
}

export interface AgSpinnerNode {
  id: string;
  component: 'AgSpinner';
  size?: 'default' | 'small' | 'large' | 'xlarge';
  ariaLabel?: string;
  children?: string[];
}

export interface AgTabsNode {
  id: string;
  component: 'AgTabs';
  activation?: 'manual' | 'automatic';
  activeTab?: number;
  orientation?: 'vertical' | 'horizontal';
  ariaLabel?: string;
  children?: string[];
}

export interface AgTagNode {
  id: string;
  component: 'AgTag';
  variant?: 'primary' | 'success' | 'monochrome' | 'warning' | 'info' | 'error';
  shape?: 'circle' | 'pill' | 'round';
  uppercase?: boolean;
  removable?: boolean;
  on_remove?: string;
  children?: string[];
}

export interface AgToggleNode {
  id: string;
  component: 'AgToggle';
  label?: string;
  labelPosition?: 'top' | 'bottom' | 'end' | 'start';
  labelHidden?: boolean;
  noLabel?: boolean;
  checked?: boolean;
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  variant?: 'default' | 'success' | 'monochrome' | 'warning' | 'danger';
  disabled?: boolean;
  readonly?: boolean;
  required?: boolean;
  invalid?: boolean;
  errorMessage?: string;
  helpText?: string;
  name?: string;
  value?: string;
  on_click?: string;
  on_change?: string;
  children?: string[];
}

export interface AgTooltipNode {
  id: string;
  component: 'AgTooltip';
  content?: string;
  placement?: 'top' | 'top-start' | 'top-end' | 'right' | 'right-start' | 'right-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'left' | 'left-start' | 'left-end';
  distance?: number;
  skidding?: number;
  trigger?: string;
  disabled?: boolean;
  on_show?: string;
  on_hide?: string;
  children?: string[];
}
export interface AgTextNode {
  id: string;
  component: 'AgText';
  text: string;
  el?: 'p' | 'span' | 'h1' | 'h2' | 'h3' | 'h4' | 'label';
  children?: string[];
}

export type AgNode =
  | AgAccordionNode
  | AgAlertNode
  | AgAspectRatioNode
  | AgAvatarNode
  | AgBadgeNode
  | AgBadgeFxNode
  | AgBreadcrumbNode
  | AgButtonNode
  | AgButtonFxNode
  | AgCardNode
  | AgCheckboxNode
  | AgDialogNode
  | AgDividerNode
  | AgDrawerNode
  | AgFieldsetNode
  | AgHeaderNode
  | AgIconNode
  | AgIconButtonNode
  | AgIconButtonFxNode
  | AgInputNode
  | AgIntlFormatterNode
  | AgKbdNode
  | AgLinkNode
  | AgLoaderNode
  | AgMarkNode
  | AgMessageBubbleNode
  | AgPopoverNode
  | AgProgressNode
  | AgRadioNode
  | AgRatingNode
  | AgSelectNode
  | AgSelectionButtonNode
  | AgSelectionButtonGroupNode
  | AgSelectionCardNode
  | AgSelectionCardGroupNode
  | AgSpinnerNode
  | AgTabsNode
  | AgTagNode
  | AgToggleNode
  | AgTooltipNode
  | AgTextNode;

export type AgComponentName = AgNode['component'];
