export const getSiteDocsTemplate = ({ pascalCaseName, kebabCaseName }) => {
  // Note: Using unescaped backticks for markdown code fences
  // The triple backticks below are literal and will appear as-is in the output markdown file
  const codeFence = '```';

  return `# ${pascalCaseName}

Brief description of what the component does and when to use it.

<${pascalCaseName}Examples />

<script setup>
import ${pascalCaseName}Examples from '../examples/${pascalCaseName}Examples.vue'
</script>

## Usage

::: details Vue
${codeFence}vue
<template>
  <Vue${pascalCaseName} />
</template>
<script lang="ts">
import { defineComponent } from 'vue';
import { Vue${pascalCaseName} } from 'agnosticui-core/${kebabCaseName}/vue';
export default defineComponent({
  components: { Vue${pascalCaseName} }
});
</script>
${codeFence}
:::

::: details React
${codeFence}tsx
import { React${pascalCaseName} } from 'agnosticui-core/${kebabCaseName}/react';
export default function Example() {
  return <React${pascalCaseName} />;
}
${codeFence}
:::

::: details Lit (Web Components)
${codeFence}html
<script type="module">
  import 'agnosticui-core/${kebabCaseName}';
</script>
<ag-${kebabCaseName}></ag-${kebabCaseName}>
${codeFence}
:::

## Props

| Prop | Type | Default | Description |
|------|------|---------|-------------|
|      |      |         |             |

*This table can be auto-generated by the LLM agent based on the component's props interface.*

## Events

| Event | Payload | Description |
|-------|---------|-------------|
|       |         |             |

## Accessibility

This section can be filled out by the LLM agent based on the ${codeFence}SpecSheet.md${codeFence}.
`;
};
