name: Tests

on: [push, pull_request]

jobs:
  build:
    name: Run All Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install deps
        run: yarn

      - name: Run Svelte Tests
        working-directory: ./agnosticui-svelte
        run: |
          yarn test

      - name: Run React Tests
        working-directory: ./agnosticui-react
        run: |
          yarn test

      - name: Run Vue Tests
        working-directory: ./agnosticui-vue
        run: |
          yarn test
