name: Tests

on: [push, pull_request]

jobs:
  build:
    name: Svelte Jest Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install deps
        run: yarn

      - name: Change into svelte directory
        working-directory: ./agnosticui-svelte
        run: |
          yarn test
